src/plugins/geolocation.ts

https://github.com/driftyco/ionic-native/issues/34

fix(geolocation): set callback order to reverse on getCurrentPosition

---

src/plugins/dialogs.ts

In order to use promises I had to add default values to the properties. The reason is that the original plugin takes only one parameter for a callback function but does not have an error callback. 
An alternative would be to use `@Cordova({ sync: true })` instead and add the callback function parameter to the functions.

feat(plugin): add dialogs plugin

---

scripts/docs/templates/common.template.html

Shouldn't we use `cordova` instead of `ionic` in case of non-IonicCLI users trying to use Ionic Native?

chore(docs): change ionic to cordova in commands

---

src/plugins/camera.ts

The plugin docs should mention ionic-native and the required import format, which we only found in https://forum.ionicframework.com/t/camera-plugin-not-working-build-error/45004/4?u=jonrsharpe after searching for quite a while.

Show import format and link to ionic-native

---

src/plugins/toast.ts

The plugin now supports an arbitrary number of milliseconds for `duration`

Toast 2.5.0 duration change

---

src/plugins/toast.ts

Makes it clear how to import the Toast component into projects.

docs(toast): Add import statement for Toast

---

src/index.ts
src/plugins/file.ts

Well, the plugin is not fully complete. Some methods aren't implemented.
Methods not implemented :
- `getFreeDiskSpace` (usage of `cordova.exec`)
- `writeFile` (`options.append` and `options.truncate` that does not exists)
- `writeExistingFile` (`promise.abort` that does not exists)
- `readAs`* (`evt.target.result` and `evt.target.error` that does not exists)
I didn't search too much on how to fix errors as I'm only using `removeRecursively` for now.
About the documentation, I just used the ngCordova file plugin documentation as it's pretty much the same as the ionic-native file plugin.
Anyway, this is a start.

feat(plugin): add file plugin 

---

src/index.ts
src/plugins/network.ts

add cordova-network-information plugin

add network plugin for issue #89

---

src/plugins/batterystatus.ts

As seen in the [plugin documentation](https://github.com/apache/cordova-plugin-battery-status#batterystatus-event) the event used should be called "batterystatus" instead of "batterylevel". Currently the observable you provide in the onChange method never fires, beacuse it's listening to a wrong event. This pull request aims to fix that.

Correct battery-status "status" event name

---

src/plugins/plugin.ts

Zone.js now (helpfully) throws an error on unhandled rejections in
promises. This is great because they no longer silently fail, but we
were relying on that behavior for the case where the plugin isn't
installed or Cordova isn't available. With this change, those cases
won't throw an unhandled rejection error, but all regular plugin errors
still should.

fix(plugin): handle rejection when Cordova is undefined

---

src/index.ts
src/plugins/bluetoothserial.ts

feat(plugin): add Bluetooth Serial plugin

---

src/index.ts
src/plugins/deviceaccounts.ts

Adds Device Accounts Cordova plugin (https://github.com/loicknuchel/cordova-device-accounts) 
Requires the android.permission.GET_ACCOUNTS permission
Issue: https://github.com/driftyco/ionic-native/issues/140

Add DeviceAccounts plugin

---

src/plugins/file.ts

This minor addition will automatically append a trailing slash ```/``` when the path param does not end with a slash and is used to build a directory path via concatenation.

Append Trailing Slash If Not Present On path Param

---

src/plugins/globalization.ts

This allows client code to compile properly when TypeScript's `noImplicitAny` is enabled.

type return value of globalization's stringToNumber

---

src/plugins/background-geolocation.ts

As indicated in the issue [#101](https://github.com/driftyco/ionic-native/issues/101), there is a problem with the documentation of BackgroundGeolocation plugin. This PR fixes it.

Fix documentation problem in BackgroundGeolocation plugin

---

src/index.ts
src/ng1.ts
src/plugins/plugin.ts

This adds support for Angular 1, and also renames the service from `ngCordova` to `ionic.native`.

feat(angular1): Support Angular 1

---

src/index.ts
src/plugins/brightness.ts

I've implemented the support for using the [cordova-plugin-brightness](https://github.com/mgcrea/cordova-plugin-brightness) to control the display brightness of your device.
It's working on iOS and Android.

Implemented wrapper for display brightness control

---

src/plugins/socialsharing.ts

Starting from version 5.1.0, the [SocialSharing plugin docs](https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin#using-the-share-sheet) recommend to use the new method `shareWithOptions`, that takes an `options` object instead of the 4 arguments and returns a `result` object on success and an error message on failure. The result may include the app selected by the user for analytics purposes (currently iOS only).
This is much more convenient for Ionic developers as the current `share` method doesn't return anything.
This PR implements the `shareWithOptions` method with types and returns a promise with either a result or an error.

SocialSharing: Add recommended `shareWithOptions` method

---

src/plugins/safari-view-controller.ts

Changed it to `Promise<any>` as in the example. Was `void`.

Changed SafariViewController show return type

---

src/plugins/toast.ts

In the usage example the duration was displayed as a number instead of the actual string parameter.

Fix usage example mistake for duration type

---

src/plugins/sqlite.ts

This fix resolves a race condition with the SQLite constructor where the database was constructed but there was no way to wait on it. Now, the user must call `openDatabase` explicitly which returns a promise that they can wait on before working with the database.
I've also added some documentation to a few core methods as a quick start.

fix(sqlite): resolve race condition, add comments

---

src/plugins/push.ts

Update directly from [DefinitelyTyped phonegap plugin push](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/e42fdcf8b754727afbab9e402665bde60b0f0bf1/phonegap-plugin-push/phonegap-plugin-push.d.ts) to match the [specs](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#action-buttons-1) of the plugin. 
This allow the use of the action buttons on IOs with typescript projects.

Add support for Action Buttons on IOs with categories

---

src/index.ts
src/plugins/onesignal.ts

The OneSignal service is a provider for cloud messaging and push notifications. It has an official phonegap/cordova plugin but currently no Typescript support.
So I created a Ionic Native wrapper for this plugin with this PR.
OneSignal [Website](https://onesignal.com/)
OneSignal Cordova [Documentation](https://documentation.onesignal.com/docs/phonegap-sdk-installation)

Added wrapper for the Cordova OneSignal Plugin

---

src/plugins/backgroundmode.ts

@ihadeed I meant this fix, `de.appplant.cordova.plugin.background-mode` doesn't exist on npm ;)

docs(backgroundMode): fix plugin npm ID

---

src/plugins/spinnerdialog.ts

Just implemented the SpinnerDialog into my app to use with Ionic Deploy.
The cancelCallback still happens when set to "false", when setting it to "true, the cancelCallback doesn't get called and therefore the SpinnerDialog doesn't hide on Android, exactly as expected.

Update spinnerdialog.ts to fix wrong documentation

---

src/index.ts
src/plugins/media-capture.ts

feat(media-capture): add media capture plugin

---

src/index.ts
src/plugins/camera-preview.ts

Add [camera-preview-plugin](https://github.com/westonganger/cordova-plugin-camera-preview) to ionic-native

feat(camera-preview): add camera-preview

---

src/plugins/contacts.ts

The `@InstanceProperty` for `name` was missing. This made it impossible to set the name of a contact properly, rendering this plugin pretty much useless for creating contacts.
There were also some type issues:
1. `nickname` should be type `string`
2. `phoneNumbers` should be type `IContactField[]`
3. All types should use interfaces, as the objects themselves have an `_objectInstance` property.
4. `Contact` should implement `IContactProperties`
These bugs came in at v1.3.0, where this plugin was refactored, although the changelog does not mention this.

fix(contacts): missing name property, types

---

src/plugins/socialsharing.ts

- Add support for canShareViaEmail
- Make the following parameters in shareViaEmail method optional: cc, bcc, files
- Add usage for canShareViaEmail and shareViaEmail
- Fix some formatting to be more consistent
- Fix pluginRef

Add canShareViaEmail to SocialSharing plugin

---

src/index.ts
src/plugins/securestorage.ts

Plugin for https://github.com/Crypho/cordova-plugin-secure-storage

Add Secure Storage

---

src/plugins/filetransfer.ts

Hi,
Had a bit of difficulty on finding a complete example on using the [Transfer plugin](http://ionicframework.com/docs/v2/native/transfer/).  
I finally got it working and thought it would be nice to have a full example, so it might help someone in the future. 
I believe adding an example as a comment, will show that in the [documentation page](http://ionicframework.com/docs/v2/native/transfer/). If not please let me know where to do the changes :). 
cheers
Sam

example added for Transfer plugin

---

src/plugins/plugin.ts

This is a partial fix for #348 and #367 (ES6 promise's are currently given priority over ng1's $q so a scope.$apply is required for all promise callbacks as $q is never actually used).
The other half involves using an observable to trigger a digest which should be possible by using the rxjs [scope scheduler](https://github.com/Reactive-Extensions/rx.angular.js/tree/master/docs#rxscopescheduler).

fix(ng1): use $q promises instead of the native Promise

---

src/plugins/diagnostic.ts

* Location, camera, wifi, and bluetooth 'isEnabled' functions are incorrect. Corrected all to 'is Available'.

fix(diagnostic): corrects isEnabled functions to isAvailable

---

src/plugins/twitter-connect.ts

`<Fabric API Key>` seems to have broken http://ionicframework.com/docs/v2/native/twitter-connect/.

Change <Fabric API Key> to not break the doc formatter

---

src/plugins/touchid.ts

You can see the documentation code coloring is off due to the quotation marks. I went with `"` instead of escaping.

Fix quotes on TouchID.isAvailable error comment

---

src/plugins/vibration.ts

It doesn't matter what you send as the duration to vibrate() under iOS, it's always the same.

Added comment for iOS.

---

scripts/bower.json

When installing the bower package created from this, a couple of warnings are printed:
- bower ionic-native#* invalid-meta The "main" field cannot contain minified files
- bower ionic-native#* invalid-meta The "main" field has to contain only 1 file per filetype; found multiple .js files: ["ionic.native.js","ionic.native.min.js"]

Removed unnecessary ionic.native.min.js

---

src/plugins/ibeacon.ts

Since the plugin's methods return already a promise, the workaround with the `sync` option was used. This worked well for the method calls. However, when either cordova or the plugin was not available, an error was thrown, instead of rejecting the returned promise.
Therefore a better way is to use the `otherPromise` option, introduced with https://github.com/driftyco/ionic-native/releases/tag/v1.3.8.

Using option otherPromise instead of sync

---

src/index.ts

I couldn't import `GeolocationOptions` and `Coordinates` from `ionic-angular`. Is there any reason not to export these interfaces?
Thank you :)

Exported Geolocation interfaces.

---

src/index.ts
src/plugins/native-audio.ts

feat(native-audio): Add native audio plugin

---

DEVELOPER.md
TEMPLATE
gulpfile.js
package.json

Can now run the following command to generate a plugin wrapper from template + some instructions on how to use.
```
gulp plugin:create -n PluginName
// OR
npm run plugin:create -n PluginName
```

chore(): add plugin template and generator

---

src/index.ts
src/plugins/text-to-speech.ts
src/plugins/tts.ts

feat(TTS): add tts plugin

---

src/plugins/plugin.ts

We don't want that the reject cb takes the position of an optional argument that has not been defined.
For example the Dialogs.alert method takes an optional 'buttonLabel' string. In case we do not set this value, and thus want to use the default value, the 'reject' callback get spliced into this position due the fact that the splice start index is bigger than the array length.
`Dialogs.alert('mytitle', 'mymessage', 'Okay')`
args will become: 
`["title",  resolve, "message", "My button text", reject]`
`Dialogs.alert("title", "message")`
args will become:
`["title", resolve, "message", reject]` 
The latter will invoke the **cordova-plugins-dialog** alert method with the wrong arguments
--> reject is on the position of the buttonLabel
**cordova-plugins-dialog** alert method signature …

Add the reject function at the expected errorIndex position in the args array

---

src/plugins/file.ts

Exclusive means that the file will not be overriden so it has to be set if replace is False.

Fix(File): Fixing exclusive-option (override)

---

src/plugins/media.ts

This seems to make more sense to me. In the old implementation the getters were essentially useless, since MediaError returns a number, not the string error.
A nice side effect is this will get MediaError out of the docs TOC.

refactor(media): change MediaError to interface and error codes to static members

---

src/plugins/screen-orientation.ts

Well, seems like something was breaking the markdown table syntax.
Take a look at the screenshot below.

Fix the advanced table info

---

src/plugins/screenshot.ts

Screenshot was spelling wrong: `Screneshot`.

Fix Screenshot spelling on the example code.

---

src/plugins/geolocation.ts

The way this was setup previously, if an error occurred on the watchPosition observable, the observer was sent an error, which would have to be caught. This also has the side effect of completing the observable, which means anything down stream that would be subscribed would be unsubscribed and no longer receive updates.
Instead of using binding the error callback to ```observer.error``` this change just binds the error callback to ```observer.next``` and lets the subscriber filter out results that match ```PositionError``` rather than having to manage re-subscribing (which could just immediately fail and enter a loop of catch/retry)

Retain Observable even during an Error Condition

---

src/plugins/plugin.ts

Following on from discussion in https://github.com/driftyco/ionic-native/commit/2dc68a4785b7d9218a0d5bb936efd35cbb554e1b

fix(ng1): fail gracefully when angular 1 promises can't be retrieved

---

src/plugins/localnotifications.ts

Added a couple of missing features from the cordova-plugin-local-notifications repo
https://github.com/katzer/cordova-plugin-local-notifications/wiki/04.-Scheduling#permission

feat(localNotifications): added register and has permission functions

---

src/index.ts
src/plugins/location-accuracy.ts

feat(location-accuracy): add location accuracy plugin

---

src/plugins/googlemaps.ts

related to my first PR (https://github.com/driftyco/ionic-native/pull/580) and this issue: https://github.com/driftyco/ionic-native/issues/579
The commit (https://github.com/driftyco/ionic-native/commit/f36b1c03cbaed2ddc71d4cbd02d55959d2267258) does not fix the issue.

fix(googlemaps): typo in GoogleMapsTileOverlayOptions

---

src/plugins/googlemaps.ts

add support GoogleMapsLatLng[] as target as [documentation](https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/CameraPosition) states

fix(googlemaps): CameraPosition target can now be GoogleMapsLatLng[]

---

src/plugins/socialsharing.ts

Fix shareWithOptions method signature, replacing 'options.file' property with 'options.files' to match social sharing plugin [method interface](https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin/blob/master/src/android/nl/xservices/plugins/SocialSharing.java#L209)

Fix shareWithOptions method signature

---

src/plugins/push.ts

This is included in the push plugin typings but is missing from Ionic Native: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/phonegap-plugin-push/phonegap-plugin-push.d.ts

fix(push): Add support for passing notification id into finish

---

src/plugins/power-management.ts

Fixes the link that is generated in the docs here
http://ionicframework.com/docs/v2/native/powermanagement/

fix(PowerManagement): repo url

---

src/plugins/googlemaps.ts

When using the `Geocoder.geocode` method, the area can be restricted to a rectangle using the bounds array. This array is optional and can contain two `LatLng` objects. The first `LatLng` specifies the lower left corner, the second `LatLng` specifies the upper right corner.
See:
[Implementation in the plugin](https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/30a28dfee236bbdaa95e17b752f9c40116069b44/src/android/plugin/google/maps/MyGeocoder.java#L64)
[Android developer docs for the used method](https://developer.android.com/reference/android/location/Geocoder.html#getFromLocationName(java.lang.String, int, double, double, double, double))

feat(googlemaps): support bounds in Geocoder

---

src/index.ts
src/plugins/stepcounter.ts

Added support for https://github.com/texh/cordova-plugin-stepcounter

feat(stepcounter): add stepcounter plugin

---

src/plugins/googlemaps.ts

GoogleMaps.one() returns Promise not Observable

Changed observable to promise in docs

---

scripts/docs/dgeni-config.js
scripts/docs/tag-defs/tag-defs.js
scripts/docs/templates/common.template.html
src/plugins/camera.ts
src/plugins/googlemaps.ts

Now interfaces and related classes can be documented in the same page as the plugin.
I defined new tags for dgeni to recognize: `interfaces` and `classes`. Those tags must be placed in the plugin's JSDoc. Here's an example:
```
/**
* @name Google Maps
* @description This plugin uses the native Google Maps SDK
* @usage
...
* @interfaces
* AnimateCameraOptions
* CameraPosition
* MyLocation
* MyLocationOptions
* VisibleRegion
* GoogleMApsMarkerOptions
* GoogleMapsMarkerIcon
* GoogleMapsCircleOptions
* GoogleMapsPolylineOptions
* GoogleMapsPolygonOptions
* GoogleMapsTileOverlayOptions
* GoogleMapsGroundOverlayOptions
* GoogleMapsKmlOverlayOptions
* GeocoderRequest
* GeocoderResult
* @classes
* GoogleMapsMarker
* GoogleMapsCircle
* GoogleMapsPolyline
* GoogleMapsPolygon
* GoogleMapsTileOverlay …
```

document interfaces + other classes

---

src/plugins/camera.ts

Reading the document on which destination type, without commas leads to confusing behaviour.

Changed confusing sentence structure.

---

src/plugins/pay-pal.ts

Hey guys,
I'm getting this error while using the ionic-native PayPal plugin.
PayPal SDK: PayPalPayment not processable: Currency code is required.
**I'm using this code:**
PayPal.init({
"PayPalEnvironmentProduction": "YOUR_PRODUCTION_CLIENT_ID",
"PayPalEnvironmentSandbox": "YOUR_SANDBOX_CLIENT_ID"
}).then(() => {
let payment = new PayPalPayment('1.23', 'EUR', 'Charge money', 'intent');
PayPal.renderSinglePaymentUI(payment).then((s) => {
console.log('SUCCESS RENDER INIT', s);
}, (e) => {
console.log('ERROR RENDER INIT', e);
});
}, (e) => {
console.log('ERROR PAYPAL INIT', e);
});
**Explanation of this issue:**
The PayPal-Cordova-Plugin uses the _currency_ from the array instead _currencyCode_ so that this can never work. See https://github.com/paypal/PayPal-Cordova-Plugin/blob/master/src/io …

[PayPal] Fixed bug with currency code not found

---

src/plugins/pay-pal.ts

After I fixed the other #653 problem I find out that I'm unable to leave the "NoNetwork" mock environment.
So I searched for a solution and I found out that the PayPal scripts are not up to date with the cordova plugin repository.
With this update we are able to use PayPal via ionic-native in production and sandbox environments. So we can work with IPN's and everything and test as we like.
**Example pay flow...**
import {PayPal, PayPalPayment, PayPalConfiguration} from "ionic-native";
_[...]_
PayPal.init({
"PayPalEnvironmentProduction": "YOUR_PRODUCTION_CLIENT_ID",
"PayPalEnvironmentSandbox": "YOUR_SANDBOX_CLIENT_ID"
}).then(() => {
/** Environments: PayPalEnvironmentNoNetwork, PayPalEnvironmentSandbox, PayPalEnvironmentProduction */
PayPal.prepareToRender('PayPalEnvironmentSandbox', new …

Fixed problems with selection of PayPal environment

---

src/index.ts
src/plugins/themeable-browser.ts

- The name of ThemeableBrowser was mistaked as ThemableBroswer.
- The class name and some other typos was also fix to make this plugin works fine.

fix the name of themeablebroswer plugin, and make it works

---

src/plugins/onesignal.ts

fix(onesignal): update to match latest api

---

src/plugins/onesignal.ts

Delete enableNotificationsWhenActive() and add inFocusDisplaying() see issue https://github.com/OneSignal/OneSignal-Cordova-SDK/issues/103

fix(onesignal): delete method deprecated

---

src/plugins/googlemaps.ts

Adds the type property to GoogleMapsLatLngBounds
**Fixes:** #693

fix(googlemaps): Expose 'type' property in GoogleMapsLatLngBounds #693

---

src/plugins/mixpanel.ts
test/plugin.spec.ts
test/plugins/mixpanel.spec.ts

- Fixes Mixpanel.people issue (#677)
- Adds basic tests 
Closes #677

feat(mixpanel): make MixpanelPeople return promises

---

src/plugins/camera.ts

The constants used in CameraOptions are properties of Camera, not navigator.camera

Correct docs on where CameraOptions constants are defined

---

src/plugins/datepicker.ts

Changed `allowOldDate` property to `allowOldDates`
See documentation: https://github.com/VitaliiBlagodir/cordova-plugin-datepicker#allowolddates---ios

fix(datepicker): fix DatePicker allowOldDates option

---

src/plugins/inappbrowser.ts

It's [deprecated](https://www.google.com/search?q=deprecated) not [depreciated](https://www.google.com/search?q=depreciated).

Fix typo in inappbrowser.ts

---

src/plugins/camera-preview.ts

The newer repo reference in the README is incomplete, and does not function. This PR reverts to the older operable plugin, and assigns the appropriate repo to match.

Revert plugin and update repo to match

---

src/plugins/market.ts

The plugin reference is available as part of the global `cordova` object and not the global `plugins` object. This caused the plugin to `Plugin not installed warning` even though the plugin is installed and works when using through `cordova.plugins.market.open(appId);`

Plugin reference fix

---

src/plugins/media-capture.ts

Comment for `supportedImageModes()` meant for `supportedAudioModes()` and vice-versa.

docs(media-capture): fix documentation mixup

---

src/plugins/sqlite.ts

Addresses #592 
Can now create db using static method `SQLite.openDatabase()`. Also that method now resolves instance of Ionic Native's SQLite object instead of the original object.

fix(sqlite): add static constructor, and fix resolve type

---

src/plugins/camera-preview.ts

Just added the '?' to the parameter (size) in the static takePicture(size?: CameraPreviewSize): void { } because the size is a optional parameter

Parameter (size) is optional

---

src/plugins/android-fingerprint-auth.ts

Updated example
Added new configuration options.
Added new show() result fields
Added new delete method

update plugin android-fingerprint-auth to v1.2.1

---

src/plugins/diagnostic.ts

The latest release of Ionic Native started giving me errors because I'm using the ts `noImplicitAny` option.
This adds the missing types to the diagnostic plugin.

fix(diagnostic): add permissionStatus types

---

src/plugins/background-geolocation.ts

I figured out that altitudeAccuracy is missing based on my result in ios sim

add altitudeAccuracy into BackgroundGeolocationResponse

---

src/plugins/background-geolocation.ts

Fix a whitespace lint issue that makes `npm run lint` fail

style: fix whitespace lint issue

---

src/plugins/ble.ts

Fixes #943 - `stopScan()` was called incorrectly with arguments when used as `clearFunction`.

fix(ble): stopScan takes no args when used as clear function

---

src/plugins/onesignal.ts

OSNotification::app_id is not required when sending a selfNotification.

fix(onesignal): Made OSNotification::app_id optional

---

src/plugins/plugin.ts

I previously pushed a commit to wrap the `callCordovaPlugin` with a try/catch block. This approach wasn't ideal because in some cases the plugins have issues (uncaught exceptions) and the try/catch is getting rid of the necessary console logs for debugging.
https://github.com/driftyco/ionic-native/commit/54d1a9891beca23d229ff3b064110f3de6c86da2
This commit fixes that by only handling cases where the `pluginRef` exists  but the method doesn't exist. For example, the screen orientation plugin uses `window.screen` variable that exists on all devices, but only has the orientation property on mobile devices.

chore(): replace try/catch with better approach

---

src/plugins/googlemap.ts

I added a change that makes it clear that the map element needs a height to be visible.
I tried to follow the docs but It didn't work, after that I thought my API keys were invalid, at the end it turned out the map wasn't visible at all.

docs(google-maps) Make it clear that the map element needs a height

---

src/index.ts
src/plugins/headercolor.ts

fix [#760](https://github.com/driftyco/ionic-native/issues/760)

feat(headercolor): add HeaderColor plugin

---

src/plugins/plugin.ts

This reverts part of commit 67adb23, which moved the call to getPlugin()
from within CordovaProperty() to a point where it was called too early.
When the CordovaProperty decorator is called on a property, the class
containing that call has not yet had its Plugin decorator called. Only
when the latter happens does pluginRef get set. Thus, attempting to
access pluginRef within CordovaProperty at the time of the call will
give undefined, and attemping to call getPlugin with an undefined value
will throw an exception:
Runtime Error
Cannot read property 'split' of undefined
TypeError: Cannot read property 'split' of undefined
at get
at getPlugin
at CordovaProperty
at __decorate
...
The above message can be seen in the browser after running the 'ionic
serve' command.
This commit moves the …

Fix exception in CordovaProperty

---

src/plugins/push.ts

Fixes: https://github.com/driftyco/ionic-native/issues/983 and https://github.com/driftyco/ionic-native/issues/861

fix(push): #983 and #861

---

src/plugins/background-geolocation.ts

There seemed to be some discrepancies between the options you could pass in and the ones on the [plugin's github](https://github.com/mauron85/cordova-plugin-background-geolocation) so I updated them

fix(1011): Updating docs (seconds -> milliseconds) and adding options for ANDROID_ACTIVITY_PROVIDER provider

---

src/plugins/filetransfer.ts

Adding a link to **cordova plugin file** for ease of understanding file management using cordova.
It took me almost a day to figure out how to properly save things like a pdf/image in a publicly accessible directory. Having a link to the main **cordova file** documentation will save a lot of time.

Link to cordova-plugin-file

---

scripts/build/core-package.json.template
scripts/build/plugin-package.json.template

closes #1046 
Or we can update the ionic framework to use the stable version of rxjs,

chore(): change rxjs version to match ionic framework

---

src/plugins/apprate.ts

According to the `cordova-plugin-apprate` docs on their [Available Preferences Options](https://github.com/pushandplay/cordova-plugin-apprate#available-preferences-options), the plugin supports a `windows` option that takes the application URL in the Windows Store.
I've updated the interface to reflect that and the docs to show example usage.

fix(apprate): add missing Windows Store option

---

src/plugins/devicemotion.ts

AccelerationData interface is wrongly named in docs. It should be DeviceMotionAccelerationData. And I added it to import statement.

Docs for devicemotion.ts updated

---

src/plugins/inappbrowser.ts
test/plugins/inappbrowser.spec.ts

The InAppBrowser plugin has a lot of options/features that can be passed in during initialization, but without TypeScript it's hard to manage what options -- and their corresponding valid values -- are available.
This pull request adds the interface `InAppBrowserOptions` that will let users construct an object with tooling to display these valid options/features and suppress the values to those that are supported.
To integrate this change with the `InAppBrowser` class, I've overloaded the constructor. The `options` variable can now be of type `string` or `InAppBrowserOptions`. When the constructor is called, it type-checks the `options` parameter, if it exists. If the parameter is not a string, it will map the object into a comma-separated string that follows the InAppBrowser structure. …

feat(inappbrowser): add interface for IAB options

---

src/plugins/push.ts

according to https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/API.md#parameters, there is one clearBadge option in Android push options, which is missing in the ionic native push module interface at the moment.

add the missing cordova push android push option clearBadge

---

src/plugins/imagepicker.ts

add new outputType option. 
```
// output type, defaults to FILE_URIs.
// available options are 
// window.imagePicker.OutputType.FILE_URI (0) or 
// window.imagePicker.OutputType.BASE64_STRING (1)
outputType: int
```

fix(imagepicker): add outputType option

---

src/plugins/facebook.ts

It is necessary to have default values when calling Facebook.logEvent() instead of optional parameters. This is necessary because calling this method without any of the optional parameters, causes a bug where the second and third parameter are the callbacks instead of "null" or "undefined".
I am not sure if this is the case for any plugin using the optional parameter notation instead of default value, but I can confirm this one because it created a bug in my application.

Fix default facebook logEvent parameters

---

src/plugins/file.ts

Any declaration that is not being exported is missing from the resulting d.ts declaration files.

fix(file): add missing exports

---

src/plugins/inappbrowser.ts

Add `InAppBrowserOptions` to the list of `@interfaces` to appear in the ionic-native documentation.

chore(InAppBrowser)

---

src/plugins/googlemap.ts

The code to set the camera position and marker should be moved inside the function handling MAP_READY.  Otherwise they execute before the event is fired and it doesn't work.

Move marker code inside MAP_READY

---

src/plugins/media.ts

https://github.com/apache/cordova-plugin-media#mediapauserecord
https://github.com/apache/cordova-plugin-media#mediaresumerecord

fix(media): add missing pauseRecord and resumeRecord methods

---

src/plugins/pay-pal.ts

Type of items should be Array<PayPalItem> instead of string.

fix typing of "items" member in PayPalPayment

---

src/plugins/serial.ts

The `options` parameter of `Serial.requestPermission()` is entirely optional, and is only to be used as a last resort if a specific device is not (yet) included in the usb-serial-for-android library: https://github.com/xseignard/cordovarduino#your-device-is-not-yet-known.
This should be a rather uncommon case, and the plugin's documentation does not mention the `options` parameter in its introductory examples, so documentation was also slightly adapted.

fix(serial): Serial.requestPermission() options are optional

---

src/plugins/screen-orientation.ts

Screen Orientation version 1.4.2 's API
```javascript
lockOrientation() {}
```
not return promise, it return void.
Screen Orientation version 2.0's API changes the API to 
```javascript
lock(orientation): Promise<any>();
```
both name and return type changed.
but it is not been released to npm, so ionic native should handle 1.4.2 API correctly

fix(plugin): fix #1001, screen-orientation 1.4.2 lockOrientation not return promise.

---

src/index.ts
src/plugins/alipay.ts

Alipay plugin for Cordova/Ionic Applications.

feat(alipay): add new plugin for alipay support.

---

src/plugins/googlemap.ts

Inside  ionic-native maps documentation : moved `map.moveCamera(position);` **inside the MAP_READY event.** 
**Short description of what this resolves :**
Fix zoom on first launch on Android device. 
**Changes proposed in this pull request :**
moved `map.moveCamera(position);` inside the MAP_READY event.

Improve ionic-native maps documentation

---

src/plugins/file.ts

Promises that reject with a `FileError` are not of the type `Promise<T|FileError>`, but `Promise<T>`.
The previous declarations of `Promise<T|FileError>` would break typing further down the chain where you are trying to use the value that the typing says could be `T|FileError` but in reality could only be `T`.
```ts
File.readFileAsText(cordova.file.dataDirectory, 'some.json')
.then(json => JSON.parse(json));
```
This would result in `Argument of type 'string | FileError' is not assignable to parameter of type 'string'. Type 'FileError' is not assignable to type 'string'.'`

fix(File): typing where `FileError` can be thrown

---

src/plugins/googlemap.ts

Now matches: https://developers.google.com/maps/documentation/javascript/3.exp/reference#MapTypeId
Example...
import { GoogleMap, GoogleMapsEvent, GoogleMapsLatLng, GoogleMapsMapTypeId } from 'ionic-native';
this.map = new GoogleMap('map', {
'backgroundColor': 'white',
'mapType': GoogleMapsMapTypeId.HYBRID,
'controls': {
'compass': true,
'myLocationButton': true,
'indoorPicker': true,
'zoom': true
},
'gestures': {
'scroll': true,
'tilt': true,
'rotate': true,
'zoom': true
},
'camera': {
'latLng': location,
'tilt': 30,
'zoom': 15,
'bearing': 50
}
});

Added in a constant for MapTypeId in GoogleMaps

---

src/plugins/file.ts

fix(File): Platform Browser will raise a an DOMException on resoleLocalFilesystemUrl and tries to write on readonly property DOMException err.message in fillErrorMessage

fix(File): Platform Browser will raise a an DOMException

---

src/plugins/localnotifications.ts

The Cordova plugin Ionic Natives uses allows specifying the background color of the smallIcon.  By not including it in your interface you force users to use the default color for their version of Android.  While the LocalNotification plugin is not well documented, it does include this feature, see Options.java line 253:
```
/**
* @return
*      The notification background color for the small icon
*      Returns null, if no color is given.
*/
public int getColor() {
String hex = options.optString("color", null);
if (hex == null) {
return NotificationCompat.COLOR_DEFAULT;
}
int aRGB = Integer.parseInt(hex, 16);
return aRGB + 0xFF000000;
}
```
I've simply added the option to the interface as well as a short description.
This lets you go from the default color (varies by Android version): …

Add matching support for local notification icon background color

---

src/index.ts
src/plugins/unique-device-id.ts

This plugin is similar to how `device.uuid` works, except that it is iOS 6+ compatible by creating a uuid in the keychain to persist between app installs.

Added UniqueDeviceId plugin support

---

src/index.ts
src/plugins/background-fetch.ts

Adding the [Background Fetch](https://github.com/transistorsoft/cordova-plugin-background-fetch) plugin to the repo.

feat(background-fetch): Adding Background Fetch requested in #990

---

src/index.ts
src/plugins/photo-library.ts
src/plugins/plugin.ts

PhotoLibrary plugin for Cordova/Ionic Applications.
https://github.com/terikon/cordova-plugin-photo-library

feat(photo-library): added cordova-plugin-photo-library

---

src/index.ts
src/plugins/health.ts

Add support for [cordova-health-plugin](https://github.com/dariosalvi78/cordova-plugin-health)

feat(health): add wrapper for cordova-plugin-health

---

src/plugins/fingerprint-aio.ts

fingerprint-aio: setting 'use backup' as optional for android only.

fingerprint-aio: setting 'use backup' as optional for android only.

---

src/@ionic-native/core/bootstrap.ts
src/@ionic-native/core/decorators.ts
src/@ionic-native/core/index.ts
src/@ionic-native/core/plugin.ts
src/@ionic-native/core/util.ts
src/@ionic-native/plugins/file/index.ts
src/@ionic-native/plugins/google-maps/index.ts
src/@ionic-native/plugins/media/index.ts
src/@ionic-native/plugins/sqlite/index.ts
tsconfig.json

- split `plugin.ts` contents into separate files for organizational purposes
- added a global `tsconfig.json` so that the IDE can resolve imports during development. This will not be used to compile anything.
- added `@InstanceCheck()` and `@CordovaCheck()` decorators. 
---
Checks that the plugin exists before running the function. This is helpful in situations where we are writing custom code for a plugin and we only want to run it if the plugin is available. 
```typescript
//  basic example, code inside will only run if Cordova check passes
@CordovaCheck()
someMethod(): void {
console.log('I will only run if the plugin exists and we are running on Cordova');
}
// similar to example above
// except that it will return a promise that will never resolve/reject
// this ensures that it won't …
```

chore(): organize and enhance decorators

---

src/plugins/backgroundmode.ts

feat(background-mode): add missing functions moveToBackground and moveToForeground as explained in https://github.com/driftyco/ionic-native/issues/1180
Please can you add the following 2 functions into background mode:
cordova.plugins.backgroundMode.moveToBackground();
// or
cordova.plugins.backgroundMode.moveToForeground();
Found here:
https://github.com/katzer/cordova-plugin-background-mode#transit-between-application-states
The reason being is that overrideBackButton (https://github.com/driftyco/ionic-native/blob/master/src/plugins/backgroundmode.ts#L133) works really badly for opened nav pages. Instead of going back to the root it closes the App. However moveToBackground works perfectly when required without interfering with the hardware back button.

added moveToBackground and moveToForeground

---

src/plugins/music-controls.ts

There are more options available for iOS in https://github.com/homerours/cordova-music-controls-plugin. I have added Album name, duration and elapsed time to address added options.

Added music controls options for music-controls

---

src/plugins/googlemap.ts

fixed syntax error caused by mismatched parentheses and braces in the description

fixed syntax error in docs example

---

src/plugins/ble.ts

In the ble-central-plugin native plugin, the readRSSI method was missing in the wrapper, more info here:
https://github.com/don/cordova-plugin-ble-central/issues/338

Added function to read RSSI value to the ble plugin wrapper

---

src/@ionic-native/plugins/media/index.ts

The plugin was not working at all.
I think these are the reasons why:
1. There was a typo in MediaObject constructor
2. The MediaPlugin.create promise was never executed
3. The return object was not a MediaObject
I have tested these changes in one of my projects using startRecord, stopRecord and play functions.
I think the rest are also working. Test it before merging this pull request.

fix(media-plugin): MediaPlugin.create promise never fires

---

src/@ionic-native/plugins/music-controls/index.ts

There was a double .subscribe() function in `this.musicControls.subscribe()`

Removed duplicated subscribe()

---

src/@ionic-native/plugins/fingerprint-aio/index.ts

In the documentation, when calling `show()`, you logged 'any' in the console, instead of logging 'result'

Change 'any' to 'result' in documentation

---

src/@ionic-native/plugins/android-full-screen/index.ts

This PR adds support for [cordova-plugin-fullscreen](https://github.com/mesmotronic/cordova-plugin-fullscreen).
BTW, I think the `@usage` examples created by e.g.
```
gulp plugin:create -n AndroidFullScreen
```
should be updated to Ionic Native v3 - they still use the old static method syntax.

feat(android-full-screen): add cordova-plugin-fullscreen support

---

src/@ionic-native/plugins/zeroconf/index.ts

This PR adds support for [cordova-plugin-zeroconf](https://github.com/becvert/cordova-plugin-zeroconf), as requested in #636.
Please note that I only tested the browsing/watching functionality, since I've never published a zeroconf service myself (on a mobile device) and I wouldn't really know how to test that.
A note on naming: The plugin uses all lowercase `zeroconf` as pluginRef and in examples, but uses camel-case `ZeroConf` internally and sporadically in the docs. However, the [official zeroconf site](http://www.zeroconf.org/) refers to `Zeroconf` with initial caps only. I decided to go with the latter, even if that may look unfamiliar to some (but hey, so does `Geolocation`). It also avoid naming the package `zero-conf` which isn't used widely, and might cause even more confusion. …

feat(zeroconf): add cordova-plugin-zeroconf support

---

circle.yml
src/@ionic-native/plugins/status-bar/index.ts

Managed to drop build time to 20 seconds (from 1:45+).
- ionic-site is always cached, the scripts will take care of updating it
- node_modules gets restored from cache unless `package.json` changes (takes 10-20 more seconds to install them from scratch).
- configured it to update docs on master branch, it's a bit hacky now. Their docs say they will have a better way to do it soon
Just need to remove lines 7-9 and it's good to go. (the branches property)

chore(): use CircleCI 2

---

src/@ionic-native/plugins/jins-meme/index.ts

Add a more complete usage example showing scanning for JINS MEME smart glasses, connecting to them, and start a data report (subscription events fire at 100Hz)

docs(jins-meme): add extended usage example

---

src/@ionic-native/plugins/secure-storage/index.ts

I've added the keys() and clear() methods that are present in later versions of the cordova-secure-storage plugin (from 2.6.0 - 2016-10-26)

feat(secure-storage): add keys() and clear() methods

---

src/@ionic-native/plugins/flashlight/index.ts

There is a typo on line 14, changed from
```
* constructor(private flashlight: FlashLight) { }
```
to
```
* constructor(private flashlight: Flashlight) { }
```

Correct typo on Line 14

---

src/@ionic-native/plugins/music-controls/index.ts

The sample code does not work...this change returns the observable first with subscribe() before actually calling the Observable's subscribe method.
In fact, the way it's written in the example, the code would not build because of typescript errors.

Fix musicControls.subscribe() example code

---

src/@ionic-native/plugins/social-sharing/index.ts

ShareViaEmail parameter for providing email "must be null or an array" because it's type is "string:[]" and the provided syntax is wrong, so i have updated that syntax.

Syntax error in ShareViaEmail: typescript + ionic2

---

src/@ionic-native/plugins/media/index.ts

`getDuration` is synchronous, inside the example it was used with a promise, which is quite missleading...

Minor documentation fix

---

src/@ionic-native/plugins/google-plus/index.ts

Issue reported: https://forum.ionicframework.com/t/ionic-native-googleplus-unrecognized-selector-sent-to-instance/81944/3
In order to correctly call the login method on the GooglePlus provider you need to pass it the 'options' parameter even if it's empty.

The 'options' parameter is currently required

---

src/@ionic-native/plugins/sqlite/index.ts

The documentation for SQLite's `executeSql` method mentions that users must have previously called `openDatabase`, which I believe has been renamed/subsumed by the `create` method, so this PR adjusts the comment accordingly.

change executeSql doc to mention create instead of openDatabase

---

src/@ionic-native/plugins/health/index.ts

I made changes to cordova-plugin-health to accept the following array as datatypes. Earlier it was just an array of strings. Now it also contains an object with `read` and `write` array.
```
[
'calories', 'distance',   //read and write permissions
{
read : ['steps'],       //read only permission
write : ['height', 'weight']  //write only permission
}
]
```
Don't know how to specify this array in typescript so just replaced by 'any'

Update datatypes to match recent release of plugin

---

src/@ionic-native/plugins/keychain/index.ts

ionic-native for cordova ios keychain plugin

Ionic Native Keychain

---

scripts/build/build.js

This change allows developers to specify which plugins to build with the `build` script. If none are specified, all plugins are built as usual.

Specify list of plugins to build

---

src/@ionic-native/plugins/printer/index.ts

`this.p` is not defined as Printer is imported as `printer`

docs(printer): Fix example

---

src/@ionic-native/plugins/barcode-scanner/index.ts

Make an interface type for the result of barcode scanning, so it can return something more strongly typed than `Promise<any>`.

Type result of barcode scan

---

src/@ionic-native/plugins/camera-preview/index.ts

4 new methods are available in the master:
- getSupportedFocusModes();
- getFocusMode();
- seFocusMode();
- getFlashMode();
1 mistake correction for the FLASH_MODE type
Thanks in advance for the update

(CameraPreview) New focus methods & getFlashMode()

---

src/@ionic-native/plugins/google-maps/index.ts

It should be clearer now that the marker etc. should be added inside the .then() block
Related to: 
- https://github.com/driftyco/ionic-native/issues/1444
- https://forum.ionicframework.com/t/ionic-build-android-failed/88742/9

docs(google-maps): example fix #1444

---

src/@ionic-native/plugins/admob/index.ts

Because the Admob ad id differs according to the platform I imported the Platform to check the platform.

docs(admob): improved example

---

src/@ionic-native/plugins/app-preferences/index.ts

I changed the usage part to match the usage part of other plugins 
1. constructor with the private import
2. Call the plugin methods

docs(app preferences): unified example

---

src/@ionic-native/plugins/app-rate/index.ts

Because in the example the parameter for the promptForRating() method is false, the user has to set the usesUntilPrompt option otherwise the app rate prompt will never be shown.

docs(apprate): update example

---

src/@ionic-native/plugins/in-app-browser/index.ts

Nothing special I just changed https://ionic.io because the URL redirects to http://ionicframework.com/
One improvement would be if https://ionic.io would redirect to https:// and not to http://

docs(iab): https://ionicframework.com/

---

src/@ionic-native/plugins/email-composer/index.ts

This repo is out of beta and they fixed problems with newer android versions
https://github.com/hypery2k/cordova-email-plugin/commit/171b99b

docs(email composer): out of beta

---

src/@ionic-native/plugins/google-maps/index.ts

In the google-maps plugin, there is a `panBy()` function with no arguments. Looking at [the plugin code](https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/www/googlemaps-cdv-plugin.js), it should take two numeric strings.

add args to panBy()

---

src/@ionic-native/plugins/google-maps/index.ts

Fixed number of parameters to match the cordova-googlemaps [plugin](https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v1.4.0/class/Map/README.md).

Removed unecessary parameter for map method fromPointToLatLng.

---

src/@ionic-native/plugins/web-intent/index.ts

refactor(web-intent): updated source

---

src/@ionic-native/plugins/camera-preview/index.ts

Hi, everyone!
Just fixing a small typo: `PictureOptions` to `CameraPreviewPictureOptions`.

Fix interface name

---

src/@ionic-native/plugins/diagnostic/index.ts

by reversing callback order, rather than specifying callback indices (as added in commit 58db96147e973a264e1c013f46f93bccdfd9dfb4 due to recommendation in #1458), since the latter causes callbacks not to be invoked when using the plugin at runtime. This is consistent with the original implementation, e.g. for requestLocationAuthorization() which also has an optional 3rd argument.

fix(diagnostic plugin): fix Cordova decorator in camera API

---

src/@ionic-native/plugins/admob/index.ts

Using the example in the previous version of this document, calling `prepareInterstitial(adId)` resulted in an `-[__NSCFString count]: unrecognized selector sent to instance` exception on the ios platform. This was alleviated by changing the call to `prepareInterstitial({adId: adId})` 
(e.g. passing in an options object vs. just the adid string).
Interestingly enough this did not happen when calling `createBanner()`, so perhaps this is a bug with the admobpro plugin. In any case, this documentation adjustment should help folks in the meantime.

Use correct admobpro options for prepareInterstitial

---

src/@ionic-native/plugins/file/index.ts

Pass reader object on call function.
Fixes #1530

File plugin: file reader fix

---

src/@ionic-native/plugins/file/index.ts

What was the reason to remove `toInternalURL` from `Entry`?
Fixes #1560

Put back toInternalURL

---

src/@ionic-native/plugins/document-viewer/index.ts

refactor(document-viewer): fix example

---

src/@ionic-native/plugins/secure-storage/index.ts

The `create()` method reject the promise when the plugin is not available for avoid return a never fulfilled promise when we call the methods of `SecureStorageObject`
Closes #1515

fix(secure-storage): reject when the plugin doesn't exist

---

scripts/docs/templates/common.template.html

This PR makes it clear that installation is a two step process of 1) running commands on the CLI and 2) "Add this plugin to your app's module" (which links to the explanation in the Ionic Native Overiew at https://ionicframework.com/docs/native/#Add_Plugins_to_Your_App_Module). It also switches the plugin description with the installation commands.
This way users that "miss" this part of the docs will have a better Ionic Native experience and I hope most of the "This Ionic Native plugin is not working and throwing this strange error" posts in the forum will go away.
Currently:
After this PR is accepted and docs regenerated:

docs(template): Improved plugin docs

---

src/@ionic-native/plugins/dialogs/index.ts

Document the fact that confirm() will return a promise that resolves to 0 if the user clicks outside the dialog box. This behavior was previously undocummented and could lead to issues if not handled properly.

confirm() can return a promise that resolves to 0

---

src/@ionic-native/plugins/document-viewer/index.ts

Options for  viewDocument should be an DocumentViewerOptions object, not array of DocumentViewerOptions objects

Native DocumentViewer options type

---

package.json

Looks like ts 2.3.4 breaks the ci builds. Sorry for that

fix(ci): fix karma builds

---

src/@ionic-native/plugins/sqlite/index.ts

This allows the same plugin wrapper to be used with an alternative version that supports pre-filled sqlite databases.
See https://github.com/litehelpers/cordova-sqlite-ext
Installing sqlite-ext:
```
ionic cordova plugin add cordova-sqlite-ext --save
npm install --save @ionic-native/sqlite
```
Opening an existing database requires the "createFromLocation" param:
```
this.sqlite.create({
name: dbName,
location: 'default',
createFromLocation: 1
})
```
This patch adds that param as an optional parameter.

support pre-filled databases

---

src/@ionic-native/plugins/android-fingerprint-auth/index.ts

As seen in the Cordova plugin (https://github.com/mjwheatley/cordova-plugin-android-fingerprint-auth) the isAvailable method returns an object that contains 3 parameters, {isAvailable:, isHardwareDetected, hasEnrolledFingerprints}.
If you do a console log on
```
this.androidFingerprintAuth.isAvailable()
.then(res => console.log(res))  //{isAvailable: true, isHardwareDetected: true, hasEnrolledFingerprints: true}
.catch(err => console.error(err));
```
So we are getting the data, just need to make the interface expose it.

Android Fingerprint Auth - isAvailable method to return the proper object.

---

src/@ionic-native/plugins/in-app-purchase-2/index.ts

This should change the IAPProductEvents to follow the documentation and allow callbacks in their place. The documentation for the original plugin was a bit complicated. 
Didn't know what to do for the downloading callback. I haven't been able to test that piece.

(feat): change iap2 for callbacks

---

src/@ionic-native/plugins/intel-security/index.ts

Instead of intelSec it should be intelSecurity base on the name of the instance.

Correct typo in code example

---

src/@ionic-native/plugins/music-controls/index.ts

Plugin PR: https://github.com/homerours/cordova-music-controls-plugin/pull/71
This adds support for iOS' control center and lock screen time scrubber. This is a breaking change (probably needs to update to 2.0.0) as the event messaging system was changed to handle extra params (position in seconds) being passed back to Ionic from iOS. Now all message events are returned as json.

feat(music-controls): event for iOS control center seek and update elapsed time function

---

src/@ionic-native/plugins/pin-check/index.ts

New plugin that allows your application to check whether pin/keyguard or passcode is setup on iOS and Android phones.

feat(plugin): pin check

---

src/@ionic-native/plugins/toast/index.ts

The single quote needed to be escaped to providing proper syntax highlighting in documentation in Usage part of [Toast Docs](http://ionicframework.com/docs/native/toast/)

docs(Toast) template literal in example usage

---

scripts/docs/templates/common.template.html

This PR adds anchors to the headlines in the Ionic Native docs. There already were some for the methods, but the section headlines like "Installation" or "Usage" were not linkable yet.

docs(template): add anchors to make headlines in Ionic Native docs linkable

---

src/@ionic-native/plugins/document-viewer/index.ts

- Before it forced defining all properties
- Option arguments can be found [here](https://github.com/sitewaerts/cordova-plugin-document-viewer#options)

Made Optional `DocumentViewerOptions` Optional

---

src/@ionic-native/plugins/google-maps/index.ts

BREAKING CHANGES: Google Maps definitions now only support v2 of the plugin. v1 will no longer be supported.

feat(google-maps): update wrapper to support v2 of the plugin

---

src/@ionic-native/plugins/file-transfer/index.ts

BREAKING CHANGE: Package name is now `@ionic-native/file-transfer`. `Transfer` class has been
renamed to `FileTransfer`. Also, `TransferObject` class has been renamed to `FileTransferObject`.

refactor(file-transfer): rename to FileTransfer to match original plugin

---

src/@ionic-native/plugins/admob-pro/index.ts

BREAKING CHANGE: `@ionic-native/admob` is now `@ionic-native/admob-pro`. Also, class name is changed from `AdMob` to `AdMobPro`.

refactor(admob-pro): rename plugin from AdMob to AdMobPro

---

src/@ionic-native/plugins/image-resizer/index.ts

Running original command "ionic cordova plugin add https://github.com/protonet/cordova-plugin-image-resizer.git" will throw a Cordova error shown below. Installing the plugin via the plugin cordova id (per the original repo's package.json) will allow this plugin to install correctly and work with the ionic native "image-resizer"
An error occurred while running ionic cordova plugin add https://github.com/protonet/cordova-plugin-image-resizer.git
... (exit code 1):
Error: Failed to fetch plugin https://github.com/protonet/cordova-plugin-image-resizer.git via registry
...

Update image-resizer index.ts

---

scripts/docs/processors/jekyll.js
scripts/docs/tag-defs/tag-defs.js
scripts/docs/templates/common.template.html
scripts/docs/templates/native_menu.template.html
src/@ionic-native/plugins/admob/index.ts
src/@ionic-native/plugins/native-keyboard/index.ts

Attn. @perrygovier 
This PR changes the following:
- adds a `paid` tag
- shows a paid label in the menu
- shows a paid label on the plugin's doc page
- shows a notice that tells the user that the plugin might require a license or might take shares of profits
- simplified the native menu template, I pushed the beta plugins to the end of the array using JS
Action needed before merging:
Need to add two new CSS styles:
- `span.paid`: used for the label shown in menu & doc page, similar to the beta label
- `p.paid-notice`: used for the paid plugin notice shown on the doc page

docs(): add paid tag

---

scripts/docs/templates/common.template.html
src/@ionic-native/plugins/in-app-purchase-2/index.ts

This was causing an issue on http://ionicframework.com/docs/native/in-app-purchase-2/ where the command `ionic cordova plugin add cc.fovea.cordova.purchase --variable BILLING_KEY="<ANDROID_BILLING_KEY>"` was being interpreted as HTML and not allowing the code block to close.  This escapes those characters.

Escape < and > from plugin install command in doc template

---

src/@ionic-native/plugins/phonegap-local-notification/index.ts

$ ionic cordova plugin add phonegap-local-notifications -- should be -- 
$ ionic cordova plugin add phonegap-plugin-local-notification -- in Docs --

Incorrect Installation Instructions in Docs

---

src/@ionic-native/plugins/background-mode/index.ts

Fixed some typos in [the doc](http://ionicframework.com/docs/native/background-mode/) and a hopefully a bug in the  `BackgroundModeConfiguration` table at the bottom of the page.

Fix Background Mode doc

---

src/@ionic-native/plugins/google-maps/index.ts

https://stackoverflow.com/questions/45137375/ionic-2-use-htmlinfowindow-in-native-cordova-plugin-googlemaps

feat(google-maps): add missing features and fix wrong definitions

---

src/@ionic-native/plugins/sqlite/index.ts

As described in [this forum thread](https://forum.ionicframework.com/t/execution-failed-for-task-processdebugresources-ionic-compile/103001), users of [cordova-sqlitecipher-adapter](https://github.com/litehelpers/Cordova-sqlcipher-adapter) will encounter type errors when adding their needed encryption key to `SQLite.create()` calls. This PR adds it as an optional parameter.

add optional key parameter to SQLiteDatabaseConfig to support sqlcipher-adapter

---

src/@ionic-native/plugins/fingerprint-aio/index.ts

This PR introduces two properties to the `FingerprintOptions` interface that are available in the Cordova plugin but missing in Ionic Native. When building for iOS, it seems the Touch ID dialog will not display unless unless 'localizedFallbackTitle' and 'localizedReason' are provided.

fix(fingerprint-aio): add missing FingerprintOptions properties

---

src/@ionic-native/plugins/android-permissions/index.ts
src/@ionic-native/plugins/nfc/index.ts

show an example of how the event listeners work with observable subscription and implement an nfc share within the event listener.

docs(nfc): update usage doc of the nfc plugin

---

src/@ionic-native/plugins/push/index.ts

Browser Push interface with options to use push notification with browsers , as a proxy to phonegap-plush-plugin.
Based on the official docs for `phonegap-plugin-push`:
* https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/API.md#browser
I guess this is what we need to achieve this issue:
* https://github.com/ionic-team/ionic-native/issues/1847

Browser Push notification support

---

src/@ionic-native/plugins/background-geolocation/index.ts

BackgroundGeolocationResponse was not declared in classes to import from @ionic-native/background-geolocation

Adding missing import class

---

src/@ionic-native/plugins/clipboard/index.ts

Removing browser from the list of supported platforms.
Browser being listed in the supported platforms is conflicting with the data in plugin git repo.

supported platforms

---

src/@ionic-native/plugins/google-maps/index.ts

Since the new googlemaps plugin uses the native code, you need to wait for the platform to be ready before loading the map. If you try to create a maps page using the instructions currently on https://ionicframework.com/docs/native/google-maps/ your map will not render.

Updating googlemaps documentation

---

scripts/docs/processors/jekyll.js

fixes the problem that each navigation item first has to redirected to the version with trailing slash
closes https://github.com/ionic-team/ionic-site/issues/1223

docs(navigation): add trailing slash to navigation items

---

src/@ionic-native/plugins/http/index.ts

Fixes PR #1921 wrong plugin reference

HTTP Plugin reference fix

---

src/@ionic-native/plugins/zeroconf/index.ts

This now includes the value 'resolved', as it is a valid action passed by the service browser on iOS (at least) when IP addresses for the chosen service have been resolved.
This allows people to simplify the process of capturing services with resolved IP addresses.

Extended the ZeroconfResult.action definition

---

src/@ionic-native/plugins/firebase-dynamic-links/index.ts

Added:
`
Variable REVERSED_CLIENT_ID can be found in your GoogleService-Info.plist under the same key name.
Variable PHOTO_LIBRARY_USAGE_DESCRIPTION specifies required value for NSPhotoLibraryUsageDescription on iOS.
`
See: https://github.com/chemerisuk/cordova-plugin-firebase-dynamiclinks

Add required variables to index.ts

---

src/@ionic-native/plugins/index-app-content/index.ts

This PR adds the cordova-index-app-content plugin. 
I am not really sure if attaching the `onItemPressed` function works like expected. Maybe Ionic Native contributores could help.
I am looking forward hearing your feedback.

feat(indexappcontent) add Index-App-Content plugin (spotlight feature)

---

src/@ionic-native/plugins/android-full-screen/index.ts

This adds support for a new method `setSystemUiVisibility` that was added in version 1.2 of [cordova-plug-fullscreen](https://github.com/mesmotronic/cordova-plugin-fullscreen). The new method allows you to manually specify an Android System UI mode.

feat(android-full-screen): add support for setSystemUiVisibility

---

src/@ionic-native/plugins/launch-navigator/index.ts

Fixes an issue with the latest launch-navigator plugin (v4). Plugin expects options to be second parameter passed into method `navigate` but ionic-native wrapper was setting the success callback as the second input parameter.

Fixed success & error index for launch-navigator.navigate

---

src/@ionic-native/plugins/zeroconf/index.ts

Hi!
The `ZeroconfResult` interface spec is incomplete. The `action` property can also have the `resolved` value.

Zeroconf: Incomplete spec - Action can also be `resolved`

---

src/@ionic-native/plugins/firebase/index.ts

The return value of the hasPermission() promise is set to return any, but really returns an object that returns with an isEnabled flag

update return value in hasPermission()

---

src/@ionic-native/plugins/geolocation/index.ts

Hello guys,
I make this pull request to add the installation variable `GEOLOCATION_USAGE_DESCRIPTION` needed on iOS, since version 10.
Without this variable, using `getCurrentPosition` do nothing on iOS because phone wait user authorization. But that authorization is not display because there is no message defined.
This variable make this part of code in `info.plist` : 
```
<key>NSLocationWhenInUseUsageDescription</key>
<string>To allow locate you</string>
``` 
Source : https://github.com/apache/cordova-plugin-geolocation#ios-quirks
Have a good coding day :)

Update documentation for a installation variable

---

package-lock.json
package.json

Fix for https://github.com/ionic-team/ionic-native/issues/1798

Use RxJS 5.4.2 to fix generics checking in TS 2.4.1

---

package.json

The Ionic-Angular repo now uses Angular 5 so we could also update ionic-native.

chore(package): bump Angular

---

src/@ionic-native/plugins/jins-meme/index.ts

The most important change here is to point to the BlyncSync version of the plugin, which is actively maintained.  The jins-meme version lacks a package.json, which causes issues on some platforms that will result in an inability to build.
The plugin name should be JINS MEME ES (ES for Eye-Sensing,) as this is how the product is actually named: not "Jins Meme."
The BlyncSync plugin also uses standard naming convention for cordova plugins (cordova-plugin-jins-meme-es)

fix(jins-meme): update plugin repo to one which contains a package.json

---

src/@ionic-native/plugins/mobile-accessibility/index.ts

A fix so the plugin references the correct methods in the actual plugin. 
See: #2138

fix(mobile-accessibility): change signature references to the correct methods

---

src/@ionic-native/plugins/nfc/index.ts

This commit adds the missing references to UriHelper and TextHeler.
There were missing references to some methods of nfc and ndef modules.
The constants for ndef has ben added.

feat(nfc): Add interfaces and missing references to UriHelper and TextHelper

---

src/@ionic-native/plugins/braintree/index.ts

Adds support for the Braintree Drop-In Payments UI via `cordova-plugin-braintree`.
NOTE: Does not use the npm version of `cordova-plugin-braintree`, which is out of date and not maintained. This is intended to be used by a maintained fork at https://github.com/Taracque/cordova-plugin-braintree
Addresses #1373 
@danielsogl 
@wwallace

feat(braintree): add plugin support

---

src/@ionic-native/plugins/push/index.ts

This commit adds support for the following methods:
- createChannel
- deleteChannel
- listChannels
Also, I modified the PushEvent definition to allow any string, this because version 2.1.0 also allows to listen  to action button callbacks: [Action buttons documentation](https://github.com/phonegap/phonegap-plugin-push/blob/v2.1.0/docs/PAYLOAD.md#action-buttons)
Finally, I modified the finish() method, so that it can receive the notification id [push.finish documentation](https://github.com/phonegap/phonegap-plugin-push/blob/v2.1.0/docs/API.md#pushfinishsuccesshandler-errorhandler-id---ios-only)

feat(push) add support for version 2.1.0

---

src/@ionic-native/plugins/network-interface/index.ts

Adds support for the `cordova-plugin-networkinterface` plugin.

feat(network-interface): add plugin support

---

src/@ionic-native/plugins/music-controls/index.ts

Add hasScrubbing variable to options - used to enable or disable scrubbing from the iOS control center or lockscreen progress bar
Make non required options actually non-required.
Correct errors in usage examples.

fix (music-controls) make optional items optional, add hasScrubbing value for lock screen seeking

---

src/@ionic-native/plugins/apple-pay/index.ts

trueflywood's fork is currently used for this plugin. I'm changing it back to the original which contains the current changes and also includes type definitions and methods for the new version as well as documentation updates.
The diff here is a little weird and some things were not changed although they are showing up in the diff. A summary of changes:
* Updated `repo` to match the one used for `cordova-plugin-applepay` which is the most up-to-date
* Added a couple more types for transaction completion and new methods
* Organized IPaymentResponse type and updated to match plugin response
* Added `IOrderItemsAndShippingMethods` type used by the new update method. `IOrder` can extend from this type, and now billing/shipping requirements can be an array
* Added selected shipping contact …

feat(apple-pay): update for version 3 of the Apple Pay plugin.

---

src/@ionic-native/plugins/index-app-content/index.ts

Now `onItemPressed` will return an Observable. This should improve adding an event.
Inspired by the 3dTouch plugin function `onHomeIconPressed`.

fix(indexappcontent): onItemPressed returns observable

---

src/@ionic-native/plugins/three-dee-touch/index.ts

The `onHomeIconPressed` function now also uses the `CordovaFunctionOverride` decorator like suggested in #2006.

refactor(three-dee-touch) Use CordovaFunctionOverride decorator

---

src/@ionic-native/plugins/push/index.ts

phonegap-plugin-push requires `senderID` as an Android option. This change allows TypeScript to acknowledge this parameter and enforce this requirement.
Type definition here: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/phonegap-plugin-push/index.d.ts#L129

Add senderID to AndroidPushOptions

---

src/@ionic-native/plugins/alipay/index.ts

the latest version (2017-11-21) of the server-side now undertakes the job of assembling the json object into a parameters-string that can be inserted directly into the pay() function; and returns this parameter-string instead of the corresponding json (which is the previous behavior)
I checked the corresponding Alipay Cordova plugin([https://github.com/xueron/cordova-alipay-base](https://github.com/xueron/cordova-alipay-base)), and found out that the 'execute()' does also expect a string input (see below code snipe) :
```
@Override
public boolean execute(String action, JSONArray args, final CallbackContext callbackContext) throws JSONException {
Log.d(TAG, "Execute:" + action + " with :" + args.toString());
if (action.equals("pay")) {
String payParameters = null;
if (args.get(0) …
```

/plugins/alipay/index.ts add 'string' as an alternative type for 'pay()' input parameter;

---

src/@ionic-native/plugins/firebase/index.ts

The `setAnalyticsCollectionEnabled` method was exposed through [this PR](https://github.com/arnesson/cordova-plugin-firebase/pull/592)

Added setAnalyticsCollectionEnabled to Firebase plugin

---

src/@ionic-native/plugins/google-maps/index.ts

so this updates the docs to use static method.

docs(GoogleMaps): GoogleMaps.prototype.create is deprecated

---

src/@ionic-native/plugins/local-notifications/index.ts

Following cordova-plugin-local-notifications updates (https://github.com/katzer/cordova-plugin-local-notifications).
Method to gain permission change its name but signature stay the same
(first contribution ever here so don't hesitate to mentor me and to be nice ;)

ref(local-notifications): Replace registerPermission by requestPermission

---

src/@ionic-native/plugins/code-push/index.ts

The example: https://github.com/Dellos7/example-cordova-code-push-plugin contains an up-to-date example of how to use this plugin with Ionic; the current link is an outdated one.

docs(code-push) updated example link to an up to date one

---

src/@ionic-native/plugins/contacts/index.ts

Problem: 
Filtering by ContactFieldTypes such as 'familyName'/'formatted'/'givenName' gives bad results. 
Proposal: 
Add 'name.' prefix to ContactFieldTypes that are properties of ContactName
Additional info: 
I know this plugin is deprecated, but I think a lot of people would still benefit from this.

Add missing name. prefix for ContactFieldTypes

---

src/@ionic-native/plugins/health-kit/index.ts

I added two properties to `HealthKitOptions`. They are used when calling `querySampleType()`.
https://github.com/Telerik-Verified-Plugins/HealthKit/blob/bee29d76b9b0ce54bb134a910832427464d8f440/src/ios/HealthKit.m#L1271-L1272

feat(health-kit): add missing properties to HealthKitOptions

---

src/@ionic-native/plugins/navigation-bar/index.ts

In line 20, "this.navigationBar.hide(autoHide);". But there is no such a function .hide(). It shoud be correct as "this.navigationBar.setUp(autoHide);".

docs(navigation-bar): rename mismatched function

---

src/@ionic-native/plugins/firebase-dynamic-links/index.ts

*Summary*
The `sendInvitation` method was removed as well as the related configuration variables. Also `onDynamicLink ` can be called multiple times during the app lifecycle so it makes more sense that it is an Observable.

feat(firebase-dynamic-links): update to conform to the latest version of the plugin

---

src/@ionic-native/plugins/intercom/index.ts

As of Intercom Cordova 4.0.0 setSecureMode has been removed. Updating docs to indicate to use setUserHash instead https://github.com/intercom/intercom-cordova/blob/master/CHANGELOG.md#400-2017-08-29
Unsure if this is the correct syntax as wasn't sure how to run the docs locally. Any guidance on setting that up and correct syntax for would be appreciated 👍

docs(intercom): add deprecated notice for setSecureMode

---

src/@ionic-native/plugins/in-app-browser/index.ts

The current example in the docs is incomplete and thus quite useless. Just on its own won't manipulate the CSS of a loaded page. It requires the InAppBrowserEvent, and using it in the callback.

docs(in-app-browser): insertCSS example update

---

src/@ionic-native/plugins/onesignal/index.ts

- Script to match module definition (fixes paths)  
- Instructions to define hooks in recommend way

docs(onesignal): change docs to match new Cordova hook specs

---

src/@ionic-native/plugins/globalization/index.ts

As stated in the plugin repo, the options field is optional. Also, the plugin returns a `iana_timezone` property such as 'America/New_York' which was not included.

fix(globalization): options as optional

---

src/@ionic-native/plugins/jins-meme/index.ts

In order to enable background mode data collection we used the cordova-plugin-background-mode plugin in a new Cordova plugin repo, cordova-plugin-jins-meme (vs. cordova-plugin-jins-meme-es.)  We opted to maintain the old repository for backwards-compatibility as we have multiple apps using various versions; this is simplest.
Another unrelated change was made to silence unnecessary console logging.

feat(jins-meme): enable background mode data collection

---

src/@ionic-native/plugins/hot-code-push/index.ts

This is different from the current `code-push` which is tied to the Microsoft API, this plugin does not require to use Microsoft and can work with any server.
One thing I didn't add in the plugin: https://github.com/nordnet/cordova-hot-code-push/wiki/Listen-for-update-events. I am not sure if I can map these events somehow in the plugin

feat(plugin): add cordova-hot-code-push

---

src/@ionic-native/plugins/web-intent/index.ts

The `onNewIntent` function doesn't exist in `darryncampbell-cordova-plugin-intent`, it's actually called `onIntent`.
Source: https://github.com/darryncampbell/darryncampbell-cordova-plugin-intent/blob/master/www/IntentShim.js#L62
This PR renames `onNewIntent` to `onIntent`, as the implementation was right (should return an Observable). It also removes the previous `onIntent` as it was wrong and shouldn't return `void` anyway.
The change has been tested on device with latest `ionic-angular@3.9.2` and over `@ionic-native/web-intent@4.5.2`.

fix(web-intent): rename `onNewIntent` to `onIntent`

---

src/@ionic-native/plugins/call-log/index.ts

Hello, thanks for the previous merge.
We updated our plugin to 1.2.0, added the 'like' filter, and value can now be also an array.

feat(call-log): add operator 'like' and array of values

---

package-lock.json
src/@ionic-native/plugins/local-notifications/index.ts

cordova-plugin-local-notifications v0.9 has a bunch of new features.
There are some breaking changes upgrading from v0.8, e.g. the trigger property of the local notifications.
The changes proposed in  #1919 are already included

 feat(local-notifications): Support version 0.9.0-beta.3 of cordova-plugin-local-notifications

---

src/@ionic-native/plugins/zeroconf/index.ts

As mentioned in [zeroconf cordova plugin doc](https://github.com/becvert/cordova-plugin-zeroconf#usage), setting the watchAddressFamily and registerAddressFamily speed things up.

feat(zeroconf) add watchAddressFamily and registerAddressFamily

---

src/@ionic-native/plugins/openalpr/index.ts

Adds support for [cordova-plugin-openalpr](http://github.com/iMicknl/cordova-plugin-openalpr). Just tested this with the v2.0 version of our plugin and it works like a charm.
Will all documentation be generated from the index.ts or is there a place where I need to commit this?

feat(plugin): add OpenALPR plugin

---

src/@ionic-native/plugins/camera-preview/index.ts

Add `disableExifHeaderStripping` to `CameraPreviewOptions` for https://github.com/cordova-plugin-camera-preview/cordova-plugin-camera-preview.

feat(camera-preview): add disable exif stripping conf

---

src/@ionic-native/plugins/card-io/index.ts

Came across it while implementing the functionality. The manual entry button wouldn't go away. After some digging noticed that the Ionic docs had a typo in the property name.

fix(card-io): Fix typo in the "suppressManual" property name.

---

src/@ionic-native/plugins/uptime/index.ts

Added iOS support.
How can we change this page?
https://ionicframework.com/docs/native/uptime/
The installation does not contain the cordova plugin installation (ionic cordova plugin add cordova-plugin-uptime)
Thanks!

docs(uptime): add iOS support

---

src/@ionic-native/plugins/google-nearby/index.ts

Hi, I would like to merge a new plugin that wraps [this cordova plugin ](https://github.com/hahahannes/cordova-plugin-google-nearby) with support for the Google Nearby API. At the moment it only supports android and the Messages API not the Connections API.
Thanks!
Hannes

feat(plugin): Add google nearby plugin

---

src/@ionic-native/plugins/calendar/index.ts

The createCalendar should allow a string or `NameOrOptions`, not `CalendarOptions`

fix(calendar): Fixes createCalendar parameter typing

---

src/@ionic-native/plugins/ibeacon/index.ts

Changes wrongly typed `@param {BeaconRegion}` to `@param {Region}`
When using a Circular Region with `startMonitoringForRegion(myCircularRegion)`, TypeScript complains that the Type does not match.

fix(ibeacon): correct Type {Region} in some params

---

scripts/build/transformers/imports.ts

Imports in v5 are broken, for example in ```file``` plugin : 
```ts
import { IonicNativePlugin, checkAvailability, cordovaPropertyGet, cordovaPropertySet, injectable } from '@ionic-native/core';
```
which is wrong because ```injectable``` is not exported by ionic-native/core and also because the ```getPromise``` function import is removed from the original file which break some functionalities.
It should be : 
```ts
import { IonicNativePlugin, checkAvailability, cordovaPropertyGet, cordovaPropertySet, getPromise } from '@ionic-native/core';
```
I am not sure about what is the right way to fix it but the changes I have done here seems to do the job.

Fix v5 imports

---

src/@ionic-native/plugins/facebook/index.ts

As of February 5, 2018, Facebook doesn't support anymore App Invites, therefore I did remove these methods rom the `cordova-plugin-facebook4` and published these changes to npm under version v2.0.0

refactor(facebook): remove deprecated function appInvite

---

src/@ionic-native/plugins/call-directory/index.ts

I have spotted some typos and added an example for reload.

docs(calldirectory): fix typo

---

src/@ionic-native/plugins/firebase/index.ts

The `timeoutDuration` is not used in iOS, so default the value to 0

feat(firebase): verifyPhoneNumber now supports iOS

---

src/@ionic-native/plugins/android-full-screen/index.ts

Variable "error" doesn't exsit in the catch.
`this.androidFullScreen.isImmersiveModeSupported()
.then(() => console.log('Immersive mode supported'))
.catch(err => console.log(error));`
to
`this.androidFullScreen.isImmersiveModeSupported()
.then(() => console.log('Immersive mode supported'))
.catch(err => console.log(err));`

docs(android-full-screen): edit example

---

src/@ionic-native/plugins/web-intent/index.ts

…n provides no way to receive the registered broadcasts.
Usage is as follows:
webintent.registerBroadcastReceiver({
filterActions: [
'com.example.ACTION'
],
filterCategories: [
'android.intent.category.DEFAULT'
]
}).subscribe((intent) => {console.log('Received Intent: ' + JSON.stringify(intent.extras));});

fix(web-intent): registerBroadcastReceiver as Observable

---

src/@ionic-native/plugins/file/index.ts

`doesn't` was using a non escaped single quote. Therefore the example will not work and the highlighting in the demo page is broken.

docs(file): fix example

---

scripts/build/transformers/plugin-class.ts

This PR fixes a wrong behaviour in v5 which transform "declare" classes to real classes.
For example the ```file``` plugin declare a class like this : 
```ts
export declare class FileReader {
...
}
```
and currently in the final ```file``` plugin package, v5 turns it into this : 
```js
var FileReader = /** @class */ (function () {
function FileReader() {
}
return FileReader;
}());
export { FileReader };
``` 
which is wrong because FileReader should come from ```cordova-plugin-file```.

stop transforming "declare" classes in v5

---

src/@ionic-native/plugins/onesignal/index.ts

Made all properties in OSNotification optional because when you create a push notification the type is OSNotification but it does not have all the same properties required as the OSNotification as a response from a received notification. For example, you don't pass in isAppInFocus when you create a notification but it was causing issues when trying to post a notification because it was showing as required because OSNotification as a response will always have isAppInFocus.

fix(OSNotification) can't create notifications

---

src/@ionic-native/plugins/navigation-bar/index.ts

Hey!
A small misspelling detected here 🙂
This:
> The NavigationBar plugin **can** you to hide and auto hide the android navigation bar.
Should be:
> The NavigationBar plugin **allows** you to hide and auto hide the android navigation bar.

docs(navigation-bar): fix typo

---

src/@ionic-native/plugins/web-intent/index.ts

The `sendResult` method is missing in the Ionic Native definition. 
The definition in the Cordova plugin can be found here:
https://github.com/darryncampbell/darryncampbell-cordova-plugin-intent/blob/master/www/IntentShim.js#L77
The Java implementation is defined here:
https://github.com/darryncampbell/darryncampbell-cordova-plugin-intent/blob/master/src/android/IntentShim.java#L219

feat(send-result): add sendResult method for WebIntent plugin

---

src/@ionic-native/plugins/themeable-browser/index.ts

it wrong from boolean to string, after 1 year i update it. already test many time.
clear for issue: [ThemeableBrowser cannot hidden and clear cache](https://github.com/ionic-team/ionic-native/issues/2521)
closes: #2521

fix(themeable-browser): allow hidden and clear cache

---

src/@ionic-native/plugins/health/index.ts

Adding missing "filtered" attribute on HealthQueryOptionsAggregated object. 
It has been added to the cordova-plugin-health (https://github.com/dariosalvi78/cordova-plugin-health/blob/master/src/android/HealthPlugin.java => line 1248 is where it is used), but not yet in the ionic-native part. 
Also already existing for the regular HealthQueryOptions object in ionic-native

fix(healths): add missing attribute on HealthQueryOptionsAggregated

---

src/@ionic-native/plugins/ble/index.ts

This is a update for the latest cordova plugin version (1.2.1). [cordova-plugin-ble-central](https://github.com/don/cordova-plugin-ble-central)
Feel free to improve this file.

feat(ble): update wrapper to match latest plugin release

---

package.json
src/@ionic-native/plugins/background-geolocation/index.ts

Plugin has a method to watch location mode: `watchLocationMode`.
Currently it is declared as returning a Promise. That means the callback is only called ones.
Since this is a listener that is called multiple times from the native part of the plugin it has to be declared to return an observable that can be subscribed.

fix(background-geolocation): watchLocationMode returns observable

---

src/@ionic-native/plugins/photo-library/index.ts

I have submitted a pull request to the plugin author awaiting merge.  This will limit the number of items returned. ios only

feat(photo-library): maxItems to limit items-iOS

---

src/@ionic-native/plugins/onesignal/index.ts

Plugin: onesignal
Description: 
Adding 'state' property to 'OSPermissionState' interface because whenever I try to compile it fails with the following message: --- Property 'state' does not exist on type 'OSPermissionState' --- 
I check the documentation of the onesignal-cordova-plugin in here: https://documentation.onesignal.com/docs/cordova-sdk#section--getpermissionsubscriptionstate- and it saids that the OSPermissionState should have a 'status' property when platform is ios and a 'state' property when platform is android however the interface only specify the 'hasPrompted' and 'status' properties.

fix(onesignal): update OSPermissionState interface

---

src/@ionic-native/plugins/card-io/index.ts

Property 'scan' does not exist on type 'typeof CardIO'

docs(card-io): fix example

---

src/@ionic-native/plugins/image-picker/index.ts

As documented in the image picker plugin, it also supports a data url, just like the camera does. However, this option is not documented in Ionic Native currently. I've added this documentation, and have also added an enum with a naming pattern that matches the DestinationType in Camera.
Docs from the image picker plugin:
```
...
// output type, defaults to FILE_URIs.
// available options are 
// window.imagePicker.OutputType.FILE_URI (0) or 
// window.imagePicker.OutputType.BASE64_STRING (1)
outputType: int
};
```

feat(image-picker): add DATA_URL as an option to ImagePicker

---

src/@ionic-native/plugins/camera/index.ts

DATA_URL can be very memory intensive and cause app crashes or out of memory errors.
Use FILE_URI or NATIVE_URI if possible

docs(camera): Update docs to advise against DATA_URL

---

scripts/build/transformers/imports.ts

Imports in v5 are broken for file-transfer plugin, for example : 
```ts
import { IonicNativePlugin, instanceAvailability, cordovaInstance } from '@ionic-native/core';
```
which is wrong because the ```checkAvailability``` function import is removed from the original file which break FileTransferObject constructor.
It should be : 
```ts
import { IonicNativePlugin, instanceAvailability, cordovaInstance, checkAvailability } from '@ionic-native/core';
```

fix v5 imports for file-transfer plugin

---

src/@ionic-native/plugins/aes-256/index.ts

This Cordova ionic plugin allows you to perform AES 256 encryption and decryption on the plain text. It's a cross-platform plugin which supports both Android and iOS. The encryption and decryption are performed on the device native layer so that the performance is much faster.

feat(aes-256): AES256 encryption and decryption plugin added

---

src/@ionic-native/plugins/health/index.ts

query method is always returning an array
closes: #2499

fix(healt): add correct return type for query function

---

src/@ionic-native/plugins/deeplinks/index.ts

If it has only one argument, then no need function brackets. It would decrease the readability of the source code snippets.

docs(deeplinks): update example

---

src/@ionic-native/plugins/sqlite/index.ts

The transaction callback function argument is currently typed as `any`, however this isn't very  helpful so I have added a base interface which contains only the `executeSql` function. This function is all that is available on the object returned by WebSQL, but is also available on the full SQLite implementation.

docs(sqlite): Add interface for transaction callback function argument

---

src/@ionic-native/plugins/network-interface/index.ts

As currently implemented, this wrapper doesn't work for all underlying platform implementations (certainly not on Android, because the Promise resolves to an object, not a string).
I've changed the types to `any` here in the interest of simplicity. I've also updated the associated documentation in a PR against the plugin implementation repo (https://github.com/salbahra/cordova-plugin-networkinterface).
closes: #2472

feat(network-interface): match latest plugin release

---

src/@ionic-native/plugins/sqlite/index.ts

With the recent addition in 713efd720626c68df9a4c8a902eca85bb6dda1eb one of my apps broke since the optional arguments were not marked as optional. This resolves that.

fix(sqlite): mark optional arguments for executeSql

---

src/@ionic-native/plugins/fcm/index.ts

The current 'cordova-plugin-fcm' returns dependency troubles and has not been maintained in a while.

feat(ccm): replace plugin source

---

src/@ionic-native/plugins/nfc/index.ts

See the cordova project [plugin sources](https://github.com/chariotsolutions/phonegap-nfc)
The attributes `id` and for textRecord `languageCode` are optional. Default language code is english (en).

fix(nfs): Optional arguments for records like textRecord

---

src/@ionic-native/plugins/user-agent/index.ts

Fixes(user-agent): plugin is not installed (https://github.com/ionic-team/ionic/issues/13870)
```
[17:33:56]  console.warn: Native: tried calling UserAgent.set, but the UserAgent plugin is not installed. 
[17:33:56]  console.warn: Install the UserAgent plugin: 'ionic cordova plugin add cordova-plugin-useragent' 
[17:33:56]  console.error: plugin_not_installed
```
Closes: (https://github.com/LouisT/cordova-useragent/issues/6) (https://github.com/ionic-team/ionic-native/issues/1789)

fix(user-agent): Plugin not installed

---

src/@ionic-native/core/util.ts

- Explicitly spell out that this is coming from "Ionic Native", instead of just "Native"
- Improve sentence that explains 2 most common reasons for missing Cordova

refactor: Improve Ionic Native warnings

---

src/@ionic-native/plugins/network/index.ts

We noticed that in some cases network state listeners are stopped triggering, but `navigator.onLine` still reflects the state correctly. I used the following code to debug and found out an issue with `window` and `document` difference:
```js
window.addEventListener("online", ()=>console.warn('WINDOW ONLINE'), false); // won't be triggered
window.addEventListener("offline", ()=>console.warn('WINDOW OFFLINE'), false); // won't be triggered
document.addEventListener("online", ()=>console.warn('DOCUMENT ONLINE'), false); // triggered
document.addEventListener("offline", ()=>console.warn('DOCUMENT OFFLINE'), false); // triggered
```
Also, according to plugin documentation, listeners should be bound to `document`: https://github.com/apache/cordova-plugin-network-information#offline

Bind listener to document instead of window

---

src/@ionic-native/plugins/firebase-dynamic-links/index.ts

The example is a promise, but the current version uses Observables.

docs(firebase-dynamic-links): Change example

---

src/@ionic-native/core/decorators/instance-property.ts

The check in the `instancePropertySet` function is too aggressive.
This manifests in many plugins just not quite working right because the underlying js objects are not getting all the properties they should be getting.

objectInstance properties are not being set correctly. 

---

src/@ionic-native/core/decorators/common.ts

I almost sure (after some debugging) that it should fix a problem with the latest beta (5.0.0-beta.15) due to this change which have been merged : https://github.com/ionic-team/ionic-native/pull/2622 
My problem is that Network.onConnect() throws an error with the latest v5 (but worked with 5.0.0-beta.14). The error is "RangeError: Maximum call stack size exceeded" because rxjs try to subscribe to the "document" string instead of document object. 
I think it should be easy to reproduce.

fix wrapEventObservable

---

src/@ionic-native/plugins/contacts/index.ts

`checkAvailability()` is called in the contacts plugin without being imported and it is breaking docs builds

fix(contacts): fixing builds

---

src/@ionic-native/plugins/mixpanel/index.ts

- `alias` does not require an `originalId`.
- `identify` accepts a `usePeople` parameter for the iOS SDK.
- New methods:
`append`
`deleteUser`
`trackCharge`
`unset`
`union`

feat(mixpanel): Update/add functions

---

src/@ionic-native/plugins/ms-adal/index.ts

Update createAuthenticationContext to include validateAuthority flag since it is throwing Error: Fail to valid authority with errors: [50049].
Without the flag it is throwing Error: Fail to valid authority with errors: [50049].

fix(ms-adal): Update createAuthenticationContext

---

src/@ionic-native/plugins/appsflyer/index.ts

Appsflyer Attribution Cordova SDK as ionic native plugin

feat(appsflyer): Added Appsflyer Cordova SDK as ionic native plugin

---

src/@ionic-native/plugins/branch-io/index.ts

Fullfill feature request https://github.com/ionic-team/ionic-native/issues/2189
closes: #2189

feat(branch-io): Add branch.io attribution and invitation plugin

---

src/@ionic-native/plugins/onesignal/index.ts

Added this method: https://github.com/OneSignal/OneSignal-Cordova-SDK/blob/master/www/OneSignal.js#L233-L235

fix(onesignal): add missing setLocationShared method

---

src/@ionic-native/plugins/web-server/index.ts

Add support of the cordova-plugin-webserver plugin, to start a
a dynamic content web server on iOS and android devices.

feat(plugins): add web-server plugin

---

src/@ionic-native/plugins/secure-storage/index.ts

Fixes error when using secure-storage plugin.
When calling `.create()` it makes a call to `getPromise`. This was not imported, and so throws an error.

fix(secure-storage): add missing "getPromise" import

---

src/@ionic-native/plugins/siri-shortcuts/index.ts

Added options to the `getActivatedShortcut()` method in order to be able to enable/disable clearance of the active shortcut. Reflects change in the Cordova-plugin repository.

feat(siri-shortcuts): Add clear option for the activated shortcut

---

src/@ionic-native/plugins/bluetooth-le/index.ts

getAdapterInfo is a promise and had {observable: true} param

fix(bluetooth-le): Removed a wrong cordova decorator param

---

src/@ionic-native/plugins/keyboard/index.ts

Previously we were using the deprecated keyboard plugin.
Fixes #2306

fix(keyboard): use cordova-plugin-ionic-keyboard

---

src/@ionic-native/plugins/geolocation/index.ts

This is pretty nitpicky, but I think the existing documentation message is somewhat unprofessional. It's also very plausible that people will use this message in the docs as-is without thinking or realizing that it's intended to be changed (or reading it at all).
I propose a message that is hopefully generic enough to be used by any app if worse comes to worst while still communicating the same message.

docs(geolocation): use more generic / professional message

---

src/@ionic-native/plugins/network/index.ts

The network plugin offers a class with constants for the available connection types. This PR tries to recreate this with an enum.
Please let me know if there is a better way to do it.

refactor(network):  add enum for connection types

---

src/@ionic-native/plugins/last-cam/index.ts

feat(lastCam): add plugin

---

src/@ionic-native/plugins/onesignal/index.ts

The correct path is described at the official documentation from OneSignal. 
Link: https://documentation.onesignal.com/docs/customize-notification-icons

docs(one-signal): fix target url for notification icon

---

src/@ionic-native/plugins/firebase/index.ts

setting user identifier is available since [cordova-plugin-firebase@2.0.3](https://github.com/arnesson/cordova-plugin-firebase/blob/master/CHANGELOG.md#features)
added the functionality to the firebase ionic native plugin

feat(crashlytics): allow user to set userIdentifier for crashlytics

---

src/@ionic-native/plugins/contacts/index.ts

This adds the rawId parameter to the contact class which allows the rawId value to be passed to Android which is required for saving contacts.
This fixes issue #2760

fix(contacts plugin): add the rawId parameter

---

src/@ionic-native/plugins/sqlite/index.ts

executeSql takes array param not object according to the function declaration in code.

docs(sqlite): update usage example

---

src/@ionic-native/plugins/keyboard/index.ts

This will ensure consumers of this plugin don't need to go on a quest of finding what the possible values are, the values are derived from [here](https://github.com/ionic-team/cordova-plugin-ionic-keyboard#keyboardresizemode)

refactor(keyboard-setResizeMode): use explicit type

---

src/@ionic-native/plugins/card-io/index.ts

When the platform is Android, the cordova plugin wait for an Int value to set the guide color.

refactor(card-io): allow number as type for guideColor

---

src/@ionic-native/plugins/camera/index.ts

Add permissions for IOS, as it shows camera in device showing black and no error is thrown

docs(camera): improve docs

---

src/@ionic-native/plugins/local-notifications/index.ts

The `every` property of `ILocalNotificationTrigger` can be either a string or an object.
This PR updates the type to reflect this.

fix(local-notifications): update type of the every property

---

scripts/templates/wrap-min.tmpl
scripts/templates/wrap.tmpl

I tried creating a new plugin, and building it. Then an error message was displayed.
```
Failed to lint: /path/to/ionic-native/src/@ionic-native/plugins/example/index.ts [13, 10]: Named imports must be alphabetized..
```
I found ordered-imports in tslint-ionic-rules. So I changed order.
https://github.com/ionic-team/tslint-ionic-rules/commit/54d3cf883ace941ca1962d96cdeadcb20203aee4

chore(template): reorder imports

---

src/@ionic-native/plugins/health/index.ts
src/@ionic-native/plugins/nfc/index.ts

ionic-native/nfc makeReadyOnly function and isWriteable has probably not been used much as they are pointing to not existing function and attribute.
makeReadyOnly should be makeReadOnly and isWriteable should be isWritable to match phonegap-nfc package method and attribute.
This Pull request fix this two typos.
This fix issue #2823

fix(health): fix typos

---

src/@ionic-native/plugins/in-app-browser/index.ts

Please see the issue I created here for more information: https://github.com/ionic-team/ionic-native/issues/2861
This allows Ionic-Native to be used with the latest features of Cordova InAppBrowser's github.
closes: #2861

feat(in-app-browser): add 'beforeload' as option

---

src/@ionic-native/plugins/admob/index.ts

This AdMob plugin supports:
- Banner ads (top and bottom)
- Interstitial ads with autoshow feature
- Rewarded ads
- [Tappx](http://www.tappx.com/?h=dec334d63287772de859bdb4e977fce6) ads configurable as % of quota between AdMob/Tappx and/or backfill when AdMob has no ads

feat(admob): add plugin

---

src/@ionic-native/plugins/bluetooth-le/index.ts

Will this change eventually get to the v5 branch or would I need to do a separate PR to get it there?

fix(bluetooth-le): Fix typo in interface definition

---

src/@ionic-native/plugins/bluetooth-le/index.ts

It seems like my previous PR was overwritten on master.  Here it is again.  Fix #2890

fix(bluetooth-le): Fix typo in InitializeResult interface definition

---

scripts/build/transformers/imports.ts

Fixes #2801 by preventing duplicate import identifiers when building `dist` which causes prod Ionic app builds to fail.
Duplicate imports prior to this fix were caused by importing `checkAvailability` and using `@CordovaCheck` in the same ts file as shown in `ionic-native/src/@ionic-native/plugins/contacts/index.ts`. 
Currently, only `contacts` is affected but the fix should mitigate any future occurrence. Here's the diff between before and after the fix using Beyond Compare:
Let me know if you need any more info! 😀

fix(build): fixed duplicate import identifiers

---

src/@ionic-native/plugins/google-play-games-services/index.ts

closes ionic-team/ionic-docs#424

fix(google-play-games-services): correct Cordova plugin name typo

---

src/@ionic-native/plugins/abbyy-rtr/index.ts

cordova-plugin-abbyy-rtr-sdk has updated a new field of orientation as per the version 1.0.9

cordova-plugin-abbyy-rtr-sdk version 1.0.9 new option update

---

src/@ionic-native/plugins/http/index.ts

Adds missing sendRequest feature that has been implemented to cordova-plugin-advanced
which allows overriding global options for single request being sent via this method
Closes #2824

feat(http): sendRequest

---

src/@ionic-native/plugins/photo-viewer/index.ts

As of 1.1.19 of PhotoViewer, a new PhotoViewer option was added called 'headers' which allows for HTTP headers to be used when requesting the image.  This is useful for authenticated sites.

feat(photo-viewer): add new params

---

src/@ionic-native/plugins/magnetometer/index.ts

Added support for magnetometer (compass) raw x,y,z readings

feat(magnetometer): add new plugin

---

src/@ionic-native/plugins/zoom/index.ts

Hi,
This pull request includes a newly developed Cordova Plugin for using Zoom video conferencing services. For more information, please refer to https://github.com/zoom/zoom-sdk-ionic
Let me know if you have any questions. Thank you very much in advance.

feat(cordova.plugin.zoom):add new plugin

---

.gitignore
package-lock.json
package.json
scripts/docs-json/index.ts
scripts/docs-json/readme.md

This adds a script, `docs-json`, which generates a `plugins.json` file in the script directory. That JSON data can then be used in other projects where plugin data is needed, like the documentation.
```json
[
{
"packageName": "@ionic-native/abbyy-rtr",
"displayName": "ABBYY Real-Time Recognition",
"description": "\nThis plugin allows to use the Text Capt...",
"usage": "\n```typescript\nimport { AbbyyRTR } from '@ion...",
"platforms": [
"Android",
"iOS"
],
"repo": "https://github.com/abbyysdk/RTR-SDK.Cordova",
"cordovaPlugin": {
"name": "cordova-plugin-abbyy-rtr-sdk"
}
},
...
]
```

feat(scripts): add docs-json script

---

src/@ionic-native/core/decorators/common.ts

Replaced with conditional statement instead of assigning to element in multiple places

refactor(common): fix linter error

---

scripts/docs-json/index.ts

The `docs-json` script was, in one case, selecting the wrong class to document from a plugin module. This adds a check for TypeDoc comment tags to ensure we get the correct class.
```diff
- const isPlugin = (child: any): boolean => isClass(child) && Array.isArray(child.decorators) && child.decorators.some(d => d.name === 'Plugin');
+ const isPlugin = (child: any): boolean => isClass(child) && hasTags(child) && Array.isArray(child.decorators) && child.decorators.some(d => d.name === 'Plugin');
```

fix(build): check for TypeDoc tags when selecting plugin class

---

src/@ionic-native/plugins/bluetooth-le/index.ts

Initialize and enable definition functions are wrong.
This fix [2973](https://github.com/ionic-team/ionic-native/issues/2973)

Fix bad definitions in blueooth-le module in initialize and enable functions

---

src/@ionic-native/plugins/in-app-purchase-2/index.ts

Adding Cordova Property to account for the autoFinishTransactions property within cordova-plugin-purchase according to documentation at https://github.com/j3k0/cordova-plugin-purchase/blob/master/doc/api.md#random-tips

feat(in-app-purchase-2): add missing property

---

src/@ionic-native/plugins/in-app-purchase-2/index.ts

According to the documentation, alias is optional
https://github.com/j3k0/cordova-plugin-purchase/blob/master/doc/api.md#storeregisterproduct
Short Description of the issue:
It is currently not possible to register a product without an alias using the ionic-native npm package for  [cordova-plugin-purchase](https://github.com/j3k0/cordova-plugin-purchase).
Steps to reproduce:
Try registering a product without an alias throws the following error:
`error TS2345: Argument of type '{ id: any; type: string; }' is not assignable to parameter of type 'IAPProductOptions'.
[ng]   Property 'alias' is missing in type '{ id: any; type: string; }'.`

fix(in-app-purchase2): Registering a product with an alias is now optional

---

src/@ionic-native/plugins/spotify-auth/index.ts

I'm not the maintainer of the [cordova-spotify-oauth](https://github.com/Festify/cordova-spotify-oauth) plugin.
So we should probably wait for @NeoLegends review/approval on this before merging anything.

feat(spotify-auth): add Spotify OAuth plugin

---

src/@ionic-native/plugins/google-plus/index.ts

fixed if login's options is undefined, ios simulator will be throw the following error in runtime.
```
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSNull objectForKeyedSubscript:]: unrecognized selector sent to instance 0x11255cea8'
```

fix(google-plus): mark login param as required

---

src/@ionic-native/plugins/background-mode/index.ts

On the last PR https://github.com/ionic-team/ionic-native/pull/2982
there was a little typing problem for the .on event listener call.

fix(background-mode): update types definitions

---

src/@ionic-native/plugins/blinkid/index.ts

Not sure when the original code worked, but the blinkid-phonegap solution uses the updated names and fields for BlinkCard scans.  I have successfully tested the new code in my app with both US driver's license scanning and credit card scanning using the Blink API.

fix(blinkid): correct issue with blink card

---

src/@ionic-native/plugins/file-opener/index.ts

Added missing method 'showOpenWithDialog' from the underlaying plugin.
https://github.com/pwlin/cordova-plugin-file-opener2#fileopener2showopenwithdialogfilepath-mimetype-options
Needed if you want to open a file in other app without the need to preview it first.
- Tested it locally.
- Passed lint test.

feat(FileOpener): Added method showOpenWithDialog

---

src/@ionic-native/plugins/foreground-service/index.ts

Hello,
The following description is from @DavidBriglio who developed the cordova plugin for this PR:
> This plugin allows for android devices to continue running services in the background, using a foreground ongoing notification. This is targeted towards use with plugins such as 'cordova-geolocation' that will not run while the app is in the background on android API 26+.
Let me know if modifications are needed or please help yourself to it.

feat(foreground-service): add plugin

---

src/@ionic-native/plugins/music-controls/index.ts

The function this.musicControls.subscribe().subscribe was not closed properly, I added the proper syntax for closing the tag.

Fixed syntax for closing a tag

---

DEVELOPER.md

This removes a comment about methods being static that I believe is a (now misleading) remnant of v2 days before ionic-native wrappers were refactored to become injectable objects.

docs(developer): remove stale observation about methods being static

---

src/@ionic-native/plugins/full-screen-image/index.ts

Used for a Cordova plugin. The plugin converts base64 string to full-screen image or opens an image from a path.
The plugin is in the ionic origin project itself.

feat(full-screen-image): add plugin

---

src/@ionic-native/plugins/in-app-purchase-2/index.ts

Hey, I'm the maintainer of `cordova-plugin-purchase`, the cordova plugin used by `in-app-purchase-2`. I made some changes requested by users to the TypeScript definition, but I'm not ionic developer, I'm new to TypeScript, and don't know how to test the changes ;-)
Looks simple and it should probably work, but it'd be better to actually try it!
On a different note: how to update the page https://ionicframework.com/docs/native/in-app-purchase-2 ? The plugin now supports macOS and Microsoft UWP, plus it'd be nice to show more documentation, I can probably help with that.

feat(in-app-purchase-2): update TypeScript definitions

---

src/@ionic-native/plugins/diagnostic/index.ts

solves #3050
while diagnostic plugin docs may be confusing, the `requestRemoteNotificationsAuthorization(successCallback, errorCallback, types, omitRegistration)` signature is available in the sources:
https://github.com/dpa99c/cordova-diagnostic-plugin/blob/0fac4a59d1f246c872c05f513b09f0e9c93abb51/www/ios/diagnostic.notifications.js#L162

feat(diagnostic): add requestRemoteNotificationsAuthorization method

---

src/@ionic-native/plugins/music-controls/index.ts

Changed `updateElapsed()` argument's `elapsed` from string to number.
If string value is passed to it, MusicControl fully stops working.

fix(music-control): use correct input type

---

src/@ionic-native/plugins/sms-retriever/index.ts

Used for a Cordova plugin. The plugin retrieves the SMS for APP without asking for permission to reading.
The plugin is in the ionic source project itself.
Plugin name : cordova-plugin-sms-retriever-manager

feat(sms-retriever): add plugin

---

src/@ionic-native/plugins/in-app-purchase-2/index.ts

It should accept also a list of IAPProductOptions

fix(in-app-purchase-2): add missing option to register function

---

src/@ionic-native/plugins/firebase/index.ts

Added a missing call to cordova to use the clearAllNotifications from cordova-plugin-firebase

fix(firebase): add missing decorator to clearAllNotifications

---

scripts/docs-json/index.ts

In a few places where we use the output of the `docs-json` script, we need the `installVariables` from the plugin decorator. This adds it to the script output.

chore(scripts): add installVariables to docs-json output

---

scripts/tasks/publish.ts

This would allow Ionic v3 apps to use Ionic Native v5 wrappers.

refactor(core): allow rxjs 5.5 as peer dependency

---

src/@ionic-native/plugins/theme-detection/index.ts

Ionic Native Wrapper to detect the active theme (light or dark) on iOS devices.
URL: https://github.com/mariusbackes/cordova-plugin-theme-detection

feat(theme-detection): add plugin

---

src/@ionic-native/plugins/firebase-x/index.ts

Added plugin [cordova-plugin-firebasex](https://github.com/dpa99c/cordova-plugin-firebasex) which is the maintained fork from [cordova-plugin-firebase](https://github.com/arnesson/cordova-plugin-firebase) which is not maintained for a while now.

feat(cordova-plugin-firebasex): Add plugin

---

src/@ionic-native/plugins/http/index.ts

cordova-plugin-advanced-http `sendRequest` offers the possibility to change the `responseType` to text, ArrayBuffer or Blob. It is very useful to download a file with more options.
https://github.com/silkimen/cordova-plugin-advanced-http#sendrequest
Ionic Native interface does not accept this option, hence the Pull request.

feat(http): add sendRequest responseType option

---

src/@ionic-native/plugins/image-picker/index.ts

Original repo hasn't had a commit since 2016. 
`Repo:` parameter already updated, but intro docs wasn't.

docs(image-picker): set docs repo url to active repo

---

src/@ionic-native/plugins/ms-adal/index.ts

Removed a typo, which made the Access Token Type undefined all the time.

fix(ms-adal): use correct accessTokenType prop

---

src/@ionic-native/plugins/background-geolocation/index.ts

based on [this stackoverflow issue](https://stackoverflow.com/questions/57293829/argument-of-type-location-is-not-assignable-to-parameter-of-type-backgroundge/57302110#57302110) it seems passing the string causes problems in (some / all) scenarios

fix(background-geolocation): enum not string

---

src/@ionic-native/plugins/google-play-games-services/index.ts

Add submitScoreNow, unlockAchievementNow and incrementAchievementNow methods to the google-play-games-services plugin, as the function is already available on the cordova plugin: cordova-plugin-play-games-services.

feat(google-play-games-services): add new synchronous methods

---

src/@ionic-native/plugins/in-app-browser/index.ts

Closes #2744 as it includes the commit and fixes it's linting problems
Closes #2819 as it includes the new 3.1.0 options

fix(in-app-browser): update types to match cordova-plugin-inappbrowser 3.1.0 

---

src/@ionic-native/plugins/android-permissions/index.ts

The cordova plugin check/has always return a Promise with an object with this structure `{hasPermission: boolean}` but the ionic wrapper returned `Promise<any>`.
I have added an interface with the correct structure to the promise response.

Add response type to AndroidPermission plugin permission checking

---

src/@ionic-native/plugins/app-rate/index.ts

Add missing locale properties from the cordova plugin:
https://github.com/pushandplay/cordova-plugin-apprate/blob/master/typescript/AppRate.d.ts#L57

fix(app-rate) add missing locale properties

---

src/@ionic-native/core/decorators/common.ts

Return the window object as default instead of the boolean from the typeof comparison.
Otherwise the target event is invalid. Because it's a boolean, not an object. (like window).
Please see this issue for details. Fixes https://github.com/ionic-team/ionic-native/issues/2972 and all other related issues. This is a blocker bug. Please merge and release it as soon as possible. @danielsogl

fix(core): Return the window object as default instead of the boolean from the typeof comparison

---

src/@ionic-native/plugins/firebase-x/index.ts

Current version of plugin has change, described in https://github.com/dpa99c/cordova-plugin-firebasex#breaking-api-changes, this commit fixed `hasPermission()` method typings

Fix typings for hasPermission()

---

src/@ionic-native/plugins/document-scanner/index.ts

Add missing quality and returnBase64 properties from the cordova plugin:
[cordova-plugin-document-scanner](https://github.com/NeutrinosPlatform/cordova-plugin-document-scanner/blob/ade91c2f335d5be8ea42a84fadd8759cf5370db6/www/scan.js#L7)

feat(document-scanner): add quality and base64

---

src/@ionic-native/plugins/web-server/index.ts

Partially fixes #3126. It does not fix the wrong npm entry.
I have added optional body and path to the response type. Since path is supported by the cordova plugin.

fix(web-server): add path to response

---

src/@ionic-native/plugins/web-socket-server/index.ts

This PR adds cordova-plugin-websocket-server for Android and iOS. I have tested it on Android but not iOS, since I have no iPhone or Mac.
Also this plugin relies on this PR https://github.com/becvert/cordova-plugin-websocket-server/pull/64. If it does not get accepted I could also change the link to my fork.

feat(web-socket-server): Add cordova plugin websocket server

---

src/@ionic-native/plugins/camera/index.ts

It seems like these two definitions were switched around accidentally. I'm just going from the obvious logic of it. I don't know if there is some situation where the names are intentionally switched around? Please only accept PR if you can vouch for my change.

docs(camera): PictureSourceType switched?

---

src/@ionic-native/plugins/keyboard/index.ts

Somehow, the Keyboard plugin was updated/merged into master with a missing import statement.
Without it, running the `docs-json` script fails.

fix(keyboard): Add missing CordovaProperty import

---

src/@ionic-native/plugins/barcode-scanner/index.ts

Reverts ionic-team/ionic-native#3096
`shouldAutorotate` doesn't exist on the original plugin, [only on a pull request sent by the same user that is not merged yet](https://github.com/phonegap/phonegap-plugin-barcodescanner/pull/800), so this will cause issues for users using the original plugin.

Revert "fix(barcode-scanner): add missing shouldAutorotate property"

---

src/@ionic-native/plugins/secure-storage-echo/index.ts

In some projects I am working on, there are certain incompatibilities with Android Q/10 that It is fixed bt another Cordova plugin. I have created a new wrapper for that plugin can be used and we can start our Apps without problems. I don't know if this plugin is merged with the current one, so for security and necessity for the majority of developers who use this plugin, I think it is a good opportunity to contribute my grain of sand with this wrapper 😆.
Greetings!
EDIT: The current plugin is no longer mantained

feat(secure-storage-echo): added wrapper to newest plugin

---

src/@ionic-native/plugins/sign-in-with-apple/index.ts

I added the wrapper for the cordova plugin:
https://www.npmjs.com/package/cordova-plugin-sign-in-with-apple
With this we can use Apple's new sign in with Apple function with Ionic Native 🥳
https://developer.apple.com/sign-in-with-apple/

feat(Sign in with Apple): Added Sign in with Apple

---

src/@ionic-native/plugins/pspdfkit-cordova/index.ts

1. clone this repo and checkout this branch.
2. `cd` into `Ionic-Native` and run `npm run build`.
3. The newly built plugin can be found in `dist/@ionic-native/pspdfkit-cordova`.
1. Run `ionic start IonicDemo blank --type=angular --id=com.pspdfkit.ionic.example` to create a new Ionic project.
2. `cd` into `IonicDemo` and run `ionic cordova plugin add pspdfkit-cordova` to install the `pspdfkit-cordova` plugin.
3. Add a sample PDF into your `www` directory: `www/pdf/document.pdf`.
4. Open `config.xml` and change the deployment target to iOS 11 or later:
```diff
<platform name="ios">
<allow-intent href="itms:*" />
<allow-intent href="itms-apps:*" />
+ 	<allow-navigation href="*" />
+	<preference name="deployment-target" value="11.0" />
</platform>
```
5. Use your CocoaPods Key: `open …

feat(pspdfkit-cordova): add PSPDFKit-Cordova plugin

---

src/@ionic-native/plugins/fcm/index.ts

Add missing methods for `@ionic-native/fcm` (`cordova-plugin-fcm-with-dependecy-updated` plugin):
- `getAPNSToken`, released in October 2019
- `hasPermission`, released in September 2019
More info for the `cordova-plugin-fcm-with-dependecy-updated` plugin updates: https://www.npmjs.com/package/cordova-plugin-fcm-with-dependecy-updated#version-400-12102019.

feat(fcm): add getAPNSToken and hasPermission methods

---

src/@ionic-native/plugins/printer/index.ts

Migrated interface to v0.8.0
Tested locally ok

feat(printer): add v0.8.0 support

---

src/@ionic-native/plugins/firebase-x/index.ts

* (Android) *BREAKING CHANGE* Rework `verifyPhoneNumber()`
* Remove redundant `verified` in returned credentials object.
* Support mocking of instant verification for `verifyPhoneNumber()` on Android for integration testing.
* (iOS) *BREAKING CHANGE* Rework `verifyPhoneNumber()` 
* Return the same credential object structure as Android.
*  Add `signInWithCredential()` to sign user into Firebase account and `linkUserWithCredential()` to link user account with credentials obtained via `verifyPhoneNumber()`.
* (iOS) Add `getAPNSToken()` plugin API method to get the APNS token on iOS.
* (iOS) Add `onApnsTokenReceived()` to register a callback function to be invoked when the APNS token is allocated.

fix(firebase-x): update types to match cordova-plugin-firebasex 7.0.0

---

src/@ionic-native/plugins/sum-up/index.ts

The user can change to static affiliate key for SumUp authentication now on runtime. With this feature many customers can use one app

feat(sum-up): change affiliate key on runtime

---

src/@ionic-native/plugins/file/index.ts

Its important because `FileEntry` extends `Entry` and we can use the `file` method on it so that we can get the `File` for uploading it somewhere or using it somewhere.

fix(file): Changed resolveLocalFileSystemURL to FileEntryCallback

---

src/@ionic-native/plugins/http/index.ts

Hi guys, this an updated version matching cordova-plugin-advanced-http v2.3.0, which I've just released now.

feat(http): update declaration for cordova plugin version 2.3.0

---

src/@ionic-native/plugins/ms-adal/index.ts

The `acquireTokenAsync` method has one additional optional parameter called `claims`. Adding support for this parameter in the types.

fix(ms-adal): add missing "claims" parameter to "acquireTokenAsync" function

---

src/@ionic-native/plugins/pdf-generator/index.ts

I've added an wrapper for https://github.com/cesarvr/pdf-generator - we have been using this code for quite some time now, therefor it's tested.
The plugin creates a PDF file from a given HTML representation (URL or string) - all offline and on the device.

feat(pdf-generator): add new pluign

---

src/@ionic-native/plugins/mlkit-translate/index.ts

This is an ionic native wrapper for [Cordova MLKitTranslate Plugin](https://github.com/rigelglen/cordova-plugin-mlkit-translate) which implements MLKit's translation and language identification features.
To use the plugin:
`ionic cordova plugin add  https://github.com/rigelglen/cordova-plugin-mlkit-translate`

feat(cordova-plugin-mlkit-translate): Add plugin

---

src/@ionic-native/plugins/in-app-browser/index.ts

This solves the issue of the missing event that is supported by the InAppBrowser plugin: https://github.com/ionic-team/ionic-native/pull/3142#issuecomment-527171665  
This change also adds support for custom events by adding a method overload to support a generic `string`. By adding the overload the IDEs can still provide intellisense for the known events.  
Custom events are very well a thing: https://github.com/apache/cordova-plugin-inappbrowser/issues/514#issuecomment-517362862
The only downside (but `lib.dom.ts` has it, too) is that the `type` property of the `InAppBrowserEvent` needs to be changed to a `string`, too.

fix(in-app-browser): adds missing customscheme type

---

src/@ionic-native/plugins/firebase-x/index.ts

**This is only a change to documentation**
**Affected plugin:** cordova-plugin-firebasex
The path used to import FirebaseX in the usage example is wrong, it should end with /ngx

docs(firebase-x): add /ngx to import in usage example

---

src/@ionic-native/plugins/purchases/index.ts

Updated to latest version of the plugin. This includes:
- Copied types from the cordova-plugin-purchases plugin
- Cleaned up the readme to include only the basics and a link to the documentation. That's easier to maintain.
- Added getOfferings in replace of getEntitlements
- Changed a bunch of Observable wrappers to Promises
- Added purchaseProduct and purchasePackage
- Added syncPurchases, setAutomaticAppleSearchAdsAttributionCollection, isAnonymous , checkTrialOrIntroductoryPriceEligibility

fix(purchases): update to cordova-plugin-purchases@1.0.4

---

src/@ionic-native/plugins/background-geolocation/index.ts

https://github.com/mauron85/cordova-plugin-background-geolocation#API
The syncThreshold parameter type is Number

fix(background-geolocation): change syncThreshold type to number

---

src/@ionic-native/plugins/keychain-touch-id/index.ts

Added missing userAuthenticationRequired parameter to save method in definitions file for keychain-touch-id plugin. 
Resolving [this open issue](https://github.com/ionic-team/ionic-native/issues/2749)

feat(keychain-touch-id): added userAuthenticationRequired parameter to save method

---

src/@ionic-native/plugins/secure-storage/index.ts

The SecureStorage.create()  method return SecureStorageObject only when the storage is secure, but we need SecureStorageObject to call secureDevice method and redirect the user to the secure device options.
Here a simple fix that riflects the cordova-plugin-storage-echo strategy.
fixes: #2486

fix(secure-storage): method is inaccessible when device is not secure

---

src/@ionic-native/plugins/apple-pay/index.ts

Fixes the missing merchantCapabilities error in iOS versions 12 & 13.
`
2020-02-15 22:37:26.790765-0500 Tabify[83627:7611347] [General] Payment request is invalid: Error Domain=PKPassKitErrorDomain Code=1 "Invalid in-app payment request" UserInfo={NSLocalizedDescription=Invalid in-app payment request, NSUnderlyingError=0x6000007cc210 {Error Domain=PKPassKitErrorDomain Code=1 "PKPaymentRequest must have valid merchantCapabilities" UserInfo={NSLocalizedDescription=PKPaymentRequest must have valid merchantCapabilities}}}
`
Fix courtesy of https://enappd.com/blog/how-to-integrate-apple-pay-in-ionic-4-apps/21/

fix(apple-pay): fix PKPaymentRequest must have valid merchantCapabilities in iOS 12 & 13

---

src/@ionic-native/plugins/fcm/index.ts

fix(fcm): add missing clearAllNotifications, hasPermission and getAPNSToken

---

src/@ionic-native/plugins/iamport-cordova/index.ts

Hello This is Solee Choi working for a Korean IT Company which is called SIOT.
We offer payment API like Stripes and have been developing some modules for react-native, flutter, capacitor etc.
Now we are working on ionic cordova plugin and trying to add iamport-cordova plugin(https://github.com/iamport/iamport-cordova) on ionic-native to make developers use our plugin on ionic environment.
It would be pleasure for you to allow iamport-cordova plugin.
Thanks!

feat(iamport-cordova): add iamport-cordova plugin on ionic-native

---

src/@ionic-native/plugins/email-composer/index.ts

When there are no apps installed that can handle "mail", then the "apps" array is returned as `null` from the plugin. This minor change ensures we don't try to call `length` on `null` but maintains the behavior of the original implementation.
The error appears as:
> Unhandled Rejection (TypeError): null is not an object (evaluating 'apps.length').
I didn't see any corresponding unit tests to update. Please let me know if I missed something. This did correct the issue when I changed the file directly in the node_modules for my project.

fix(email-composer): fix error when no mail apps

---

src/@ionic-native/plugins/purchases/index.ts

Updated to latest version of the plugin. Changes:
* Adds Subscriber Attributes, which allow developers to store additional, structured information
for a user in RevenueCat. More info: https://docs.revenuecat.com/docs/user-attributes.
* Adds new method to invalidate the purchaser info cache, useful when promotional purchases are granted from outside the app.
https://github.com/RevenueCat/cordova-plugin-purchases/pull/32 
* Adds shouldPurchasePromoProduct, which allows the app to decide how and when to handle promotional purchases made by users directly through the App Store.
https://github.com/RevenueCat/cordova-plugin-purchases/pull/25
* Fixes some JSDocs and export types.
https://github.com/RevenueCat/cordova-plugin-purchases/pull/26

feat(purchases): update to cordova-plugin-purchases@1.1.0

---

src/@ionic-native/plugins/iamport-cordova/index.ts

card_quota property could be undefined, empty array, or numbers of array.
So I changed the data type of card_quota from [number] to number[].
It would be pleasure for ionic-team to merge this pull request.
Thanks for developing an awesome platform!

fix(iamport-cordova): fix data type of card_quota

---

src/@ionic-native/plugins/health/index.ts

As said in the comment: `if specified, aggregation is grouped an array of "buckets" (windows of time),` the `bucket` field in `HealthQueryOptionsAggregated` should be optional.

fix(health): HealthQueryOptionsAggregated bucket optional

---

src/@ionic-native/plugins/firebase-messaging/index.ts

Add the `getInstanceId` method, which was added to the cordova plugin in this [commit](https://github.com/chemerisuk/cordova-plugin-firebase-messaging/commit/31c32650a68efd770a4d694b3c41c8ee3db9c856).  Let me know if I need to change anything.  I've tested this locally on iOS successfully.

feat(firebase-messaging): add getInstanceId

---

src/@ionic-native/plugins/in-app-browser/index.ts

There were some missing definition for passing options. Fixed them.

fix(in-app-browser): add missing 'no' type

---

src/@ionic-native/plugins/firebase-authentication/index.ts

When using the function
`this.firebaseAuthentication.signInWithVerificationId(this.verificationID,123456)`
Error is
`by.chemerisuk.cordova.firebase.FirebaseAuthenticationPlugin.signInWithVerificationId argument 2 has type java.lang.String, got java.lang.Integer
`
**and that is because smsCode has to be string instead of number**
package.json
```
"@ionic-native/firebase-authentication": "^5.23.0",
"cordova-plugin-firebase-authentication": "^3.1.0",
```
Reference:
https://github.com/ionic-team/ionic-native/issues/2967
https://github.com/chemerisuk/cordova-plugin-firebase-authentication/issues/53

fix(firebase-authentication): signInWithVerificationId parameter mismatch

---

src/@ionic-native/plugins/stripe/index.ts

It took me quite a while to realize what is going on with **validateExpiryDate**.
1. The Cordova plugin this ionic native plugin wraps [does not take string, but number](https://github.com/zyra/cordova-plugin-stripe/blob/master/typings/CordovaStripe.d.ts#L51).
2. That this method's documentation does not exist, and can obviously not be looked up in [zyra/cordova-plugin-stripe](https://github.com/zyra/cordova-plugin-stripe), it would be rather nice the code would document it for me at least.
3. And then the big question comes up: What about [the example](https://ionicframework.com/docs/native/stripe#usage) for [StripeCardTokenParams](https://github.com/casaper/ionic-native/blob/master/src/@ionic-native/plugins/stripe/index.ts#L4)? It says `expMonth: 12` and takes number. Why go back to …

docs(validateExpiryDate): expMonth param month 0 to 11

---

src/@ionic-native/plugins/native-storage/index.ts

Required if you want to provide access to storage shared between apps in an app group in iOS.
Relevant section of the documentation for the plugin:
https://github.com/TheCocoaProject/cordova-plugin-nativestorage#usage

feat(native-storage): add initWithSuiteName

---

src/@ionic-native/plugins/vibes/index.ts

This adds an Ionic Native Wrapper for the cordova vibes plugin(https://github.com/vibes/vibes-cordova.git). The plugin enables integration with the Vibes platform.

feat(vibes-push-plugin): add Vibes Push plugin wrapper

---

src/@ionic-native/plugins/bluetooth-le/index.ts

change reconnect signature from Observable<{ status: DeviceInfo }> to  Observable<DeviceInfo> fixes #3374

fix(bluetooth-le): change reconnect signature

---

src/@ionic-native/plugins/appsflyer/index.ts

According to appsflyer docs, there should be *registerUninstall()* method to allow tracking uninstalls for iOS:
https://github.com/AppsFlyerSDK/appsflyer-cordova-plugin/blob/master/docs/API.md#-registeruninstalltoken-void

feat(appsflyer): added registerUninstall function

---

src/@ionic-native/plugins/pushape-push/index.ts

This adds an Ionic Native Wrapper for the `cordova pushape plugin` (https://github.com/gluelabs/pushape-cordova-push#readme).
The plugin enables integration with the Pushape service. (https://glue-labs.com/pushape-invio-notifiche-push-ios-android-api-sdk)
It's pretty equal to Push plugin implementation, but it exposes some more specific types related to the service and allows you to register/unregister to Pushape service via API through monkey-patch of `init` and `unregister` methods.

feat(pushape-push): add plugin

---

src/@ionic-native/plugins/secure-storage-echo/index.ts

This is a identical to a change already made to secure-storage.
Let me know if you have any questions or requests.

fix(secure-storage-echo): method is inaccessible when device is not secure #3322

---

src/@ionic-native/plugins/firebase-x/index.ts

Definition for the non-ionic methods are available as
https://github.com/dpa99c/cordova-plugin-firebasex/blob/master/types/index.d.ts#L120
`fakeVerificationCode` is an optional param
and `timeOutDuration` is required
`fakeVerificationCode` is necessary to test instantVerification behavior

fix(firebase-x): add fakeVerificationCode param to verifyPhoneNumber

---

src/@ionic-native/plugins/mixpanel/index.ts

The plugin method of MixpanelPeople.identify() fails on iOS as it is not supported anymore causing an uncaught exception. The plugin expects 2 arguments while the identify method only provides 1. 
See the the plugin repo for more info: [cordova-mixpanel-plugin](https://github.com/samzilverberg/cordova-mixpanel-plugin/blob/master/www/mixpanel.js )
changes:
1. Added @deprecated to MixpanelPeople.identify()

docs(mixpanel): add deprecated on identify

---

src/@ionic-native/plugins/ocr/index.ts

This plugin depends on the GoogleMobileVision pod which is referencing UIWebview, that has been deprecated by Apple.
- Add deprecation warning: Don't use this plugin in an app intended for App Store as you will get a review rejection from Apple: `Deprecated API Usage — Apple will stop accepting submissions of apps that use UIWebView APIs`
- For more info, please see the following Github issue [Google Mobile Vision relying on deprecated UIWebview](https://github.com/NeutrinosPlatform/cordova-plugin-mobile-ocr/issues/27).

docs(OCR): Add deprecation warning for OCR plugin

---

src/@ionic-native/plugins/fcm/index.ts

Hi, I'm the maintainer of cordova-plugin-fcm-with-dependecy-updated and there are two methods of which the types are not available in @ionic-native/fcm.
I'm not so sure if it's correct. But the definition for the non-ionic methods are available as https://github.com/andrehtissot/cordova-plugin-fcm-with-dependecy-updated/blob/master/src/FCMPlugin.d.ts

feat(fcm): add requestPushPermissionIOS and createNotificationChannelAndroid functions

---

src/@ionic-native/plugins/launch-review/index.ts

Use Cordova "Observable" instead of Promise since the rating() success callback needs to be called up to 3 times ("requested", "shown", "dismissed").

fix(launch-review): Allow rating() callback to be invoked multiple times

---

src/@ionic-native/plugins/firebase-x/index.ts

indicate callback methods to verifyPhoneNumber and signInWithCredential functions.
Definition for the non-ionic methods are available as
https://github.com/dpa99c/cordova-plugin-firebasex/blob/master/types/index.d.ts#L120

fix(firebase-x): indicate callback methods to verifyPhoneNumber

---

src/@ionic-native/plugins/build-info/index.ts

Plugin wrapper for [cordova-plugin-buildinfo](https://github.com/lynrin/cordova-plugin-buildinfo).

feat(build-info): add plugin

---

src/@ionic-native/plugins/vibes/index.ts

These changes add support for inbox messaging, which is being released with the latest version of the Vibes Cordova plugin.

feat(vibes): add support for inbox messaging

---

src/@ionic-native/plugins/ble/index.ts

To resume :
- Cordova doesn't guarantee callback ordering relative to when they are queued. See [this analyze](https://github.com/don/cordova-plugin-ble-central/issues/625) of @timburke. Thanks to him.
- cordova-plugin-ble-central has fixed this by adding a second parameter to the callback to leave the client checking and reordering the sequences order. This fix has been included in version 1.2.4. [Here](https://github.com/don/cordova-plugin-ble-central/pull/656) the PR
- The second parameter of plugin callback was not accessible from IONIC wrapper used to convert callback to observable
- I changed the option of wrapper by adding the destruct option. Now the value returned by subscription on the observable is an array with at index 0 the data value and at index 1 the sequence order. This …

fix(ble) #3506 : leave a chance to client to reorder sequences 

---

src/@ionic-native/plugins/ibeacon/index.ts

Change some cordova.plugins calls to window.cordova.plugins to
prevent 'Cannot read property 'locationManager' of undefined'

fix(ibeacon): undefined locationManager

---

src/@ionic-native/plugins/badge/index.ts

Badges plugin is not recommended for use in Android as of Android 8 (Oreo). We published these updates to the docs website

docs(android): badges fyi for android docs

---

src/@ionic-native/plugins/firebase-dynamic-links/index.ts

The interface `ICreatedDynamicLink` isn't the correct typing for the cordova-plugin (see https://github.com/chemerisuk/cordova-plugin-firebase-dynamiclinks)
I also currently need the following ugly conversion, because the real plugin returns a string instead of an interface.
```typescript
this.firebaseDynamicLinks
.createDynamicLink({
link: "https://XXX",
})
.then((link) => {
window.location.href = link as unknown as string ;
});
```

refactor(firebase-dynamic-links): removed interface that doesn't apply to the api

---

src/@ionic-native/plugins/clover-go/index.ts

Added support to pass signature incase the card payment require signature for authorisation
Added support to void any payment
Removed iOS platform for now as it will be supported in coming releases

feat(clover-go): add support to pass signature and void payment

---

src/@ionic-native/plugins/onesignal/index.ts

Fix issue #3478 
On the documentation the [OSInAppMessageAction](https://documentation.onesignal.com/docs/sdk-reference#osinappmessageaction-class) Class is listed as being `camelCase` but the result properties of the Cordova SDK method that I tested returns `snake_case` (likely inspired by a json conversion as also seem on the [Flutter SDK](https://github.com/OneSignal/OneSignal-Flutter-SDK/blob/15e0b89bd028adea83101f7d03de0d59644e10b9/lib/src/in_app_message.dart#L6)), so I opted to set the interface with the `snake_case` notation.
Example of a tested `OSInAppMessageAction` result object:
```
[ng] [console.log]: "in-app message clicked"
[ng] [console.log]: {
[ng]   "click_url": "",
[ng]   "first_click": true,
[ng]   "closes_message": true,
[ng]   "outcomes": []
[ng] }
```

feat(onesignal): add in-app messages methods

---

src/@ionic-native/plugins/geolocation/index.ts

The return type of `watchPosition` is wrong. `Geoposition` **and** `PositionError` will pass to the Observable. Therefore the return type has to be changed to reflect this behavior.  
#3303

fix(geolocation): #3303 geolocation watchPosition return type

---

src/@ionic-native/plugins/firebase-x/index.ts

Added the missing function reloadCurrentUser() for cordova-plugin-firebasex. This is identical to the already implemented function getCurrentUser(), but instead of loading the user from local memory, it reloads it from Firebase.
https://github.com/dpa99c/cordova-plugin-firebasex#reloadcurrentuser

feat(firebase-x): Add missing function reloadCurrentUser()

---

src/@ionic-native/plugins/in-app-purchase-2/index.ts

it was renamed from cc.fovea.cordova.purchase to cordova-plugin-purchase
https://github.com/j3k0/cordova-plugin-purchase/commit/14305f35c0d17aaed27119164ed3a5c7922b43ab
closes https://github.com/ionic-team/ionic-native/issues/3554

fix(in-app-purchase-2): change in-app-purchase-2 plugin id

---

src/@ionic-native/plugins/in-app-purchase-2/index.ts

IAPProduct.expiryDate and renewalDate is defined as string but must be defined as Date
lastRenewalDate?: Date;
expiryDate?: Date;
Other information:
https://github.com/j3k0/cordova-plugin-purchase/blob/master/doc/api.md#storeproduct-public-attributes
it's the fix for #3516

fix(in-App-purchase2) Correct type definition for date fields

---

src/@ionic-native/plugins/music-controls/index.ts

This path is necessary to use plugin in Capacitor see:
https://capacitorjs.com/docs/cordova/known-incompatible-plugins
The original project message in github.com:
No longer maintained.
Gavin Henry (ghenry22) has been maintaining a fork that should be updated and working better than this one. Please use his fork.
Is recomended update Ionic Documentation:
https://ionicframework.com/docs/native/music-controls

fix(music-controls): update associated cordova plugin

---

src/@ionic-native/plugins/diagnostic/index.ts

Just noticed, that the **locationAccuracyAuthorization** Property from my last PR (#3490) is missing in final build's `index.js`. The only difference to the other Properties was the comma/semicolon, so i changed this. Hope it's correct now?
Sorry for the issue in the last PR...

fix(diagnostics): locationAccuracyAuthorization Property missing in build

---

src/@ionic-native/plugins/http/index.ts

cordova http API has a 'raw' serializer, and in it is referenced several times in this file. It is even possible to set the serializer using `setDataSerializer('raw')`
This serializer is required for sending binary data.

fix(http): add missing type to serialiser property

---

src/@ionic-native/plugins/social-sharing/index.ts

Add missing method shareViaWhatsAppToPhone.
Method available in https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin#by-phone-number

feat(social-sharing): Add missing method shareViaWhatsAppToPhone

---

src/@ionic-native/plugins/firebase-dynamic-links/index.ts

Added Typescript definition for the recently added [`getDynamicLink()`](https://github.com/chemerisuk/cordova-plugin-firebase-dynamiclinks#getdynamiclink) method.

feat(firebase-dynamic-links): add missing method

---

src/@ionic-native/plugins/firebase-analytics/index.ts

Adding instructions for firebase analytics capacitor support on Android, because the plugin require cordova variables.

docs(cordova-plugin-firebase-analytics): Adding instructions for capacitor support on Android.

---

src/@ionic-native/plugins/appsflyer/index.ts

In AppsFlyer Cordova plugin 6.x.x the api was changed from 'track' to 'log'.
Ionic-Native AppsFlyer plugin support only until version 5.4.30

feat(AppsFlyer): update to 6.x.x

---

src/@ionic-native/plugins/smartlook/index.ts

Added new and adjusted some API methods so the ionic plugin is up-to-date with Smartlook SDK (currently version 1.6.0).

feat(smartlook): update to 1.6.0

---

DEVELOPER.md
scripts/build/transformers/methods.ts
src/@ionic-native/core/decorators/interfaces.ts

closes #3557
As i wrote in the linked Issue, this can be very useful.
- `methodName` add to Interface
- add to developer docs
- while creating messageBlock, prefer the given methodName if available

feat(core): add `methodName` to Cordova Decorator

---

src/@ionic-native/plugins/dfu-update/index.ts

I created this PR as Wrapper for my Plugin [DfuUpdate](https://github.com/EinfachHans/cordova-plugin-dfu-update) which uses Nordic Semiconductor's Device Firmware Update (DFU) service to update a Bluetooth LE device.

feat(dfu-update): add DfuUpdate Plugin Wrapper

---

src/@ionic-native/plugins/facebook/index.ts

With the merge of #3603 and my [PR](https://github.com/cordova-plugin-facebook-connect/cordova-plugin-facebook-connect/pull/8) to that new fork, the plugin now supports Facebooks GDPR Compliance.

feat(facebook): add setAutoLogAppEventsEnabled method

---

src/@ionic-native/plugins/purchases/index.ts

- remove deprecated `makePurchase`, replaced by `purchaseProduct`
- iOS: 
- add new method, `syncPurchases`, that enables syncing the purchases in the local receipt with the backend without risking a password prompt. The method was already available on Android.
- add a new method, `presentCodeRedemptionSheet`, for offer codes redemption.
- Bump `purchases-hybrid-common` to 1.5.0 [Changelog here](https://github.com/RevenueCat/purchases-hybrid-common/releases/1.5.0)
- Bump `purchases-ios` to 3.9.2 [Changelog here](https://github.com/RevenueCat/purchases-ios/releases/3.9.2)
- Bump `purchases-android` to 4.0.1 [Changelog here](https://github.com/RevenueCat/purchases-android/releases/4.0.1)

feat(purchases): bump cordova-plugin-purchases from 1.3.2 to 2.0.0

---

src/@ionic-native/plugins/firebase-authentication/index.ts

Adding missing signInWithApple method to the firebase-authentication plugin.
The cordova plugin has this method but the ionic native wrapper doesn't.
Ref. https://github.com/chemerisuk/cordova-plugin-firebase-authentication#signinwithappleidtoken-rawnonce

feat(firebase-authentication): add signInWithApple method

---

src/@ionic-native/plugins/launch-navigator/index.ts

Without the decorator the property is not working when calling `this.launchNavigator.appSelection.userChoice` for example.

fix(launchnavigator): make appSelection accessible

---

src/@ionic-native/plugins/in-app-purchase-2/index.ts

This new iOS App Store-feature was added in j3k0's cordova-plugin-purchase version 10.5.0, released 8 days ago.
More info on offer codes: [https://developer.apple.com/app-store/subscriptions/#offer-codes](https://developer.apple.com/app-store/subscriptions/#offer-codes)

feat(in-app-purchase-2): add redeem() for opening redeem code dialog [iOS]

---

src/@ionic-native/plugins/wonderpush/index.ts

We've upgraded our Cordova plugin to a major version and this method is no longer available.

feat(wonderpush): remove isReady method.

---

src/@ionic-native/plugins/preview-any-file/index.ts

add new methods to matching the last update of the cordova plugin "cordova-plugin-preview-any-file"

feat(preview-any-file): add new methods for preview-any-file cordova

---

src/@ionic-native/plugins/purchases/index.ts

- iOS: 
- Added a new method `setSimulatesAskToBuyInSandbox`, that allows developers to test deferred purchases easily.
- Bumped purchases-hybrid-common to 1.6.2 [Changelog here](https://github.com/RevenueCat/purchases-hybrid-common/releases/1.6.2)
- Bumped purchases-ios to 3.10.7 [Changelog here](https://github.com/RevenueCat/purchases-ios/releases/3.10.7)
- Bumped purchases-android to 4.0.5 [Changelog here](https://github.com/RevenueCat/purchases-hybrid-common/releases/4.0.5)
https://github.com/RevenueCat/cordova-plugin-purchases/pull/79

feat(purchases): bump cordova-plugin-purchases from 2.0.0 to 2.1.1

---

src/@ionic-native/plugins/in-app-purchase-2/index.ts

Fixes the typings for the return value of `refresh` as described [here](https://github.com/j3k0/cordova-plugin-purchase/blob/dd6bf6f/doc/api.md#return-value-3)

fix(in-app-purchase-2): fix typings for refresh

---

src/@ionic-native/plugins/network/index.ts

This enum was introduced in #2754 but it is declared with numbers, which may cause issues when doing something like:
```ts
this.network.type === Connection.NONE
```
Typescript will complain that `this.network.type` is a string and `Connection.NONE` is a number.

feat(network): declare connection enum with strings

---

src/@ionic-native/plugins/text-to-speech-advanced/index.ts

Adding support for `cordova-plugin-tts-advanced` with support for setting TTS voices

feat(plugin): Text to Speech Advanced

---

src/@ionic-native/plugins/in-app-purchase-2/index.ts

The `any` in the transaction is quite annoying that's why I looked into the docs of the corresponding corodva-plugin and found the typings for it: https://github.com/j3k0/cordova-plugin-purchase/blob/d5589af8c449ff87428b9ae8a59abacd839bdaaf/src/js/validator.js#L336
I can also confirm the correctness of the typings on my iOS and Android device.

feat(in-app-purchase-2): adds typings for transaction

---

src/@ionic-native/plugins/app-center-shared/index.ts

Adding support for `cordova-plugin-appcenter-shared`.
#2850

feat(plugin): add MS App Center shared plugin

---

src/@ionic-native/plugins/app-rate/index.ts

Hey hey!
We just noticed that some arguments on the `onButtonClicked` [callback](https://github.com/pushandplay/cordova-plugin-apprate/blob/master/www/AppRate.js#L103) are missing in the type definition. The types in the `cordova-plugin-apprate` are already updated (https://github.com/pushandplay/cordova-plugin-apprate/pull/301).
I tried to follow your naming / documentation pattern. Let me know if something should be changed!
Happy to get feedback! 😉

fix(app-rate): add missing types for onButtonClicked callback

---

src/@ionic-native/plugins/shortcuts-android/index.ts

Hi, I'm using the plugin [cordova-plugin-shortcuts-android](https://github.com/avargaskun/cordova-plugin-shortcuts-android) in a Ionic project, so I've added the wrapper for it. Please review it and let me know, thanks!

feat(shortcuts-android): add  cordova-plugin-shortcuts-android

---

src/@ionic-native/plugins/sqlite/index.ts

Current behavior:
Using sqlite plugin with cordova-sqlite-evcore-extbuild-free, it's not possible to use its androidDatabaseLocation feature which enables support for arbitrary database location on android.
The SQLiteDatabaseConfig interface currently don't have a slot for androidDatabaseLocation.
Expected behavior:
Here's the code for existing iosDatabaseLocation :
/**
* iOS Database Location. Example: 'Library'
*/
iosDatabaseLocation?: string;
Here's the code to add to the interface to support androidDatabaseLocation:
/**
* support arbitrary database location on android with https://github.com/litehelpers/cordova-sqlite-evcore-extbuild-free
*/
androidDatabaseLocation?: string;
Steps to reproduce:
When creating a connection using the SQLite.create method, the androidDatabaseLocation is …

feat(sqlite):add androidDatabaseLocation Support

---

src/@ionic-native/plugins/network/index.ts

After PR #3608 the Network onChange Method throws `mapTo is not defined`.
I imported it correctly and fixed the typing.
closes #3649

fix(network): onChange no longer causes error

---

src/@ionic-native/plugins/smartlook/index.ts

There was wrongly used `string` type where the underlaying cordova code expects `boolean`.

fix(smartlook): fix SmartlookResetSession.resetUser type to boolean

---

src/@ionic-native/plugins/paytabs/index.ts

added a wrapper for paytabs cordova plugin.

feat(paytabs): add plugin

---

src/@ionic-native/plugins/android-full-screen/index.ts

`isImmersiveModeSupported` returns a boolean in the [android code](https://github.com/mesmotronic/cordova-plugin-fullscreen/blob/master/src/android/com/mesmotronic/plugins/FullScreenPlugin.java#L129), so it also should here.

fix(android-full-screen): add correct return type

---

src/@ionic-native/plugins/firebase-authentication/index.ts

This definition is missing, given plugin documentation : 
https://github.com/chemerisuk/cordova-plugin-firebase-authentication#getcurrentuser

feat(firebase-authentication) add getCurrentUser() definition

---

src/@ionic-native/plugins/hyper-track/index.ts

- Added  and updated interfaces
- Added documentation to explain usage

feat(hyper-track): add interfaces to access new cordova plugin APIs

---

src/@ionic-native/plugins/barcode-scanner/index.ts

Adds the missing Android-only `saveHistory` option.
https://github.com/phonegap/phonegap-plugin-barcodescanner#using-the-plugin
https://github.com/phonegap/phonegap-plugin-barcodescanner/blob/v8.1.0/src/android/com/phonegap/plugins/barcodescanner/BarcodeScanner.java#L52

fix(barcode-scanner): add `saveHistory` option

---

src/@ionic-native/plugins/purchases/index.ts

Purchases plugin is not working in my ionic project with static method logIn, logOut
that methods will return undefined so I removed static of logIn, logOut methods.
This code must be reviewed by revenuecat developers before marge.

fix(purchases): remove static for logIn, logOut methods

---

src/@ionic-native/plugins/app-rate/index.ts

Updated to match 1.7.0 of the plugin which contained these changes:
https://github.com/pushandplay/cordova-plugin-apprate/pull/286

feat(app-rate): update sample code to use setPreferences and remove preferences property

---

src/@awesome-cordova-plugins/plugins/imap/index.ts

Add support for iOS.
Extend the function ‘listMailFolders’ to list mail folders names by regular expression pattern.
Create a function named ‘getFullMessageDataOnNewSession’ that will allow the user to connect and download the full message data from a new IMAP server connection

feat(imap): add iOS support

---

src/@awesome-cordova-plugins/plugins/purchases/index.ts

Adds `setAirshipChannelID` method, bumps dependency version number to `cordova-plugin-purchases` 2.4.0

feat(purchases): add `setAirshipChannelID` method

---

src/@awesome-cordova-plugins/plugins/camera-preview/index.ts

As indicated in the doc here: https://github.com/cordova-plugin-camera-preview/cordova-plugin-camera-preview
the prop `storeToFile` was missing in type definition

feat(camera-preview): add storeToFile param

---

src/@awesome-cordova-plugins/plugins/star-prnt/index.ts

Based on reading [the underlying source](https://github.com/auctifera-josed/starprnt/blob/master/src/ios/StarPRNT.m)

docs(star-prnt): correct capitalization of example code

---

src/@awesome-cordova-plugins/plugins/email-composer/index.ts

"this.emailComposer.hasClient()" and "this.emailComposer.isAvailable()" method usage is wrong on the official documentation. Please check.
.hasClient and .isAvailable both requires an app name string as the parameter, and they return promises. 
The original code of putting the parameter "app" into the "then()" chainable is not correct, as the "then()" only accepts callback functions as parameters.
Tested and proved in visual studio code.

docs(email-composer): update example

---

src/@awesome-cordova-plugins/plugins/http/index.ts

Hi :)
First of all, thx for your awesome plugins 😄 
The `HTTP` plugin lacks `setClientAuthMode` method which exists in the original plugin: https://github.com/silkimen/cordova-plugin-advanced-http#setclientauthmode

feat(http): add set client auth mode method

---

src/@awesome-cordova-plugins/plugins/keychain/index.ts

`useTouchID` is not an optional parameter. When it is not explicitly set, the whole app crashes with this error:
> Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSNull boolValue]: unrecognized selector sent to instance 0x111f02f08'
This bug is [known](https://github.com/ionic-team/cordova-plugin-ios-keychain/issues/34) since November 2018 and likely won't be fixed.

fix(keychain): mark useTouchID as required

---

src/@awesome-cordova-plugins/plugins/keychain/index.ts

It currently leads to a 404 page (https://ionicframework.com/docs/native/secure-storage/): a working anchor would lead to https://ionic.io/docs/secure-storage

doc: fix Secure Storage broken link

---

src/@awesome-cordova-plugins/plugins/diagnostic/index.ts

This updates the types to the latest [implementation](https://github.com/dpa99c/cordova-diagnostic-plugin/blob/019fe5860a17854e5fc4cc8db3510423478de412/www/android/diagnostic.location.js#L219-L241).
https://github.com/dpa99c/cordova-diagnostic-plugin#requestlocationauthorization
Resolves #4349

feat(diagnostic): extend parameter for requestLocationAuthorization

---

src/@awesome-cordova-plugins/plugins/adjust/index.ts

- Updated `index.ts` to expose current state of Adjust Cordova SDK v4.32.0 to TS users.

feat(adjust): update wrapper for Adjust Cordova SDK v4.32.0

---

src/@ionic-native/plugins/themeable-browser/index.ts

the type of fullscreen property actually is boolean, if the prop set to string 'true', it will cause parseFeature() method throw exception and create an new default Options class
https://github.com/initialxy/cordova-plugin-themeablebrowser/blob/master/src/android/ThemeableBrowser.java#L1406

fix(themeable-browser):update option type

---

docs/plugins/applovin/README.md
src/@awesome-cordova-plugins/plugins/applovin/index.ts

I haven't been able to test if it works locally. It keeps prompting below messages (even though I have installed the cordova plugin itself)
```
Msg: Native: tried calling Applovin.initialize, but the Applovin plugin is not installed.
Msg: Install the Applovin plugin: 'ionic cordova plugin add cordova-plugin-applovin-max'
```

feat(applovin): add plugin

---

package-lock.json
package.json
scripts/build/ngx.ts
scripts/tasks/build-ngx.ts

This should switch the ngx packages to use angular ivy output.
(Related to #3976, #4198, #4215)
This change will probably break usage of the plugins in apps using older angular version (<=9 i think) and apps disabling ivy.
It did some testing with small angular test apps using v12 & v14 - which worked as expected (apps still working & ngcc is no longer required).

Use ivy for ngx packages

---

src/@awesome-cordova-plugins/plugins/purchases/index.ts

Migrates the `purchases` plugin to the newest RevenueCat version `3.1.0`.
I also added some methods that are defined by the RevenueCat plugin and don't exist here before. You can see the typings of the supported methods here: https://github.com/RevenueCat/cordova-plugin-purchases/blob/main/www/plugin.d.ts
The Breaking Changes can be found here: https://github.com/RevenueCat/cordova-plugin-purchases/releases/tag/3.0.0

feat(purchases)!: migrate RevenueCat to 3.1.0

---

src/@awesome-cordova-plugins/plugins/bluetooth-le/index.ts

The bluetooth-le package has some incorrect return types. This PR corrects them.

fix(bluetooth-le): use correct return types

---

src/@awesome-cordova-plugins/plugins/ble/index.ts

Hello! noticed this function was missing, I added it in my own fork and its working as expected, figured I would open a PR to the upstream.

feat(ble): addwrapper for starting location notifications

---

src/@awesome-cordova-plugins/plugins/image-resizer/index.ts

This PR partially resolves this issue https://github.com/danielsogl/awesome-cordova-plugins/issues/4203

feat(image-resizer): add plugin

---

src/@awesome-cordova-plugins/plugins/purchases/index.ts

Followup on https://github.com/danielsogl/awesome-cordova-plugins/pull/4382 removing some functions that have been removed in cordova-plugin-purchases 3.0.0 and updating dependency to 3.2.0

feat(purchases)!: migrate RevenueCat to 3.2.1

---

docs/plugins/power-management.md
docs/plugins/power-management/power-management.md
src/@awesome-cordova-plugins/plugins/power-management/index.ts

Hi.
I just rescue this "old" wrapper (@ionic-native) witch I'm still using with cordova and capacitor.
I don't know why this wrapper was dropped out... I found the old PR (https://github.com/danielsogl/awesome-cordova-plugins/pull/489)
I tested this new and updated code, compiled and installed locally
and all work like as expected

feat(power-management): add power management support

---

src/@awesome-cordova-plugins/plugins/diagnostic/index.ts

feat(diagnostics): add getBluetoothAuthorizationStatuses function

---

src/@awesome-cordova-plugins/plugins/http/index.ts

PR to plugin repo
https://github.com/silkimen/cordova-plugin-advanced-http/pull/505

feat(http): onProgress param to  sendRequest  method

---

src/@awesome-cordova-plugins/plugins/mobile-messaging/index.ts

Fix methods for registering and unregistering events and improve comments. Also make return type for saveUser more descriptive.

fix(mobile-messaging): fix event (un)register and saveUser

---

src/@awesome-cordova-plugins/plugins/urbanairship/index.ts

The Airship SDK now supports overriding the default locale, this was added in https://github.com/urbanairship/urbanairship-cordova/pull/399
I would like to add these methods here as well.

feat(urbanairship): add plugin

---

src/@awesome-cordova-plugins/plugins/firebase-x/index.ts
src/@awesome-cordova-plugins/plugins/firebase/index.ts

Function `setConfigSettings` was using incorrect input arguments `settings: any` wheres [firebase-x cordova plugin doc](https://github.com/dpa99c/cordova-plugin-firebasex?tab=readme-ov-file#setconfigsettings) specifies correct arguments: 
**Parameters**:
- {integer} fetchTimeout - fetch timeout in seconds.
- Default is 60 seconds.
- Specify as `null` value to omit setting this value.
- {integer} minimumFetchInterval - minimum fetch inteval in seconds.
- Default is 12 hours.
- Specify as `null` value to omit setting this value.
- Set to `0` to disable minimum interval entirely (**DO NOT** do this in production)
- {function} success - callback function to be call on successfully setting the remote config settings
- {function} error - callback function which will be passed a {string} error …

fix(firebase-x): setConfigSettings function input parameters aligned with firebase-x plugin

---

src/@awesome-cordova-plugins/plugins/cashfree-pg/index.ts

These are the iconic wrapping for the `cordova-plugin-cashfree-pg`. In this ,we are proving support for UPI Payment
This is our [Cordova SDK](https://www.npmjs.com/package/cordova-plugin-cashfree-pg)

feat(cashfree-pg): support cordova-plugin-cashfree-pg 1.0.6

---

scripts/tasks/publish.ts

Related to this issue: https://github.com/danielsogl/awesome-cordova-plugins/issues/4714
Since the file bundle.js does not exist in the root directory we need to make index.js the main entry point.

fix(package): wrong top package main field

---

docs/plugins/ssl-certificate-checker/README.md
docs/plugins/ssl-certificate-checker/ssl-certificate-checker.md
src/@awesome-cordova-plugins/plugins/ssl-certificate-checker/index.ts

Hi, here is the wrapper for [SSLCertificateChecker](https://github.com/EddyVerbruggen/SSLCertificateChecker-PhoneGap-Plugin).
I have tested and installed it locally, and everything works as expected.

feat(ssl-certificate-checker): add SSL Certificate Checker support

---

src/@awesome-cordova-plugins/plugins/adjust/index.ts

- Updated `index.ts` to expose current state of Adjust Cordova SDK v4.37.1 and v4.38.0 to TypeScript users.

feat(adjust): update wrapper for Adjust Cordova SDK v4.37.1

---

src/@awesome-cordova-plugins/plugins/approov-advanced-http/index.ts

feat(approov-advanced-http): support approov3 methods

feat(approov-advanced-http): support approov3 methods

---

src/@awesome-cordova-plugins/plugins/in-app-purchase-3/index.ts

Close https://github.com/danielsogl/awesome-cordova-plugins/issues/4848
I'm not sure if this should be an update of the plugin in-app-purchase-2, but since the wrapped cordova-plugin-purchase got some huge backward compatibility breaks in the version 13.x I thought it was better.
(Note : only lightly tested, I'm new to both capacitor and cordova-plugin-purchase. I'll test it more thoughtfully in the next days, I'm working on a angular + capacitor in app purchase integration.)

feat(in-app-purchase-3) new InAppPurchase3 plugin

---

src/@awesome-cordova-plugins/plugins/downloader/index.ts

This Merge Request is compatible with both:  
- **`integrator-cordova-plugin-downloader`**,  
- and the new **`@e-is/cordova-plugin-downloader`**, which:  
* is a well-maintained fork of `integrator-cordova-plugin-downloader` (which seems to no longer be maintained),  
* fixes [this issue](https://github.com/Luka313/integrator-cordova-plugin-downloader/issues/20) related to Android SDK 33.

feat(downloader): add plugin

---

src/@awesome-cordova-plugins/plugins/ble/index.ts

Please add the capability to change the BLE connection priority while running on Android platform: requestConnectionPriority() to the `ble` plugin.

Add requestConnectionPriority() to the ble plugin.

---

src/@awesome-cordova-plugins/plugins/facebook/index.ts
src/@awesome-cordova-plugins/plugins/fbsdk/index.ts

Fixes the following for both old and new facebook plugin typings:
- Updates the return type for loginWithLimitedTracking to actually match the object returned
- Adds the `nonce` parameter which is required in the plugin.

fix(facebook/fbsdk): fix typings for loginWithLimitedTracking

---

src/@awesome-cordova-plugins/plugins/fingerprint-aio/index.ts

Added two optional parameters to FingerprintAIO.isAvailable() to reflect the optional parameters of isAvailable() in cordova-plugin-fingerprint-aio https://github.com/NiklasMerz/cordova-plugin-fingerprint-aio?tab=readme-ov-file#optional-parameters
* requireStrongBiometrics
* allowBackup
Should correct issue #4881

fix(fingerprint-aio) : Added optional parameters to isAvailable()

---

src/@awesome-cordova-plugins/plugins/imap/index.ts

Please consider accepting my pull request. I have added functionality to support downloading email attachments in the Cordova plugin for Android and iOS. Additionally, I’ve updated the wrapper to ensure compatibility, allowing users to easily integrate the plugin into their Ionic projects.
Thanks,
Aleksandar

feat: implement email attachments support in IMAP plugin wrapper

---

src/@awesome-cordova-plugins/plugins/screenshot/index.ts

No matching export in "node_modules/@awesome-cordova-plugins/core/index.js" for import "Plugin"

fix(screenshot): Update import

---

src/@awesome-cordova-plugins/plugins/cashfree-pg/index.ts

These are the iconic wrapping for the cordova-plugin-cashfree-pg. In this ,we are proving support for Subscription Payment
This is our [Cordova SDK](https://www.npmjs.com/package/cordova-plugin-cashfree-pg)

feat(cashfree-pg): support cordova-plugin-cashfree-pg 1.0.11
