danielsogl/awesome-cordova-plugins

- .gitignore
- src/index.ts
- src/plugins/datepicker.ts
Should I go as deep as documenting each sub-parameter for the parameter `options` ?
> Add datepicker

- src/plugins/flashlight.ts
> feat(plugin): add flashlight plugin

- src/plugins/datepicker.ts
Tested on Android .. works fine now.
> Edit datepicker

- src/plugins/batterystatus.ts
Not complete yet, thought I would show you where I'm going with this first. Note that I'm new to observables so I do apologize if there are any mistakes.
I thought for this plugin using the Cordova wrapper would not make sense since the original plugin does not have any functions to be called. 
*Edit*: I probably have to call isInstalled function, but I'm not sure what the pluginRef is for this plugin ...
> add batterystatus

- src/plugins/base64togallery.ts
- src/plugins/dbmeter.ts
- src/plugins/hotspot.ts
- src/plugins/keyboard.ts
- src/plugins/splashscreen.ts
- splashscreen
- hotspot
- dbmeter
- base64togallery
- keyboard
> Add plugins

- circle.yml
this should help for now to ensure that we are able to build
> test(tests): add build_bundle to tests

- src/plugins/spinnerdialog.ts
https://github.com/driftyco/ionic-native/issues/69
> feat(plugin): add spinner dialog plugin

- src/index.ts
- src/plugins/inappbrowser.ts
> feat(plugin): add InAppBrowser plugin

- src/index.ts
- src/plugins/diagnostic.ts
I did not add every method and have not tested on IOS only android.
> Added diagnostic plugin.

- scripts/docs/templates/common.template.html
- src/plugins/facebook.ts
closes https://github.com/driftyco/ionic-native/issues/93
> chore(docs): ability to add custom install command for a plugin

- src/index.ts
- src/plugins/webintent.ts
closes https://github.com/driftyco/ionic-native/issues/104
> feat(plugin): add web intent plugin

- src/index.ts
- src/plugins/emailcomposer.ts
First pass at email composer plugin. Should address #12
> feat(plugin): add email composer plugin

- src/plugins/statusbar.ts
> update docs statusbar.ts

- src/plugins/devicemotion.ts
documentation was wrong. watchPosition instead of watchAcceleration..
> documentation wrong for watchAcceleration

- src/plugins/camera.ts
> feat(camera): add camera constants

- src/index.ts
- src/plugins/screenshot.ts
Adding the Screenshot Plugin to close the issue https://github.com/driftyco/ionic-native/issues/137
Adding the cordova plugin https://github.com/gitawego/cordova-screenshot
This is my first attempt. I request you to please test it.
> Screenshot Plugin

- src/index.ts
- src/plugins/admob.ts
> feat(plugin): add admob pro plugin

- src/plugins/plugin.ts
this wrapper will be able to handle get/set functions for any instance property
> feat(plugin): add wrapper for instance properties

- src/plugins/facebook.ts
> Update install command

- src/index.ts
- src/plugins/filetransfer.ts
- src/plugins/plugin.ts
Added wrappers for the file transfer plugin.
> Implemented wrappers for FileTransfer.

- circle.yml
- src/index.ts
- src/plugins/googlemaps.ts
DISCLAIMERS:
- Work in progress
- Do not merge
- Use at your own risk
Closes #13
> Googlemaps

- src/plugins/googlemaps.ts
> Some fixes on GoogleMaps plugin

- src/plugins/admob.ts
- src/plugins/background-geolocation.ts
- src/plugins/batterystatus.ts
- src/plugins/ble.ts
- src/plugins/bluetoothserial.ts
- src/plugins/dbmeter.ts
- src/plugins/devicemotion.ts
- src/plugins/deviceorientation.ts
- src/plugins/geolocation.ts
- src/plugins/googlemaps.ts
- src/plugins/keyboard.ts
- src/plugins/network.ts
- src/plugins/plugin.ts
- src/plugins/toast.ts
> change rxjs/Rxjs to rxjs/Observable

- src/plugins/brightness.ts
Hi,
as requested: Improved docs for display brightness plugin. #214
> Improved brightness plugin documentation

- src/plugins/file.ts
Rebase of [#116](https://github.com/driftyco/ionic-native/pull/116) onto dev branch.
> alternate file implementation redux

- src/plugins/socialsharing.ts
Reverts driftyco/ionic-native#218
> Revert "SocialSharing: Add recommended `shareWithOptions` method"

- src/plugins/barcodescanner.ts
> fix barcode scanner callback order

- src/index.ts
- src/plugins/printer.ts
Added wrapper for the cordova-plugin-printer.
Here is the git repo: https://github.com/katzer/cordova-plugin-printer.git
> feat(printer): add printer plugin

- src/plugins/googlemaps.ts
- Add missing class GoogleMapsLatLngBounds
- Reformat to match code style guidelines
> Add GoogleMapsLatLngBounds (needs testing)

- src/plugins/actionsheet.ts
> fix(actionsheet): add missing optional parameter for hide function

- src/index.ts
- src/plugins/pin-dialog.ts
> feat(pin-dialog): add pin dialog plugin

- src/plugins/ibeacon.ts
- Order of major/minor parameters for `BeaconRegion` creator fixed
- Property `PluginResult.error` added
- Comment for `BeaconRegion.minor` fixed
> Minor fixes in IBeacon plugin

- src/plugins/googlemaps.ts
> feat(googlemaps): add Geocoder class

- src/index.ts
- src/plugins/sim.ts
> Add sim plugin

- src/plugins/sqlite.ts
> refactor(sqlite): fix method attribute typo

- src/plugins/camera.ts
> refactor(camera): Change static fields from default (private) to public

- src/plugins/plugin.ts
> feat(otherPromise): can work better with plugins that return promises

- src/index.ts
- src/plugins/crop.ts
This plugin doesn't seem very stable, but we can add it if it's something people want.
Will leave this PR here and if we get lots of +1s we'll merge.
Repo is here: https://github.com/jeduan/cordova-plugin-crop
> feat(crop): add crop plugin

- src/index.ts
- src/plugins/imageresizer.ts
Plugin repository: [https://github.com/protonet/cordova-plugin-image-resizer](https://github.com/protonet/cordova-plugin-image-resizer)
> feat(image-resizer): Add ImageResizer plugin

- src/plugins/diagnostic.ts
* Adds plugin description and example import statement
> docs(diagnostic): Adds basic documentation for importing plugin

- src/plugins/localnotifications.ts
> Missing Comma / Syntax Error

- src/plugins/googlemaps.ts
I would do more, but I'll see what kind of feedback I get first from these changes.
> docs(google maps) - Updates to Google Maps docs

- src/plugins/securestorage.ts
> There's a semicolon which shouldn't be there :)

- src/plugins/keyboard.ts
> feat(keyboard): enable hideKeyboardAccessoryBar function

- src/plugins/googleanalytics.ts
https://github.com/danwilson/google-analytics-plugin/blob/master/android/UniversalAnalyticsPlugin.java#L52
https://github.com/danwilson/google-analytics-plugin/blob/master/android/UniversalAnalyticsPlugin.java#L193-L195
https://github.com/danwilson/google-analytics-plugin/blob/master/ios/UniversalAnalyticsPlugin.m#L279-L283
> feat(GoogleAnalytics): Add campaign measurement tracking

- src/plugins/googlemaps.ts
Based on https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Map.getMyLocation()
> feat(GoogleMaps): Allow specify enableHighAccuracy option that attempt to get your location with highest accuracy

- src/plugins/camera.ts
> fix(camera): camera options should be optional. 

- src/plugins/datepicker.ts
> fix(datepicker): date now accepts Date, string, or number

- src/index.ts
- src/plugins/shake.ts
> feat(shake): add Shake plugin

- src/index.ts
- src/plugins/zip.ts
> feat(zip): add zip plugin

- DEVELOPER.md
Steals commit message guidelines from main Ionic project repo
> docs(DEVELOPER.MD): Add commit message guidelines

- src/plugins/file.ts
Added return types to documentation as well as modified return type definition to match actual types returned.
Used union types for promises where applicable.
Builds and gulp docs ok.
> Additions to documentation and type definitions for File plugin

- .gitignore
- DEVELOPER.md
- Also adds .DS_Store to gitignore
> docs(DEVELOPER.MD): Adds steps for adding new plugins to index.ts

- src/index.ts
- src/plugins/video-editor.ts
> feat(VideoEditor): add video editor plugin.

- src/index.ts
- src/plugins/instagram.ts
- src/plugins/plugin.ts
> feat(instagram): add instagram sharing plugin

- src/plugins/camera-preview.ts
- Changes interfaces to match plugin
- Minor docs updates
- Changes startCamera() function signature to match plugin
> fix(camera-preview): Changes implementation to match Cordova plugin

- src/plugins/onesignal.ts
> Updated the OneSignal docs

- src/plugins/file.ts
intended to address [#439](https://github.com/driftyco/ionic-native/issues/439).
> initialize writeFile options

- src/index.ts
- src/plugins/estimote-beacons.ts
Plugin repository: https://github.com/evothings/phonegap-estimotebeacons
TODO: the sub-plugin for the Estimote nearables
> feat(estimote-beacons): Add Estimote beacons plugin

- src/plugins/file.ts
https://developer.mozilla.org/de/docs/Web/API/FileReader --> FileReader expects File and not FileEntry.
> Fix(File): Fixing readFileAs

- src/index.ts
- src/plugins/file-opener.ts
- src/plugins/plugin.ts
> feat(file-opener): add file opener support

- src/plugins/googlemaps.ts
> fix(GoogleMaps): Fixes #452

- src/plugins/deeplinks.ts
- src/plugins/facebook.ts
- src/plugins/googlemaps.ts
> fix(install-instructions): Fixes install instructions for deeplinks, facebook and googlemaps

- src/plugins/base64togallery.ts
- Promise of error run how success and this not run.
> Base64toGallery order callback @Cordova

- src/plugins/file.ts
This prevents app crash when user picks a big file to write
> fix(file): adds chunked blob writing

- src/plugins/statusbar.ts
Replace `status Var` to `status Bar`
> Fix typo in StatusBar doc

- src/plugins/socialsharing.ts
- Improvements docs;
- Fix order callback because params are optional;
- Feature add method shareVia();
- Feature add params optionals canShareVia().
> Improvements socialsharing

- src/plugins/background-geolocation.ts
Extension of the BackgroundGeolocation plugin to make it compatible with the latest version of the plugin
> Extension of the BackgroundGeolocation plugin

- src/plugins/taptic.ts
@mlynch 
Added docs for the `selection` method and fixed the return type for all functions.
> docs(taptic): improve docs

- src/plugins/emailcomposer.ts
Fix docs wrap EmailComposer only changes in [pluginRef](https://github.com/driftyco/ionic-native/commit/a092a31a1ed4c286d922f0c5089d1b4bab5d46a6)
> docs(emailcompposer): fix docs #568

- src/plugins/pay-pal.ts
> fix(paypal): fix typings, add PayPalItem and PayPalPaymentDetails

- src/index.ts
- src/plugins/z-bar.ts
Add support for the zBar plugin https://github.com/tjwoon/csZBar
> feat(zBar): add zBar barcode scanner plugin

- src/plugins/pay-pal.ts
Delete **:** of the params see http://ionic-site-staging.herokuapp.com/docs/v2/native/paypal/.
> docs(paypal): delete ':' of the params

- src/plugins/plugin.ts
create a new pull request based on the feedback from https://github.com/driftyco/ionic-native/pull/646
> fix google maps setPadding not working issue #573

- src/index.ts
- src/plugins/http.ts
> feat(http): add cordovaHTTP wrapper

- src/index.ts
- src/plugins/http.ts
- Fix 
- Export system module;
- Add attribute platforms decorator @Plugin();
- Typo name parameter uploadFile().
- Style 
- Angular style;
- Delete multiline
> Improvements Http

- src/plugins/themeable-browser.ts
> fix(themeablebrowser): add missed options

- src/plugins/file.ts
> fix(file): fix writeFile method

- src/plugins/camera-preview.ts
> Remove Quote

- src/plugins/imagepicker.ts
> Image picker improvements

- src/index.ts
- src/plugins/device-feedback.ts
> feat(device-feedback): add DeviceFeedback plugin

- src/plugins/sqlite.ts
> fix(sqlite): fix callback order for transaction

- src/index.ts
- src/plugins/filepath.ts
Adds cordova-plugin-filepath (https://github.com/hiddentao/cordova-plugin-filepath)
I use it for following workflow:
FileChooser -> FilePath -> Transfer
> feat(filepath): add cordova-plugin-filepath

- src/plugins/filepath.ts
> feat(filepath): add name field 

- scripts/templates/wrap-min.tmpl
- scripts/templates/wrap.tmpl
> feat(templates): add name field

- src/plugins/themeable-browser.ts
> feat(themeable-browser): add name field

- src/plugins/device-feedback.ts
> feat(devicefeedback): add name field

- src/plugins/stepcounter.ts
> feat(stepcounter): add name field

- src/plugins/z-bar.ts
> feat(zbar): add name field

- src/plugins/http.ts
> feat(http): add name field

- src/plugins/location-accuracy.ts
> feat(location-accuracy): add name field

- src/plugins/filetransfer.ts
also add information how to browse your app
files directory, which is hard to find.
I needed very long time to check where my files are.
> docs(Transfer): add how-to download files

- src/plugins/mixpanel.ts
Documentation doesn't specify the repo or the correct command for ionic plugin add ...
> Update mixpanel.ts for documentation

- src/plugins/youtube-video-player.ts
Changed YouTubeVideoPlayer.openVideo to YoutubeVideoPlayer.openVideo  (notice the T in Youtube).
> Update youtube-video-player.ts documentation typo

- scripts/docs/prepare.sh
This should clean the old docs before processing the new ones, to remove any old directories.
> chore(scripts): clean old docs before processing

- src/plugins/admob.ts
I thought it'd be nice to give a starting point.
I'll look into documenting return types when I have some more spare time.
> docs(admob) Added basic usage description

- src/plugins/file.ts
Also remove code duplication in writeExistingFile.
This is useful in cases if then you need to use `fileEntry.toURL()` for `new Trasfer().download/upload` method
> refactor(file): add return value to be  file entry in writeFile

- src/plugins/googlemap.ts
I was trying to integrate Ionic Native Google Map plug-in and faced lot of problem. After spending lot of time to make the code work, I think it will be helpful for someone else to use the complete example and create the initial map rendering. Attaching working screen shot.
> Update Example for Ionic Native Google Map

- src/plugins/sim.ts
Add hasReadPermission and requestReadPermission to cordova-plugin-sim
> feat(sim): add new methods

- src/plugins/nfc.ts
Add missing  `mimeType` parameter in `addMimeTypeListener` function
> Fix in nfc definition

- src/plugins/sqlite.ts
Added a placeholder parameter to resolve typescript error
> Typescript error solved

- src/plugins/barcodescanner.ts
> feat(barcodescanner): Add missing options

- src/index.ts
- src/plugins/firebase.ts
> feat(firebase): add firebase plugin

- src/index.ts
- src/plugins/broadcaster.ts
Fixes #875
plugin: https://github.com/bsorrentino/cordova-broadcaster
> feat(broadcaster): add Broadcaster plugin

- src/index.ts
- src/plugins/speech-recognition.ts
> feat(speech-recognition): add new plugin

- src/index.ts
- src/plugins/backlight.ts
plugin: https://github.com/mebibou/cordova-plugin-backlight
> feat(backlight): add Backlight plugin

- src/plugins/googlemap.ts
References: https://github.com/driftyco/ionic-native/issues/819
Missing functions yet:
- removeEventListener()
- off()
- trigger()
> fix(google-maps): Adds some functions of BaseClass

- src/plugins/barcodescanner.ts
https://github.com/phonegap/phonegap-plugin-barcodescanner/pull/408
> feat(barcodescanner): add option disableSuccessBeep

- src/plugins/file.ts
> refactor(file): accept ArrayBuffer for data to write

- src/index.ts
- src/plugins/browser-tab.ts
- src/plugins/firebase.ts
Fixes #1115. Added the `hasPermission`function to Firebase Plugin
> feat/fix: Implemented support for BrowserTab #1077 Fixed hasPermission Firebase #1115

- src/index.ts
- src/plugins/app-update.ts
AppUpdate plugin for Cordova/Ionic Applications (Android only).
https://github.com/vaenow/cordova-plugin-app-update
> feat(app-update): add cordova-plugin-app-update support

- src/plugins/text-to-speech.ts
https://github.com/vilic/cordova-plugin-tts/pull/32
> feat(text-to-speech): Add stop method

- src/plugins/file.ts
Reverts driftyco/ionic-native#1086
> Revert "fix(File): typing where `FileError` can be thrown"

- src/plugins/sqlite.ts
The `{}` should be `[]`, but since there is no binding we do not get error. In case we add one, then the syntax will be incorrect.
> Syntax error resolved

- src/plugins/filepath.ts
> Update File path plugin docs

- src/plugins/pay-pal.ts
'sku' needs to be made 'optional' as explained in the documented comment
> Update to pay-pal.ts

- src/plugins/apppreferences.ts
Close code block to make it render properly
> Updated AppPreferences docs

- src/plugins/diagnostic.ts
fixed typo in example code bluetoothState is defined singular at line 101
> (docs) change bluetoothStates to bluetoothState

- src/plugins/camera-preview.ts
Hi,
The Camera Preview Plugin improved a lot lately and an update here is needed.
I also updated the documentation.
I tested on an Nexus 5X. 
It seems that the npm package of the plugin isn't up-to-date, so for the moment, the command to install the plugin is :
```
ionic plugin add https://github.com/cordova-plugin-camera-preview/cordova-plugin-camera-preview.git
```
Any feedback is welcome.
Related issue : #1172
> Update the signature of Cordova Plugin Camera Preview

- src/@ionic-native/plugins/background-geolocation/index.ts
From old BackgroundGeolocation.finish() to new this.backgroundGeolocation.finish();
> fix documentation

- src/@ionic-native/plugins/toast/index.ts
Changed thisoast to this.toast
> Fixed typo

- package.json
- scripts/build/build.js
- scripts/build/publish.js
- scripts/build/tsconfig-core.json
- scripts/build/tsconfig-plugin.json
- scripts/config.json
- scripts/docs/dgeni-readmes-config.js
- scripts/docs/gulp-tasks.js
- tsconfig.json
- Publish everything to `/dist/@ionic-native/` instead of `/dist/packages-dist/@ionic-native`
- Get rid of `plugins` directory that was under `packages-dist`
This way it's consistent with the way it's installed in a project: `node_modules/@ionic-native/*`
> chore(): modify dist paths

- src/@ionic-native/plugins/secure-storage/index.ts
Fixes the plugin not found issue by using the correct pluginRef.
> fix(secure-storage): Update the pluginRef

- src/@ionic-native/plugins/admob-free/index.ts
> feat(admob-free): add AdMobFree plugin

- src/@ionic-native/plugins/sqlite-porter/index.ts
- src/@ionic-native/plugins/sqlite/index.ts
> feat(sqlite-porter): add SQLite porter plugin

- src/@ionic-native/plugins/admob-free/index.ts
Can't import from 'ionic-native'. need to use "@ionic-native/admob-free".
> Import from @ionic-native

- src/@ionic-native/plugins/paypal/index.ts
The import ref for paypal is incorrect. I've added the correct name.
> import ref for paypal is incorrect

- src/@ionic-native/plugins/push/index.ts
Resolves - https://github.com/driftyco/ionic-native/issues/1331
> added 'any' to avoid TS errors

- src/@ionic-native/plugins/video-player/index.ts
the imported library is missing the ending apostrophe
> fixed missing ' on line 29

- src/@ionic-native/plugins/nfc/index.ts
labeled methods with classes, improved method descriptions
> Trying to make documentation a bit clearer

- src/@ionic-native/plugins/sqlite-porter/index.ts
Fix documentation with new import path
> Fix SQLitePorter plugin documentation

- src/@ionic-native/core/plugin.ts
For: https://github.com/driftyco/ionic-native/issues/1327
I get an error, originating there, and I need to know how to handle it
> fix(cordova-plugin): add check if method exists

- src/@ionic-native/plugins/battery-status/index.ts
> bug(doc): battery-status example fix

- scripts/docs/update_docs.sh
- src/@ionic-native/plugins/flurry-analytics/index.ts
Flurry Analytics wrapper
Repo: https://github.com/blakgeek/cordova-plugin-flurryanalytics
Supported platforms:
- Android
- iOS
> Added Flurry Analytics wrapper

- src/@ionic-native/plugins/native-geocoder/index.ts
**native-geocoder: added district for larger cities**
look here:
https://github.com/sebastianbaar/cordova-plugin-nativegeocoder/commit/2b08896193e1fbbff4a91f11aca74275fb48077a
> native-geocoder: added district for larger cities

- src/@ionic-native/plugins/google-maps/index.ts
Issue: https://github.com/driftyco/ionic-native/issues/1370
> Fix Geocoder's pluginRef

- src/@ionic-native/plugins/action-sheet/index.ts
**Notes:**
- Add browser to the platforms
- Add subtitle
- Add possibility to set the destructive button being the last or not
> feat(action-sheet): update to newest version

- src/@ionic-native/plugins/camera-preview/index.ts
Hi,
New methods related to exposure, zoom and flash modes are now available in the master.
I propose to update the wraper for Ionic, so we can use new features from Ionic.
Have performed all my tests using Ionc 2.
Kind regards
> New methods and constants available for CameraPreview

- src/@ionic-native/plugins/taptic-engine/index.ts
On line 11 there was not closing single quote.
> Bad import quote

- src/@ionic-native/plugins/media/index.ts
The function never returns an object of MediaObject. The onSuccess callback is wrongly used to return the object. In fact, onSuccess/onError callbacks are only invoked after the current play, record, or stop action is called. The use of promise is unnecessary.
> fix(media): function 'create' never returns media object

- src/@ionic-native/plugins/native-page-transitions/index.ts
Support for executePendingTransition and cancelPendingTransition
> feat(native-page-transitions): pendingTransition

- src/@ionic-native/plugins/in-app-purchase/index.ts
Only the productid is needed
com.mycompany.productID --> productID
> docs(): remove identifier from product id

- src/@ionic-native/plugins/firebase/index.ts
the OCD in me is here to help 😂
> Fix typos in comments/documentation

- src/@ionic-native/plugins/firebase/index.ts
Added support for errorlogs and crash reporting in my [recent PR to cordova-plugin-firebase](https://github.com/arnesson/cordova-plugin-firebase/pull/253), this is the matching change to support that in @ionic-native/firebase
> feat(firebase): add support for firebase ErrorLog

- src/@ionic-native/plugins/secure-storage/index.ts
. changed myKey to key and myItem to value
> docs(secure storage): Renamed item to key

- README.md
- Update example import for Ionic >2
- Removed Ionic 2.x
- typo
> docs(README): Ionic 3 Update / typo

- src/@ionic-native/plugins/barcode-scanner/index.ts
> typo(barcode-scanner): fixe circle lint error

- src/@ionic-native/plugins/globalization/index.ts
Added missing return types to getDatePattern.
> bug(globalization): getDatePattern return types

- src/@ionic-native/plugins/touch-id/index.ts
> update(touch-id): didFingerprintDatabaseChange

- src/@ionic-native/plugins/geofence/index.ts
Didn't seem quite obvious to me so might help someone else
> Adding the unit of measurement for radius value

- src/@ionic-native/plugins/zbar/index.ts
- fixed import
- fixed options
> docs(zbar): fixed import and usage

- src/@ionic-native/plugins/mixpanel/index.ts
Release 3.0 removed the showSurvey method
https://github.com/samzilverberg/cordova-mixpanel-plugin/commit/8d675d779dde61a907cc6abb36605dfb289d4714
>  remove survey functionality as its been removed in the mixpanel libs
> update(Mixpanel): removed showSurvey

- src/@ionic-native/plugins/native-storage/index.ts
> refactor(native-storage): missing method

- src/@ionic-native/plugins/in-app-browser/index.ts
I struggled to figure out what options I had for target until I read them from the github repo.
I'm assuming that the documentation is generated from the comments and I think addition clarifies the intent of `target` a bit.
> clarify the options for target

- src/@ionic-native/plugins/camera-preview/index.ts
> refactor(camera-preview): missing method

- src/@ionic-native/plugins/diagnostic/index.ts
update camera API function signatures to support cordova.plugins.diagnostic@3.6.0. See https://github.com/dpa99c/cordova-diagnostic-plugin/commit/515317e89a874447812de0c720367c3fc68c0872
> refactor(diagnostic plugin)

- src/@ionic-native/plugins/background-mode/index.ts
> refactor(Background Mode): added missing method

- src/@ionic-native/plugins/media/index.ts
See https://github.com/driftyco/ionic-native/issues/1452 for reasons.
And https://github.com/driftyco/ionic-native/issues/1452#issuecomment-299605906 for solution. :sunglasses:
> Added hints for media plugin if its not recording on iOS #1452

- src/@ionic-native/plugins/safari-view-controller/index.ts
> refactor(SafariViewController): added missing options

- src/@ionic-native/plugins/youtube-video-player/index.ts
> refactor(YoutubeVideoPlayer): updated repo

- src/@ionic-native/plugins/social-sharing/index.ts
> refactor(social sharing): added missing method

- src/@ionic-native/plugins/app-preferences/index.ts
> refactor(AppPreferences): changed input type

- scripts/templates/wrap.tmpl
> typo(wrap.tmpl)

- src/@ionic-native/plugins/fingerprint-aio/index.ts
This plugin is out of beta (1.1.0)
> docs(fingerprint aio): out of beta

- src/@ionic-native/plugins/flurry-analytics/index.ts
> refactor(FlurryAnalyticsPlugin): fixed wrong pluginRef

- src/@ionic-native/plugins/android-permissions/index.ts
> feat(plugin): Android Permissions

- src/@ionic-native/plugins/intercom/index.ts
> feat(plugin): Intercom

- src/@ionic-native/plugins/wheel-selector/index.ts
Added the native wheel selector plugin at:
https://github.com/jasonmamy/cordova-wheel-selector-plugin
To ionic-native.
> feat(wheel-selector): Native wheel selector for Android and iOS

- src/@ionic-native/plugins/autostart/index.ts
> feature(plugin): Autostart

- src/@ionic-native/plugins/file-encryption/index.ts
> feat(plugin): File encryption

- src/@ionic-native/plugins/broadcaster/index.ts
> docs(Broadcaster): fixed example

- src/@ionic-native/plugins/mobile-accessibility/index.ts
> feature(plugin): mobile-accessibility

- src/@ionic-native/plugins/firebase/index.ts
> refactor(firebase): change platforms

- src/@ionic-native/plugins/fcm/index.ts
Align with upstream ```cordova-plugin-fcm```
> Updated method name

- src/@ionic-native/plugins/video-capture-plus/index.ts
> feat(plugin): Video Capture Plus

- package.json
And maybe we should upgrade to Angular 4.1 and TypeScript 2.3
> core(package): update tslint-ionic-rules

- package.json
- src/@ionic-native/plugins/file/index.ts
- Update typings
- Add `IFile` interface that represents the original `window.File`
This commit might not close the following issues directly, but I tested the code given in these issues and it works well.
Closes #1545 
Closes #1513 
Closes #1460 
Closes #1174 
Closes #806
> fix(file): various fixes

- src/@ionic-native/plugins/wheel-selector/index.ts
Changed the interfaces to align with the native plugin code.  Also took out the displayKey field as it interferes with the interface.
> refactor(wheel-selector): fixed the interfaces and default values

- src/@ionic-native/plugins/image-picker/index.ts
The option "maximumImagesCount" works only for Android. So there should be a comment.
> The option "maximumImagesCount" works only for Android.

- src/@ionic-native/plugins/mixpanel/index.ts
Add support to timeEvent for measure time duration the events
> feat(mix-panel): add timeEvent

- src/@ionic-native/plugins/fcm/index.ts
import { FCM } from **'ionic-native'**;  ---> **Corrected as**  -->  import { FCM } from **'@ionicnative/fcm'**;
> Correction in import statement in FCM

- src/@ionic-native/plugins/user-agent/index.ts
A plugin that might be interesting for the framework, the cordova-useragent. It's based on https://github.com/LouisT/cordova-useragent
> feat(user-agent): add User-Agent plugin

- src/@ionic-native/plugins/fcm/index.ts
data.wasPressed
should be change as data.wasTapped
> Worng Parameter in OnNotification()

- src/@ionic-native/plugins/native-keyboard/index.ts
> feat(native-keyboard): add native keyboard plugin

- src/@ionic-native/plugins/native-geocoder/index.ts
> docs(nativegeocoder): out of beta

- src/@ionic-native/plugins/flurry-analytics/index.ts
fix: FlurryAnalaytics to FlurryAnalytics
> Update class name

- src/@ionic-native/core/util.ts
ionic plugin add ... => ionic cordova plugin add ...
> Fix "Install the plugin" command when not installed

- src/@ionic-native/plugins/ftp/index.ts
This cordova plugin is created to use ftp (client) in web/js.
> feat(plugin): add FTP plugin

- src/@ionic-native/plugins/secure-storage/index.ts
> fix(secure-storage): add missing function

- package-lock.json
- package.json
I added some fields to the package.json.
And since NPM 5.0, there is a package.lock.json file.
> typo(package): added fields

- .github/CONTRIBUTING.md
- src/@ionic-native/core/util.ts
- src/@ionic-native/plugins/deeplinks/index.ts
- src/@ionic-native/plugins/facebook/index.ts
- src/@ionic-native/plugins/image-resizer/index.ts
I also removed some V2 tags from Ionic and Angular
> docs(): remove old cli commands

- src/@ionic-native/plugins/clipboard/index.ts
- added package.json
- added windows support
- added npm support
fix #1643
> refactor(tts): changed plugin source

- package.json
I had some problems with the outdated dependencies.
> fix(package): fix Node 8 install problems

- src/@ionic-native/plugins/onesignal/index.ts
Adde d a new method available in the oneSignal Cordova SDK
https://documentation.onesignal.com/docs/cordova-sdk
More methods will probably need to be added
> Add getPermissionSubscriptionState

- src/@ionic-native/plugins/mobile-accessibility/index.ts
> mobile-accessibility docs param typo fix

- src/@ionic-native/plugins/ibeacon/index.ts
> fix(IBeacon): optional parameter

- src/@ionic-native/plugins/in-app-purchase-2/index.ts
Fixed Register function to sync with Cordova operations.
> (fix): sync register function

- src/@ionic-native/plugins/media/index.ts
(still bad as usage hint is in there, but at least not the only thing any more)
> docs(media): Make description less bad

- src/@ionic-native/plugins/qqsdk/index.ts
add cordova-plugin-qqsdk, Github repository is [here](https://github.com/iVanPan/Cordova_QQ), npm is [here](https://www.npmjs.com/package/cordova-plugin-qqsdk)
> feat(cordovan-plugin-qqsdk): add qqsdk plugin

- src/@ionic-native/plugins/screen-orientation/index.ts
by removing outdated sentence and info
> docs(screen-orientation): fixed description

- src/@ionic-native/plugins/firebase-dynamic-links/index.ts
The config.xml example needed to switch the ios and android tag.
Added an example how to use onDynamicLink()
> (doc): Improved the docs for firebase dynamic links

- src/@ionic-native/plugins/in-app-purchase-2/index.ts
Updated the doc with usage examples
> (doc): updated docs with usage example

- package.json
> chore(package): bump dev deps

- src/@ionic-native/plugins/in-app-purchase-2/index.ts
> feat(in-app-purchase2): add a second InAppPurchase plugin

- src/@ionic-native/plugins/email-composer/index.ts
> feat(email-composer): update plugin to latest version and use original plugin

- src/@ionic-native/plugins/google-analytics/index.ts
In the trackMetric the first and second parameter is a number type.
> Fix parameter in the trackMetric method

- README.md
link to branch instead of specific version so possible future updates are reflected after clicking the link
> docs(readme) improve link to 2.x README

- src/@ionic-native/plugins/wheel-selector/index.ts
Changed to be in sync with cordova plugin
> refactor(): added default items interface

- src/@ionic-native/plugins/hyper-track/index.ts
Plugin that helps with location based services (i.e. track users, assign tasks, etc)
> feat(HyperTrack): add plugin

- src/@ionic-native/plugins/firebase/index.ts
Added new method `unregister()`.
https://github.com/arnesson/cordova-plugin-firebase#unregister
> feat(firebase): add unregister method

- src/@ionic-native/plugins/keychain-touch-id/index.ts
Adding the support of Keychain TouchId plugin
> feat(keychain-touch-id): add KeychainTouchID plugin

- src/@ionic-native/plugins/serial/index.ts
This is for the serial plugin.
> Add missing options for the open method

- src/@ionic-native/plugins/card-io/index.ts
Added iOS10 permission message and corrected requireCVV use
> Update CardIO docs

- src/@ionic-native/plugins/paypal/index.ts
fixes my feature request: https://github.com/ionic-team/ionic-native/issues/1855
> feat(paypal): added optional payee email for third party merchants

- src/@ionic-native/plugins/ms-adal/index.ts
The docs say User Identifier is optional but the method does not reflect it.
> Make userId optional in method

- src/@ionic-native/plugins/google-maps/index.ts
added debug option to TileOverlayOptions.
> added debug option to TileOverlayOptions

- src/@ionic-native/plugins/safari-view-controller/index.ts
The show method returns a Observable, not a Promise.
> docs(safariview): usage fix

- package-lock.json
- src/@ionic-native/plugins/http/index.ts
Hello.
Since the repository `https://github.com/wymsee/cordova-HTTP` is no longer maintained I would like to propose to switch to a fork of the plugin which is maintained nicely.
Thanks.
> HTTP Lib update

- src/@ionic-native/plugins/stripe/index.ts
fix stripe create card token promise
> fix(stripe): fix stripe create card token

- src/@ionic-native/plugins/extended-device-information/index.ts
Gets the System Memory and the CPU Information
> Added Extended Device Information

- src/@ionic-native/plugins/qr-scanner/index.ts
fix(qr-scanner): added destroy method (#1916)
> fix(qr-scanner): added destroy method (#1916)

- src/@ionic-native/plugins/ble/index.ts
Fixes https://github.com/ionic-team/ionic-native/issues/2008
> fix(BLE): make readRSSI() not static

- DEVELOPER.md
Add document for decorator as mentioned in #2006
> docs(DEVELOPER) Add documentation for CordovaFunctionOverride decorator

- src/@ionic-native/plugins/pro/index.ts
* Updated js API for `cordova-plugin-ionic`2.0.0
* Fixed `download` and `extract` to properly use observables
> feat(pro): support corova-plugin-ionic v2.0.0

- src/@ionic-native/plugins/http/index.ts
Hi guys,
I've implemented some changes to match the changes I've made in the cordova plugin (addressing #2052 #2022 #2053).
> Some updates for HTTP plugin

- src/@ionic-native/plugins/app-rate/index.ts
Adding the simpleMode preference from https://github.com/pushandplay/cordova-plugin-apprate#options--preferences to resolve https://github.com/ionic-team/ionic-native/issues/2154.
> Add simpleMode to @ionic-native/plugins/app-rate

- package-lock.json
- src/@ionic-native/plugins/deeplinks/index.ts
Add options parameter to Deeplinks routeWithNavController method.
Closes #1601
> fix(deeplinks): add options parameter(#1601)

- src/@ionic-native/plugins/web-intent/index.ts
> fix(web-intent): fix false negative of plugin installation

- src/@ionic-native/plugins/android-exoplayer/index.ts
plugin: https://github.com/frontyard/cordova-plugin-exoplayer
> feat(android exoplayer): add cordova-plugin-exoplayer

- src/@ionic-native/plugins/ftp/index.ts
- src/@ionic-native/plugins/network-interface/index.ts
Fix for #2147
I'm a newbie, I hope someone could help me edit my PR, if anything looks wrong with it.
> fix(ftp): return observable (not promise) for upload and download method

- src/@ionic-native/plugins/push/index.ts
Missing single quotation mark on doc.
> Missing single quotation mark

- src/@ionic-native/plugins/google-play-games-services/index.ts
Adding support for cordova-plugin-play-games-services.
> feat(GooglePlayGamesServices): add plugin

- src/@ionic-native/plugins/call-number/index.ts
Update CallNumber plugin, add function isCallSupported
> feat(call-number): update CallNumber

- src/@ionic-native/plugins/ms-adal/index.ts
User Info is also included in the authentication result
> User Info in the AuthenticationResult

- src/@ionic-native/plugins/file-transfer/index.ts
> Deprecation notice

- src/@ionic-native/plugins/contacts/index.ts
> docs(contact): mark as deprecated

- src/@ionic-native/plugins/globalization/index.ts
> docs(globalization): mark plugin as deprecated

- src/@ionic-native/plugins/web-intent/index.ts
I also updated the description and removed the beta tag because of the 1.0 release a week ago.
> feat(web-intent): add startService function

- src/@ionic-native/plugins/printer/index.ts
> fix(printer): add correct npm repository

- src/@ionic-native/plugins/google-analytics/index.ts
> feat(google-analytics): add missing functions

- src/@ionic-native/plugins/push/index.ts
> fix(push): Android senderID as optional

- src/@ionic-native/plugins/crop/index.ts
> ref(crop): add options interface

- src/@ionic-native/plugins/index-app-content/index.ts
> fix(index-app-content): remove onItemPressed function

- src/@ionic-native/plugins/app-update/index.ts
related to: https://github.com/vaenow/cordova-plugin-app-update/pull/62
> feat(app-update): add app update options

- src/@ionic-native/plugins/firebase-analytics/index.ts
> fix(firebase-analytics): add `sync` option for all methods

- src/@ionic-native/plugins/http/index.ts
Documentation was copied from cordova plugin, but the answer was not linked as indicated.
> docs(http): linking Stackoverflow answer for .pem to .cer

- src/@ionic-native/plugins/mixpanel/index.ts
Added events: getSuperProperties, registerSuperPropertiesOnce, unregisterSuperProperty
> feat(mix panel): add missing events

- src/@ionic-native/plugins/push/index.ts
- add missing the decorator option: callbackOrder: 'reverse' to channels
- Added sound property to create channel
> feat(push): add missing decorator option to channel

- src/@ionic-native/plugins/local-notifications/index.ts
added a new param to specify if the notification will be silent
> feat(local-notifications) add silent configuration parameter

- src/@ionic-native/plugins/in-app-browser/index.ts
This PR adds the new options for Android introduced in release 2.0.2 of the In App Browser plugin.
> feat(in-app-browser): add new footer options for Android

- src/@ionic-native/plugins/call-log/index.ts
Hello,
here is a wrapper of our cordova-plugin-calllog, a plugin to get the call log of device.
Thanks !
> feat(call-log): add plugin

- src/@ionic-native/plugins/background-mode/index.ts
Added missing descriptions taken from the plugin's repo README.
> docs(background-mode): added push parameter description

- src/@ionic-native/plugins/broadcaster/index.ts
I've added `Browser` as supported platform
> docs(broadcaster): add support for browser platform

- src/@ionic-native/plugins/music-controls/index.ts
This will add optional parameters for icons in android.
> feat(music-controls): add new optional parameters for icons

- src/@ionic-native/plugins/blinkup/index.ts
- Added Electric Imp Blinkup Plugin support
- Cordova plugin: https://www.npmjs.com/package/cordova-plugin-blinkup
> feat(BlinkupPlugin): added ElectricImp BlinkUp

- src/@ionic-native/plugins/speechkit/index.ts
Nuance SpeechKit ionic-native implementation
> feat(plugin): add SpeechKit plugin

- src/@ionic-native/plugins/file-picker/index.ts
> fix(file-picker): use correct plugin ref

- src/@ionic-native/plugins/autostart/index.ts
Added a tiny fix to the description text to make it read better.
> docs(autostart): add correct plugin description

- src/@ionic-native/plugins/web-intent/index.ts
fix(web-intent): fix options param for startService, sendBroadcast, startActivityForResult, startActivity
> fix(web-intent): fix options param

- src/@ionic-native/plugins/in-app-browser/index.ts
Add new option from plugin relase 3.0.0
> docs(inappbrowser): add new option hidespinner

- src/@ionic-native/plugins/clipboard/index.ts
-  Added the possibility to clean the clipboard on Android, iOS and Windows.
> feat(clipboard)Added ability to clean clipboard :sparkles:

- scripts/templates/wrap-min.tmpl
- scripts/templates/wrap.tmpl
As far as I know this step is not necessary anymore.
> chore(plugin-generator): remove notice of /src/index.ts

- src/@ionic-native/plugins/call-directory/index.ts
This adds the plugin for identfifying incomming calls: https://www.npmjs.com/package/cordova-plugin-call-directory
> feat(calldirectory): add call directory plugin

- src/@ionic-native/plugins/clipboard/index.ts
- src/@ionic-native/plugins/email-composer/index.ts
- src/@ionic-native/plugins/fcm/index.ts
- src/@ionic-native/plugins/in-app-browser/index.ts
- src/@ionic-native/plugins/qr-scanner/index.ts
- src/@ionic-native/plugins/web-intent/index.ts
Working on the new typedoc setup for the ionic v4 docs, I ran in to some linting errors that caused the docs to fail to compile. This fixes those. 
Here's the error from typedoc
```shell
typedoc --tsconfig tsconfig.json --json dist/docs.json --mode modules src/@ionic-native/plugins/*/index.ts
Using TypeScript 2.7.2 from /Users/perry/Development/ionic-docs/node_modules/typedoc/node_modules/typescript/lib
Error: /Users/perry/Development/ionic-docs/sources/ionic-native/src/@ionic-native/plugins/email-composer/index.ts(127)
Cannot find name 'getPromise'.
Error: /Users/perry/Development/ionic-docs/sources/ionic-native/src/@ionic-native/plugins/email-composer/index.ts(127)
Parameter 'resolve' implicitly has an 'any' type.
Error: /Users/perry/Development/ionic-docs/sources/ionic-native/src/@ionic …
```
> fix(linting): Fixing misc linting errors that typedoc complains about

- src/ionic-native/plugins/in-app-review
> feat(InAppReview): add InAppReview plugin

- DEVELOPER.md
- package-lock.json
- src/@ionic-native/plugins/tealium-adidentifier/index.ts
- src/@ionic-native/plugins/tealium-installreferrer/index.ts
- src/@ionic-native/plugins/tealium/index.ts
Added Tealium wrappers
Minor grammar correction in DEVELOPER.md (it's -> its possessive)
> feat(tealium): add tealium ionic wrappers

- src/@ionic-native/plugins/native-geocoder/index.ts
as described in current version - https://github.com/sebastianbaar/cordova-plugin-nativegeocoder/ - promises resolve with an array
also confirmed this on iOS real device
> fix(native-geocoder) result is array of objects

- src/@ionic-native/plugins/onesignal/index.ts
Added collapse_id to allow for notification stacking.
> feat(onesignal): Added notification stacking

- src/@ionic-native/plugins/star-prnt/index.ts
This change is related to this PR: https://github.com/auctifera-josed/starprnt/pull/11
Merging this should not cause any issues if it's merged before the plugin PR.
> feat(star-prnt): Add support for devices with barcode readers

- src/@ionic-native/plugins/in-app-purchase-2/index.ts
Fixed the interface which should have been a callback not a promise (resulting in promise never gets resolved).
> type(fix): fixes in-app-purchases-2 store.ready not getting fired

- src/@ionic-native/plugins/stripe/index.ts
This is just a fix to match the native code
> fix(stripe): fixed casing of postal code param

- src/@ionic-native/plugins/firebase-messaging/index.ts
@ihadeed Would you mind taking a look at this when you get a chance?
@chemerisuk also tagging you on this since you're the plugin author.
> feat(firebase-messaging): add firebase-messaging

- src/@ionic-native/plugins/three-dee-touch/index.ts
I added the description of the 3D Touch plugin
> docs(three-dee-touch): add plugin description

- src/@ionic-native/plugins/admob-free/index.ts
I added the description of the AdMob Free plugin
> docs(admob-free): add plugin description

- src/@ionic-native/plugins/admob-free/index.ts
- src/@ionic-native/plugins/keyboard/index.ts
I added the description of the Keyboard plugin
> docs(keyboard): add plugin description

- src/@ionic-native/plugins/media-capture/index.ts
I added the description of the Media Capture plugin
> docs(media-capture): add plugin description

- src/@ionic-native/plugins/pin-dialog/index.ts
I added the description of the Pin Dialog plugin
> docs(pin-dialog): add plugin description

- src/@ionic-native/plugins/qr-scanner/index.ts
I added the description of the QR Scanner plugin
> docs(qr-scanner): add plugin description

- src/@ionic-native/plugins/ionic-webview/index.ts
Merging into `v5`
Parent issue: https://github.com/ionic-team/ionic-cli/issues/3279
Corresponds to this branch: https://github.com/ionic-team/cordova-plugin-ionic-webview/tree/wip-server
@jcesarmobile
> feat(ionic-webview): plugin for cordova-plugin-ionic-webview 2.0

- src/@ionic-native/plugins/hce/index.ts
Hey 👋 !
I'm working in a project and I'm currently using `cordova-plugin-hce`, and, to make things easier for others using this plugin, I wrote this plugin.
But, since that this is my first Ionic Native plugin, I may have made some mistakes. If I did so, I'll be happy to fix them.
Thanks for your time :)
> feat(hce): add hce plugin wrapper

- src/@ionic-native/plugins/safari-view-controller/index.ts
I added the description of the Safari View Controller plugin
> docs(safari-view-controller): add plugin description

- src/@ionic-native/plugins/spinner-dialog/index.ts
I added the description of the Spinner Dialog plugin
> docs(spinner-dialog): add plugin description

- src/@ionic-native/plugins/hotspot/index.ts
I added the description of the Hotspot plugin
> docs(hotspot): add plugin description

- src/@ionic-native/plugins/pro/index.ts
Adding some better types on the ProDeploy return values
> docs(pro): add types for return values in deploy

- src/@ionic-native/plugins/sensors/index.ts
> feat(plugin): add Sensors plugin

- src/@ionic-native/plugins/streaming-media/index.ts
The plugin has had a number of enhancement in the past year. Added all of the parameters from those various enhancements and additionally added better documentation.
> feat(streaming-media): add new parameters & docs

- src/@ionic-native/plugins/health-kit/index.ts
checkAuthStatus requires the input type but it is not available in healthKitOptions
> fix(health-kit): add missing checkAuthStatus param

- src/@ionic-native/plugins/app-version/index.ts
fix(app-version): fix getVersionCode to return a `number` Promise as is in the actual implementation instead of a `string`. Also update and clarify the method docs.
> fix(app-version): fix getVersionCode to return number

- src/@ionic-native/plugins/linkedin/index.ts
* added missing `)` in login code
> docs(linkedin): fix example

- src/@ionic-native/plugins/ble/index.ts
fix(ble): change signature for autoConnect (#2573)
closes: #2573
> fix(ble): change signature for autoConnect

- src/@ionic-native/plugins/abbyy-rtr/index.ts
ABBYY Real-Time Recognition implementation.
> feat(abbyy-rtr): add ABBYY Real-Time Recognition plugin

- src/@ionic-native/plugins/alipay/index.ts
...dova-plugin-gubnoi-alipay
(https://github.com/jing-zhou/cordova-plugin-alipay)
> feat(alipay): replace plugin

- src/@ionic-native/plugins/network-interface/index.ts
> docs(network-interface): update example

- src/@ionic-native/plugins/fabric/index.ts
https://github.com/sarriaroman/FabricPlugin
> feat(fabric): add fabric plugin

- src/@ionic-native/plugins/local-notifications/index.ts
Update index.ts add new property foreground
> feat(local-notifications): add new foreground property

- src/@ionic-native/plugins/onesignal/index.ts
> docs(onesignal): fix typo

- src/@ionic-native/plugins/contacts/index.ts
>  fix(contacts): remove double import of checkAvailability

- package-lock.json
- src/@ionic-native/plugins/bluetooth-le/index.ts
Plugin wrap around https://github.com/randdusing/cordova-plugin-bluetoothle
A more complete implementation of the BLE API for Android, iOS and Windows than the exisiting one (named ble).
> feat(bluetooth-le): add bluetooth-le plugin

- src/@ionic-native/plugins/in-app-browser/index.ts
This is the fix for #2683. Sorry for not checking twice.
> fix(in-app-browser): fix mandatory options

- src/@ionic-native/plugins/local-notifications/index.ts
Update `ILocalNotificationAction` for parity with https://github.com/katzer/cordova-plugin-local-notifications/#user-content-properties-1
> feat(local-notifications): Added local additional local notification action fields

- src/@ionic-native/plugins/onesignal/index.ts
Just a copy/pasta typo, me thinks. 👍
> docs(onesignal): update incorrect path to hook file

- src/@ionic-native/plugins/sqlite-db-copy/index.ts
> feat(SqliteDbCopy):add plugin

- src/@ionic-native/plugins/apple-wallet/index.ts
Please review. Waiting for feedback and code review
> feat(plugins): add AppleWallet

- src/@ionic-native/plugins/firebase-messaging/index.ts
Add revokeToken function that was added to the plugin version 1.1.3
> feat(firebase-messaging): add revokeToken function

- src/@ionic-native/plugins/speechkit/index.ts
Add voice parameter to TTS invokation to reflect changes in plugin version 2.0.0
> feat(speechkit): plugin updated with voice parameter

- src/@ionic-native/plugins/admob-plus/index.ts
AdMob Plus is the successor of cordova-plugin-admob-free, which provides a cleaner API and build with modern tools.
Github: https://github.com/admob-plus/admob-plus
> feat(admob-plus): Add admob-plus

- src/@ionic-native/plugins/local-notifications/index.ts
> fix(local-notifications): add missing functions

- src/@ionic-native/plugins/social-sharing/index.ts
Just a tiny error in an anchor link there.
> docs(social-sharing): update web share api link

- src/@ionic-native/plugins/downloader/index.ts
Add support for the [integrator-cordova-plugin-downloader](https://github.com/Luka313/integrator-cordova-plugin-downloader).
> feat(downloader): add plugin

- src/@ionic-native/plugins/blinkid/index.ts
Add support for the [blinkid-cordova](https://github.com/BlinkID/blinkid-phonegap/)
> feat(blinkid): add plugin

- src/@ionic-native/plugins/gao-de-location/index.ts
Through this plug-in, you can get the local location. Reverse Address Coding
> feat(gao-de-location): add plugin

- src/@ionic-native/plugins/analytics-firebase/index.ts
This pull request adds the Firebase Analytics plugin.
This is the plugin cordova-plugin-analytics adapted to work with Firebase.
> feat(analytics-firebase): add plugin

- src/@ionic-native/plugins/adjust/index.ts
This PR adds a plugin for [Adjust Cordova SDK](https://www.npmjs.com/package/com.adjust.sdk).
> feat(adjust): add adjust sdk plugin

- src/@ionic-native/plugins/background-geolocation/index.ts
> docs(background-geolocation): update usage doc

- src/@ionic-native/plugins/http/index.ts
> fix: Add 'legacy' as valid option to setSSLCertMode

- src/@ionic-native/plugins/quikkly/index.ts
hi, looking to add support for quikkly's latest scanning library. cheers, rob
> feat(quikkly): add plugin

- src/@ionic-native/plugins/luxand/index.ts
This plugin add support for Luxand Face SDK
> feat(luxand plugin): add luxand Face SDK plugin

- src/@ionic-native/plugins/apple-wallet/index.ts
Major update to the plugin
+ Enhance documentation 
+ add method to check if there is existing devices paired e.g. Apple Watch
+ add method to check existence and eligibility to add a card
> feat(apple-wallet): update wrapper to release 2.0

- src/@ionic-native/plugins/in-app-purchase-2/index.ts
Add missing function: manageSubscriptions()
> feat(in-app-purchase-2): add manageSubscriptions()

- src/@ionic-native/plugins/purchases/index.ts
Adding Plugin for https://github.com/RevenueCat/cordova-plugin-purchases to use with https://www.revenuecat.com/
> feat(purchases): add new plugin for purchases

- src/@ionic-native/plugins/google-play-games-services/index.ts
Add getPlayerScore function to the google-play-games-services plugin, as the function is already available on the cordova plugin: cordova-plugin-play-games-services.
> feat(google-play-games-services): add getPlayerScore function

- src/@ionic-native/plugins/native-geocoder/index.ts
- result array returns the same information for forward and reverse geocoding
- result array return points of interest string array for iOS and Android
>  feat(nativegeocoder): update plugin to v3.2.0

- package-lock.json
- src/@ionic-native/plugins/device-accounts/index.ts
Fixed: Device account does not support android 8.0 permissions update. Read more here https://developer.android.com/about/versions/oreo/android-8.0-changes
> feat(device-accounts): update plugin source

- src/@ionic-native/plugins/purchases/index.ts
- Updates RCError type
- Updates makePurchase error function
> feat(purchases): update plugin to v0.0.5

- src/@ionic-native/plugins/fingerprint-aio/index.ts
I received some requests with confusion about those parameters. I hope this description clears this up.
> docs(fingerprint-aio): change parameter description

- src/@ionic-native/plugins/firebase-crash/index.ts
Here is the ionic-native wrapper for the [cordova-plugin-firebase-crash](https://github.com/chemerisuk/cordova-plugin-firebase-crash) plugin, written by @chemerisuk.
> feat(firebase-crash): add plugin

- src/@ionic-native/plugins/camera-preview/index.ts
add new method takeSnapshot detailed in plugin and referenced by this open issue: https://github.com/ionic-team/ionic-native/issues/3004
> feat(camera-preview): add wrapper for camera preview snapshot

- src/@ionic-native/plugins/biocatch/index.ts
ionic-native wrapper for the [biocatch-cordova-plugin](https://bitbucket.org/whisprnd/biocatch-cordova-plugin) plugin.
> feat(biocatch): add plugin

- src/@ionic-native/plugins/biometric-wrapper/index.ts
Used for a cordova plugin. The plugin captures the biometric data(iris and fingerprint).
The plugin is in the ionic source project itself.
> feat(biometric-wrapper): add plugin

- src/@ionic-native/plugins/blinkid/index.ts
With the added/modified BlinkCard support recently, a camera overlay setting was added for scanning payment cards.  This PR integrates this feature and adds documentation for using BlinkCard.
> feat(blinkid): added support for card overlay

- src/@ionic-native/plugins/document-scanner/index.ts
New wrapper for plugin https://github.com/NeutrinosPlatform/cordova-plugin-document-scanner.
> feat(document-scanner): add plugin

- src/@ionic-native/plugins/ocr/index.ts
New wrapper for plugin https://github.com/NeutrinosPlatform/cordova-plugin-mobile-ocr.
> feat(ocr): add plugin

- src/@ionic-native/plugins/device-accounts/index.ts
Fixed: 
- Added getPermissionsByType, now users can request permissions to other device account types.
> feat(device-accounts): Adding getPermissionsByType function

- src/@ionic-native/plugins/onesignal/index.ts
The functions were missing, Please refer to the issue #2909 
https://github.com/ionic-team/ionic-native/issues/2909
> feat(one signal): add missing "setExternalUserId"  and "removeExternalUserId" functions

- src/@ionic-native/plugins/in-app-purchase-2/index.ts
Ported to typescript from the plugin repo's README and API documentation.
> feat(in-app-purchase-2): add documentation

- src/@ionic-native/plugins/launch-review/index.ts
added missing closing bracket for `.then()`
> docs(launch-review): add missing bracket

- src/@ionic-native/plugins/unvired-cordova-sdk/index.ts
This adds unvired-cordova-sdk plugin. This plugin enables developers to access Unvired Mobile Platform ( UMP ).
> feat(unvired-cordova-sdk): add plugin

- src/@ionic-native/plugins/sum-up/index.ts
Ionic Native Wrapper for cordova sumup plugin to communicate with the SumUp payment terminal.
URL: https://github.com/mariusbackes/cordova-plugin-sumup
> feat(sum-up): add plugin

- src/@ionic-native/plugins/alipay/index.ts
place the plugin under 'window.cordova.plugins.alipay'
> fix(alipay): use correct pluginRef

- src/@ionic-native/plugins/calendar/index.ts
Please add this function [deleteEventById]
> feat(calendar): add deleteEventById function

- src/@ionic-native/plugins/deeplinks/index.ts
I will update the plugin readme, too. 👍
> docs(deeplinks): Added informations about AASA (iOS) and Asset Links (Android) to documentation

- src/@ionic-native/plugins/anyline/index.ts
closes: #3074
Co-authored-by: niconaso
> feat(anyline): add plugin

- src/@ionic-native/plugins/wonderpush/index.ts
Added the `wonderpush` wrapper for cordova plugin `wonderpush-cordova-sdk`.
> feat(wonderpush): add plugin

- src/@ionic-native/plugins/smartlook/index.ts
Ionic plugin for [Smartlook SDK](www.smartlook.com). If more information or some changes needed. We will more than happy to provide.
> feat(smartlook): add plugin

- src/@ionic-native/plugins/chooser/index.ts
added a '?' to make 'accept' parameter optional
> fix(chooser): @param accept is supposed to be optional

- src/@ionic-native/plugins/file-chooser/index.ts
added missing optional parameter to support mime types
> feat(file-chooser): add missing options param

- src/@ionic-native/plugins/anyline/index.ts
Pull request to anyline-ocr-cordova-module 
https://github.com/Anyline/anyline-ocr-cordova-module/pull/39
> fix(anyline): added official plugin

- src/@ionic-native/plugins/screen-orientation/index.ts
> fix(screen-orientation): add window element to eventObservable

- src/@ionic-native/plugins/ssh-connect/index.ts
Added the `ssh-connect` wrapper for [cordova-plugin-ssh-connect](https://github.com/JosePerez27/cordova-plugin-ssh-connect)
> feat(cordova-plugin-ssh-connect): add new plugin for ssh connection

- src/@ionic-native/plugins/line-login/index.ts
https://github.com/nrikiji/cordova-line-login-plugin/commit/a19e002a811351702d342dc964d78261c3649928
Fixed the codeova plugin refactor.
> fix(line-login): adjustment parameter

- src/@ionic-native/plugins/mobile-accessibility/index.ts
https://ionicframework.com/docs/native/mobile-accessibility
> docs(mobile-accessibility): adjust documentation

- src/@ionic-native/plugins/http/index.ts
- support uploading multiple files
- support response type `json
> feat(http): add type definitions for new features available in v2.2.0

- src/@ionic-native/plugins/emm-app-config/index.ts
Add [emm-app-config](https://github.com/oracle/cordova-plugin-emm-app-config) plugin to retrieve EMM application configuration
> feat(emm-app-config): add plugin

- src/@ionic-native/plugins/keyboard/index.ts
also changed the resizeMode from string to KeyboardResizeMode with the only 4 possible values and added missing keyboardDidShow and keyboardDidHide
> fix(keyboard): Update types with new 2.2.0 methods

- src/@ionic-native/plugins/smartlook/index.ts
> feat(smartlook): add iOS platform

- src/@ionic-native/plugins/alipay/index.ts
- src/@ionic-native/plugins/photo-library/index.ts
https://github.com/terikon/cordova-plugin-photo-library/issues/158
> fix(alipay): adjust pay function properties

- src/@ionic-native/plugins/wechat/index.ts
> fix(wechat): add missing cordova decorators

- src/@ionic-native/plugins/push/index.ts
We have added inline property for Push Notification for iOS device. we will also do pull request for phonegap-plugin-push node module for handling that property
> fix(push): add inline reply property

- src/@ionic-native/plugins/firebase-x/index.ts
Added description field to IChannelOptions object and changed vibration type to get a number array
> fix(firebase-x): adjust typings

- src/@ionic-native/plugins/facebook/index.ts
Added facebook4 plugin's activateApp method to manually start capturing events #3218
> feat(facebook): add activateApp function

- src/@ionic-native/plugins/background-mode/index.ts
implemented disableBatteryOptimizations() method #3085
> feat(background-mode): add disableBatteryOptimizations function

- src/@ionic-native/plugins/purchases/index.ts
changed optional parameter oldSkus to comply with the updated plugin code
> fix(purchases): changed optional parameter oldSku

- src/@ionic-native/plugins/preview-any-file/index.ts
updated documents to reflect correct import path
> docs(update): Preview any file import path

- src/@ionic-native/plugins/image-picker/index.ts
See parameters: https://github.com/Telerik-Verified-Plugins/ImagePicker/blob/master/www/imagepicker.js#L56
> docs(image-picker): updated configuration

- src/@ionic-native/plugins/in-app-browser/index.ts
Addressing issue #3152 for version 4 of this plugin.
> feat(in-app-browser): add "beforeload" callback method

- src/@ionic-native/plugins/ms-adal/index.ts
Adds missing Authentication Settings class declaration
> feat(ms-adal): add authentication settings

- src/@ionic-native/plugins/in-app-browser/index.ts
added data in Event interface for InApp Browser. fixes #3244
> feat(in-app-browser): add data in Event interface

- src/@ionic-native/plugins/camera-preview/index.ts
added getCameraCharacteristics to get the characteristics of all available cameras. #3163
> feat(camera-preview):add getCameraCharacteristics

- src/@ionic-native/plugins/image-picker/index.ts
Updates configuration for image-picker ionic plugin on v4 branch
Same as #3245 on master
> docs(image-picker): v4 updated configuration

- src/@ionic-native/plugins/firebase-analytics/index.ts
added resetAnalyticsData method to firebase-analytics plugin
> feat(firebase-analytics): add resetAnalyticsData to firebase-analytics

- src/@ionic-native/plugins/app-update/index.ts
since https://github.com/vaenow/cordova-plugin-app-update supports **Skip dialog boxes** feature, so add corresponding params
> feat(app-update): skip dialog boxes support

- src/@ionic-native/plugins/sign-in-with-apple/index.ts
The app crashes with plugin version 0.1.0 because they added options for the plugin
> docs(sign-in-with-apple): updated documentation

- src/@ionic-native/plugins/secure-storage-echo/index.ts
Implemented extra options according to https://github.com/mibrito707/cordova-plugin-secure-storage-echo#android-init-options
> feat(cordova-secure-storage-echo): Added extra options

- src/@ionic-native/plugins/admob/index.ts
- Fix typo
- Support adsense for PWA's
> fix(admob): fix interstitialAdId parameter typo

- src/@ionic-native/plugins/admob-free/index.ts
Implements missing properties to the admob configuration interfaces.
> feat(admob-free): add missing config properties

- .prettierrc
- src/@ionic-native/plugins/firebase-x/index.ts
Fixing this issue :  https://github.com/ionic-team/ionic-native/issues/3321
> fix(cordova-firebase-x) updated methods in index.ts

- src/@ionic-native/plugins/in-app-purchase-2/index.ts
This commit does a couple of things:
1. It updates the types of a couple of attributes which are not correctly typed.
2. It updates the return value of `IAPProductEvents` members so that they can be chained.
3. Adds `applicationUsername` which is vital for using the IAP2 module with a validation service.
> feat(in-app-purchase-2): update types and add getApplicationUsername function

- src/@ionic-native/plugins/mobile-messaging/index.ts
Hi,
Here is ionic-native support for https://github.com/infobip/mobile-messaging-cordova-plugin
> feat(mobile-messaging): add plugin

- src/@ionic-native/plugins/gao-de-location/index.ts
The plug-in has been updated to 2.0.5, and ionic native also needs to be updated, otherwise it will not work properly.
> feat(gao-de-location): update wrapper to match version 2.0.5

- src/@ionic-native/plugins/clover-go/index.ts
Here is the link to Cordova plugin
https://github.com/hotwax/cordova-plugin-clovergo
The plugin helps to communicate with [Clover Go](https://www.clover.com/shop/clover-go) device and make payment.
> feat(clover-go): add CloverGo plugin

- src/@ionic-native/plugins/nfc/index.ts
This closes #2193, closes #2873, and closes #2756
> feat(nfc): update to phonegap-nfc@1.1.1

- src/@ionic-native/plugins/usabilla-cordova-sdk/index.ts
This adds an Ionic Native Wrapper for the cordova usabilla plugin. The plugin enables integration with the Usabilla sdk.
> feat(usabilla-cordova-sdk): add plugin

- src/@ionic-native/plugins/firebase-x/index.ts
firebasex addDocumentToFirestoreCollection not returning document Id.
https://github.com/ionic-team/ionic-native/issues/3385
> fix(firebase-x): return document id

- src/@ionic-native/plugins/admob-plus/index.ts
fixes #3384 . add setDevode for admob-plus
> feat(admob-plus): add setDevMode

- src/@ionic-native/plugins/firebase-x/index.ts
add getId to get app instance id. fixes #3378
> feat(firebase-x): add getId

- src/@ionic-native/plugins/background-fetch/index.ts
add taskId to finish method in background fetch. fixes #3361
> feat(background-fetch): add taskId to finish method

- src/@ionic-native/plugins/firebase-vision/index.ts
Add Ionic native wrapper for cordova firebase vision plugin [https://github.com/alon22/cordova-plugin-firebase-mlvision](https://github.com/alon22/cordova-plugin-firebase-mlvision)
> feat(firebase-vision): add plugin

- src/@ionic-native/plugins/smartlook/index.ts
Added new API methods so the ionic plugin is up-to-date with Smartlook SDK (currently version 1.4.2).
> feat(smartlook): new api methods

- src/@ionic-native/plugins/native-view/index.ts
Plugin wrapper for https://github.com/mfdeveloper/cordova-plugin-nativeview
> feat(native-view): add plugin

- src/@ionic-native/plugins/in-app-purchase-2/index.ts
Add update method from plugin. Fixes: #3411
> feat(in-app-purchase-2): add update function

- src/@ionic-native/plugins/jumio/index.ts
Let me know if you have any questions or requests.
> feat(jumio): add plugin

- src/@ionic-native/plugins/firebase-x/index.ts
Definition for the non-ionic methods are available as
https://github.com/dpa99c/cordova-plugin-firebasex/blob/master/types/index.d.ts
> feat(firebase-x): add missing methods, incl. authenticateUserWithApple

- src/@ionic-native/plugins/camera-preview/index.ts
> feat(camera-preview): add record video functions

- src/@ionic-native/plugins/camera-preview/index.ts
Fixed a typo in the tapFocus option.
> fix(camera-preview): tapFocus

- src/@ionic-native/plugins/firebase-crashlytics/index.ts
- src/@ionic-native/plugins/spotify-auth/index.ts
Closes ionic docs issues:
https://github.com/ionic-team/ionic-docs/pull/1574
and
https://github.com/ionic-team/ionic-docs/pull/1555
> docs(spotify): Spotify Auth & Firebase Crashlytics

- src/@ionic-native/plugins/smartlook/index.ts
Added new and adjusted some API methods so the ionic plugin is up-to-date with Smartlook SDK (currently version 1.5.2).
> feat(smartlook): update to 1.5.2

- src/@ionic-native/plugins/diagnostic/index.ts
Issue Number: #3488 
The cordova-diagnostics Plugin added a Function for the new ios14 location accuracy authorization API: https://github.com/dpa99c/cordova-diagnostic-plugin/blob/master/CHANGELOG.md
This is my first PR to **ionic-native**, i hope everything is correct 😊
> feat(diagnostics): Add support for new iOS14-LocationAccuracy Permission

- src/@ionic-native/plugins/purchases/index.ts
Updates to cordova-plugin-purchases 1.2.0
> feat(purchases): update to plugin version 1.2.0

- src/@ionic-native/plugins/firebase-x/index.ts
I just add the feature to change the auth language of firebase, i am creating the same PR for https://github.com/dpa99c/cordova-plugin-firebasex
Thanks
> feat(firebase-x): add setLanguageCode method for auth

- src/@ionic-native/plugins/purchases/index.ts
Updates to cordova-plugin-purchases 1.3.0
> feat(purchases): update to plugin version 1.3.0

- src/@ionic-native/plugins/file-transfer/index.ts
**Reason:**
https://github.com/apache/cordova-plugin-file-transfer/commit/2d5d3519b95922aa77a1336c0a8764154c938511
> chore(file-transfer): undeprecate

- src/@ionic-native/plugins/mobile-messaging/index.ts
add new fields to Message type and new method to display chat view
> feat(mobile-messaging): add new fields and method

- src/@ionic-native/plugins/fingerprint-aio/index.ts
The latest version of 'fingerprint-aio' has 2 new methods: "registerBiometricSecret" and "loadBiometricSecret"
> feat(fingerprint-air): add new functions

- src/@ionic-native/plugins/adjust/index.ts
These are the latest typings provided by the adjust/cordova_sdk v4.23.0.
https://github.com/adjust/cordova_sdk/blob/master/ionic-native/index.ts
Required for iOS14 development.
> feat(adjust): updating to official adjust v4.23.0 typings

- src/@ionic-native/plugins/imap/index.ts
Dear ionic team,
I have created a Cordova plugin that will allow an ionic application to use the features of the IMAP service. I need this plugin for the ionic application that I'm currently developing. 
This plugin can also be used by any other Ionic developer who wants to download and modify messages using the IMAP service. 
I have written clear and precise documentation for this plugin. 
I hope you will accept my pull request (the plugin I have developed).
This is the link of the plugin published on the NPM repository: https://www.npmjs.com/package/cordova-plugin-imap
> feat(cordova-plugin-imap) initial 'native wrapper' commit

- src/@ionic-native/plugins/bluetooth-le/index.ts
See merged PR: https://github.com/randdusing/cordova-plugin-bluetoothle/pull/647/files
> feat(bluetooth-le): Allow specifying transport mode for Android

- src/@ionic-native/plugins/purchases/index.ts
Updates to cordova-plugin-purchases 1.3.2
> feat(purchases): update to plugin version 1.3.2

- src/@ionic-native/plugins/custom-uisdk/index.ts
Paytm Custom UI sdk ionic wrapper to access cordova-plugin-customuisdk plugin methods
> feat(CustomUiSDK): add plugin for Paytm Custom UI SDK

- src/@ionic-native/plugins/facebook/index.ts
> Use cordova-plugin-facebook-connect in place of cordova-plugin-facebook4

- src/@ionic-native/plugins/firebase-messaging/index.ts
fix token remove function name according to
https://github.com/chemerisuk/cordova-plugin-firebase-messaging#deletetoken
> [firebase-messaging] fix deleteToken/removeToken signature

- src/@ionic-native/plugins/android-notch/index.ts
[cordova-plugin-android-notch](https://github.com/tobspr/cordova-plugin-android-notch) wrapper (See [opened issue](https://github.com/ionic-team/ionic-native/issues/3591))
> feat(android-notch): cordova plugin wrapper

- src/@ionic-native/plugins/blinkid/index.ts
Fix issue #3555 
By  adding missing blink id recognizer
> feat(blinkid): add blink id recognizer

- src/@ionic-native/plugins/launch-navigator/index.ts
based of https://github.com/dpa99c/phonegap-launch-navigator/blob/master/uk.co.workingedge.phonegap.plugin.launchnavigator.d.ts
> fix(launch-navigator): enableGeolocation and enableGeocoding typings

- src/@ionic-native/plugins/power-optimization/index.ts
Greetings to the Ionic Team!
I found this plugin that adds some nice methods no test and auto-diagnose notification problems that I'm sure you have found with custom android Roms like Xiaomi or Huawei. 
It wasn't available on ionic-native so I've followed your steps to contribute an add its wrapper and documented it with all the information available on the plugin page https://www.npmjs.com/package/cordova-plugin-power-optimization
I hope everything its good and you accept the pull request for it
Thanks!
> feat(power-optimization):  plugin initial wrapper

- src/@ionic-native/plugins/app-center-low-memory/index.ts
Adding support for `cordova-plugin-appcenter-generate-low-memory`.
> feat(plugin): add MS App Center LowMemory plugin

- src/@ionic-native/plugins/keychain-touch-id/index.ts
- Changing some function return types where Promise returns nothing.
- Adding `BiometryType`
>  refactor(keychain-touch-id): more specific return types

- src/@ionic-native/plugins/network/index.ts
Extends onChange Observable with types of connection to which it changed
> feat(network): update Network plugin

- src/@ionic-native/plugins/app-rate/index.ts
inAppReview and useCustomRateDialog are no longer used
add return type to getLocale
> chore: Update app-rate types

- src/@ionic-native/plugins/in-app-purchase-2/index.ts
- added manageBilling method for InApp Purchases 2
> feat(in-app-purchase-2): added manageBilling method (Changes Request)

- src/@ionic-native/plugins/checkout/index.ts
Checkout.com cordova plugin: https://www.npmjs.com/package/@checkout.com/cordova-plugin-checkout
> feat(checkout): add plugin

- src/@ionic-native/plugins/branch-io/index.ts
https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking-attribution/commit/6147a3e568d9f8d4efe190060188b3f08cfa0ad9
> feat(branch-io): add sendBranchEvent method

- src/@ionic-native/plugins/urbanairship/index.ts
onInboxUpdated, onShowInbox, onPushReceived, onNotificationOpened, onNotificationOptInStatus; fix return type for reattach method
> feat(urbanairship): add new methods: onDeepLink, onRegistration

- src/@ionic-native/plugins/web-server/index.ts
Change package cordova-plugin-webserver obsolete to cordova-plugin-webserver2
> fix(webserver): update to maintained repo

- src/@ionic-native/plugins/checkout/index.ts
Corrected the npm cordova plugin name
> fix(checkout): Update npm cordova plugin name

- src/@ionic-native/plugins/in-app-update/index.ts
This plugin enabels [In app update](https://developer.android.com/guide/playcore/in-app-updates) For cordova.
> feat(in-app-update): add plugin

- src/@awesome-cordova-plugins/plugins/adjust/index.ts
- Added missing `hasConversionValueUpdatedCallbackListener()` method to `AdjustConfig` to fix https://github.com/adjust/cordova_sdk/issues/147.
> fix(adjust): added missing AdjustConfig method

- src/@awesome-cordova-plugins/plugins/social-sharing/index.ts
> fix(social-sharing): change shareWithOptions parameter typing

- src/@awesome-cordova-plugins/plugins/firebase-x/index.ts
> fix(firebase-x): change incrementCounter signature

- docs/plugins/urbanairship.md
- src/@awesome-cordova-plugins/plugins/urbanairship/index.ts
There are some functions from the original plugin missing and tag groups were not working.
I implemented them to work as mentioned in the documentation of Airship:
https://docs.airship.com/platform/cordova/segmentation/#attributes
> feat(urbanairship): Add attributes editing and fix tag editing

- docs/SUMMARY.md
- docs/plugins/dynamsoft-barcode-scanner.md
- docs/plugins/dynamsoft-barcode-scanner/README.md
- src/@awesome-cordova-plugins/plugins/dynamsoft-barcode-scanner/index.ts
> feat (dynamsoft barcode scanner): add plugin

- src/@awesome-cordova-plugins/plugins/sms-retriever/index.ts
Update  URL 
import { SmsRetriever } from '@awesome-cordova-plugins/sms-retriever/ngx';
> docs(sms-retriever): update example

- package.json
Reverts danielsogl/awesome-cordova-plugins#4159
> Revert "chore(deps): update dependency jest to v28"

- docs/SUMMARY.md
Modify the link title `Http` to `ApproovHttp` for `plugins/approov-advanced-http.md`
> docs: update summary

- src/@awesome-cordova-plugins/plugins/firebase-analytics/index.ts
> docs(firebase-analytics): resolve typo

- docs/plugins/dynamsoft-barcode-scanner.md
- docs/plugins/dynamsoft-barcode-scanner/README.md
- src/@awesome-cordova-plugins/plugins/dynamsoft-barcode-scanner/index.ts
Update the wrapper to use the new Cordova plugin: https://github.com/xulihang/cordova-plugin-dynamsoft-barcode-reader
> feat(dynamsoft-barcode-scanner): update wrapper

- src/@awesome-cordova-plugins/plugins/in-app-purchase-2/index.ts
See: https://github.com/j3k0/cordova-plugin-purchase/releases/tag/v11.0.0
> feat(in-app-purchase-2): add launchPriceChangeConfirmationFlow

- src/@awesome-cordova-plugins/plugins/dynamsoft-barcode-scanner/index.ts
update Dynamsoft Barcode Scanner to allow setting camera resolution and return barcode result in bytes.
> feat(dynamsoft-barcode): update startScanning options

- src/@awesome-cordova-plugins/plugins/diagnostic/index.ts
This is to fix https://github.com/danielsogl/awesome-cordova-plugins/issues/4226
> fix(diagnostic): adjust options declaration

- src/@awesome-cordova-plugins/plugins/document-scanner/index.ts
The example is wrong. I updated the correctly import for DocumentScanner
> docs(document-scanner): update example

- src/@awesome-cordova-plugins/plugins/intercom/index.ts
https://github.com/intercom/intercom-cordova/blob/master/CHANGELOG.md#1210-2022-06-01
> feat(intercom): add displaySurvey

- src/@awesome-cordova-plugins/plugins/dynamsoft-barcode-scanner/index.ts
update Dynamsoft Barcode Scanner to allow setting zoom and focus
> feat(dynamsoft-barcode): add setFocus and setZoom

- src/@awesome-cordova-plugins/plugins/adjust/index.ts
- Updated `index.ts` to expose current state of Adjust Cordova SDK v4.30.0 to TS users.
> feat(adjust): update wrapper for Adjust Cordova SDK v4.30.0

- src/@awesome-cordova-plugins/plugins/webim/index.ts
> feat(webim): add plugin

- src/@awesome-cordova-plugins/plugins/device/index.ts
https://github.com/apache/cordova-plugin-device/pull/157
> feat(device): add sdkVersion

- src/@awesome-cordova-plugins/plugins/bluetooth-le/index.ts
New methods to check permission from Android 12+
Requires cordova-plugin-bluetoothle 6.7.0+ 
https://github.com/randdusing/cordova-plugin-bluetoothle/releases/tag/v6.7.0
> feat(bluetooth-le): upgrade to v6.7.0

- src/@awesome-cordova-plugins/plugins/launch-navigator/index.ts
> fix(launch-navigator): use currect handlers

- src/@awesome-cordova-plugins/plugins/diagnostic/index.ts
This PR should fix https://github.com/danielsogl/awesome-cordova-plugins/issues/4361 issue and also fix the minor issue with getLocationAccuracyAuthorization
> fix(diagnostic): addisCameraRollAuthorized and getCameraRollAuthorizationStatus functions

- src/@awesome-cordova-plugins/plugins/crop-plugin-privacy/index.ts
> feat(crop-privacy): add plugin

- src/@awesome-cordova-plugins/plugins/diagnostic/index.ts
> fix(diagnostic): add getBluetoothAuthorizationStatus function

- src/@awesome-cordova-plugins/plugins/file-chooser/index.ts
This PR partially resolves this issue https://github.com/danielsogl/awesome-cordova-plugins/issues/4155
> feat(file-chooser): add plugin

- src/@awesome-cordova-plugins/plugins/chooser/index.ts
https://github.com/MaximBelov/cordova-plugin-chooser/pull/2
> feat(chooser): add android 11+ support 

- src/@awesome-cordova-plugins/plugins/fingerprint-aio/index.ts
Changes:
- added confirmationRequired param to show method to options
- moved plugin errors to a separate enum
- changes some plugin method return values
> feat(fingerprint-aio): update plugin

- src/@awesome-cordova-plugins/plugins/smartlook/index.ts
Hi!
I'm a mobile SDK dev at Smartlook and we have just released a brand new rewrite of our [Cordova plugin](https://github.com/smartlook/cordova-smartlook/releases/tag/v2.0.0).
This PR mirrors the changes into the `Ionic plugin` wrapper.
Everything was tested locally on `Capacitor` with both `React` and `Angular` demo apps.
> feat(smartlook): rewrite smartlook ionic plugin

- src/@awesome-cordova-plugins/plugins/newrelic/index.ts
As of [newrelic-cordova-plugin v6.2.0](https://github.com/newrelic/newrelic-cordova-plugin/releases/tag/6.2.0), we have added a shutdown method.
> feat(newrelic): add shutdown method

- docs/SUMMARY.md
- docs/plugins/save-dialog.md
- docs/plugins/save-dialog/README.md
- docs/plugins/smtp-client/README.md
- src/@awesome-cordova-plugins/plugins/clevertap/index.ts
- src/@awesome-cordova-plugins/plugins/diagnostic/index.ts
- src/@awesome-cordova-plugins/plugins/firebase-model/index.ts
- src/@awesome-cordova-plugins/plugins/save-dialog/index.ts
Property got introduced with v7.1.0 but never exposed to TS.
> fix(diagnostic): add LIMITED permissionStatus

- docs/plugins/adjust/README.md
- docs/plugins/admob-plus/README.md
- docs/plugins/cashfree-pg/README.md
- docs/plugins/fabric/README.md
- docs/plugins/firebase-model/README.md
- docs/plugins/hyper-track/README.md
- docs/plugins/nfc/README.md
- docs/plugins/purchases/README.md
- docs/plugins/save-dialog/README.md
- docs/plugins/sign-in-with-apple/README.md
- docs/plugins/smtp-client/README.md
- docs/plugins/tealium/README.md
- docs/plugins/unvired-cordova-sdk/README.md
- docs/plugins/wonderpush/README.md
- src/@awesome-cordova-plugins/plugins/purchases/index.ts
> Revenue cat update to cordova 5

- docs/plugins/cloud-settings/README.md
- docs/plugins/save-dialog/README.md
- docs/plugins/smtp-client/README.md
> docs(cloud-settings): Change installation example to use plugin author's package ID 

- src/@awesome-cordova-plugins/plugins/firebase-x/index.ts
- src/@awesome-cordova-plugins/plugins/firebase/index.ts
Adds support of [fetchAndActivate](https://github.com/dpa99c/cordova-plugin-firebasex/?tab=readme-ov-file#fetchandactivate)
Adds support of [getAll](https://github.com/dpa99c/cordova-plugin-firebasex/?tab=readme-ov-file#getall)
> feat(adjust): Add Remote Config missing functions

- src/@awesome-cordova-plugins/plugins/airship/index.ts
Package Changes
https://github.com/urbanairship/urbanairship-cordova/blob/main/MIGRATION.md#package-changes
https://docs.airship.com/platform/mobile/setup/sdk/cordova/
Airship Plugin
https://github.com/urbanairship/urbanairship-cordova/pull/423
> feat(airship): add plugin

- src/@awesome-cordova-plugins/plugins/firebase-x/index.ts
fetchFirestoreCollection method has supported filters for like 3 years now.
Here is the reference to firebase-x plugin:
https://github.com/dpa99c/cordova-plugin-firebasex/blob/0872ef47ab7173642522d571c3825ebd3d3ff169/types/index.d.ts#L463
> fix(firebase-x): filters for fetchFirestoreCollection

- src/@awesome-cordova-plugins/plugins/airship/index.ts
Plugin
https://github.com/urbanairship/urbanairship-cordova/pull/428
> feat(airship): add isForeground to push received events

- src/@awesome-cordova-plugins/plugins/firebase-x/index.ts
Aliging with latest plugin with consent mode
> feat(firebase-x): add consent mode

- src/@awesome-cordova-plugins/plugins/ssl-certificate-checker/index.ts
> fix(ssl-certificate-checker): adjust method interfaces to follow plugin api

- src/@awesome-cordova-plugins/plugins/adjust/index.ts
- Updated `index.ts` to expose current state of Adjust Cordova SDK v5.0.0 to TypeScript users.
> feat(adjust): update wrapper for Adjust Cordova SDK v5.0.0

- src/@awesome-cordova-plugins/plugins/shortcuts-android/index.ts
https://github.com/avargaskun/cordova-plugin-shortcuts-android/pull/8
> feat(shortcuts-android): add plugin

- src/@awesome-cordova-plugins/plugins/intercom/index.ts
https://github.com/intercom/intercom-cordova/pull/329
> feat(intercom): add support cordova-intercom v14+

- src/@awesome-cordova-plugins/plugins/firebase-model/index.ts
chore(firebase-model): migrate from @ionic-native/core to @awesome-cordova-plugins/core
> fix(firebase-model): updated to @awesome-cordova-plugins/core

- docs/plugins/i-root/README.md
- src/@awesome-cordova-plugins/plugins/i-root/index.ts
This PR revives and builds upon the feature originally introduced by [adrenaline15](https://github.com/adrenaline15) in PR [#4632](https://github.com/danielsogl/awesome-cordova-plugins/pull/4632). All credit for the initial implementation goes to [adrenaline15](https://github.com/adrenaline15).
> feat(cordova-plugin-iroot): add plugin

- .github/workflows/nodejs.yml
- .github/workflows/npmpublish.yml
@danielsogl 
**Result**
https://github.com/MaximBelov/awesome-cordova-plugins/actions/runs/11128358153/job/30922898172
> ci: update node-version from 16 to 20

- src/@awesome-cordova-plugins/plugins/in-app-purchase-2/index.ts
- src/@awesome-cordova-plugins/plugins/in-app-purchase-3/index.ts
Should be correct now, I've ran `npm run readmes` locally without commit changes (since it changes other files than mines).
@danielsogl I'm wondering, what the downside of including readmes generation on pre-commit hook ? This could prevent future issues like this
(or at least updating DEVELOPERS.md to advice for a pre-commit checklist)
>  feat(in-app-purchase-3) new InAppPurchase3 plugin fixed

- src/@awesome-cordova-plugins/plugins/status-bar/index.ts
https://github.com/apache/cordova-plugin-statusbar/pull/229
> chore(status-bar): remove deprecated methods

- src/@awesome-cordova-plugins/plugins/intercom/index.ts
https://github.com/intercom/intercom-cordova/pull/337
> feat(intercom): Add new methods

- src/@awesome-cordova-plugins/plugins/bluetooth-classic-serial-port/index.ts
https://github.com/MaximBelov/cordova-plugin-bluetooth-classic-serial-port/releases/tag/1.0.0
> fix(bluetooth-classic-serial-port): support multiple simultaneous connections using the same protocol string

- src/@awesome-cordova-plugins/plugins/unvired-cordova-sdk/index.ts
Added new properties and functions
> feat(cordova-plugin-unvired-sdk): added new function
